### ISSUE TITLE
Consider using bounded FIFO instead of unbounded

### ISSUE THREAD

**Issue by jchia** [jtdaugherty/brick#106]
`Control.Concurrent.Chan.Chan` is unbounded. `Control.Concurrent.STM.TBQueue.TBQueue` is bounded.

Someone thinks that unbounded FIFOs are usually a bad idea and I tend to agree. http://lorepub.com/post/2016-12-17-Haskell-Pitfalls

Currently, my own app avoids unboundedness by using two channels, one for each direction, one channel just for ACK. On the other channel, I don't send another item until I have received an ACK. If I use a bounded channel of capacity 1, I don't need the ACK mechanism and I just need to use one channel.

**Comment by jtdaugherty** [comment]
I would be happy to consider a patch migrating the library to, say, `TBQueue`.

**Comment by jchia** [comment]
`Control.Concurrent.Chan.Chan` and `Brick.Main.defaultMain` et al operate in `IO` whereas `Control.Concurrent.STM.TBQueue` operates in `STM`. Thus, I think switching to `TBQueue` entails both the library and the user using `atomically :: STM a -> IO a` for reading and writing the channel. Seems a bit cumbersome.

On the other hand, `unagi-chan` operates in `IO`, but I don't know how popular or stable `unagi-chan` is.

Thoughts?

**Comment by jtdaugherty** [comment]
Since `stm` is going to be available everywhere, I feel better about adding the `stm` dependency. From an API perspective, I want this hidden behind a brick API so users don't have to care that it's implemented using STM. So, something like this (although I want to think more about naming it):
```
data BrickChan a = BrickChan (TBQueue a)

newBrickChan :: IO (BrickChan a)
writeBrickChan :: BrickChan a -> a -> IO ()
readBrickChan :: BrickChan a -> IO a
```

**Comment by jtdaugherty** [comment]
Also, I forgot to include a bound parameter to `newBrickChan`.

**Comment by jchia** [comment]
It turns out that `customMain` relays user events from one channel to another in a special thread. Thus, whatever capacity the user sets on the input `mUserChan` has diminished effect on flow control. E.g. even if he uses a capacity of 1, if the downstream channel has a capacity of 2, there can be up to 3=1+2 outstanding user events.

Unfortunately, AFAIK, there's no built-in facility supporting blocking read from multiple channels in `TBChan` a la Unix `select`. Otherwise, we could put terminal events and user events in separate channels.

**Comment by jchia** [comment]
I think I found a way to read from two channels, using `orElse`.

**Comment by jtdaugherty** [comment]
I assume it's safe to close this now that your pull request is merged. Feel free to re-open if there's more to be done!
