### ISSUE TITLE
brick installs docs as data

### ISSUE THREAD

**Issue by hramrach** [jtdaugherty/brick#114]
* this is somewhat incorrect
* cabal-rpm does not handle data failing to produce usable brick package

--- brick-0.17/brick.cabal~	2017-01-24 23:10:23.000000000 +0100
+++ brick-0.17/brick.cabal	2017-02-06 14:38:59.238834815 +0100
@@ -38,7 +38,7 @@
 Homepage:            https://github.com/jtdaugherty/brick/
 Bug-reports:         https://github.com/jtdaugherty/brick/issues
 
-data-files:          README.md,
+extra-doc-files:     README.md,
                      docs/guide.rst,
                      CHANGELOG.md

**Comment by jtdaugherty** [comment]
Thanks for the report! I'll make the change. In the future, would you be willing to submit a pull request instead of providing an inline diff?
