### ISSUE TITLE
availWidth/Height reports 10000

### ISSUE THREAD

**Issue by clojj** [jtdaugherty/brick#117]
playing with the EditDemo, even though hLimit and vLimit are set, the context (inside the editor's rendering function) reports always 10000 rows/columns.

Shouldn't the Context's widht/height tell the effective dimensions ?
seems like 10000 is the terminal's maximum (?)

Basically, I want to know the effective rows/columns which are visible in the editor, in order to optimize rendering for that 'window' into the rendered string-datastructure.

**Comment by jtdaugherty** [comment]
The reason is because the editor is rendered inside a `viewport`, and viewports work by temporarily raising the rendering limits to `10000` before cropping and translating the final result. Can you say more about what you're trying to do that is running into this behavior?

**Comment by jtdaugherty** [comment]
(Closed accidentally.)

**Comment by clojj** [comment]
Ok, so how would I go about getting widht and height _after_ cropping ?

**Comment by jtdaugherty** [comment]
I'm not sure what you are trying to do yet. Can you provide some example code and describe what you'd like it to do?

**Comment by clojj** [comment]
Take for example the 'str' Widget:

`str :: String -> Widget n
str s =
    Widget Fixed Fixed $ do
      c <- getContext
      let theLines = fixEmpty <$> (dropUnused . lines) s
          fixEmpty [] = " "
          fixEmpty l = l
          dropUnused l = takeColumns (availWidth c) <$> take (availHeight c) l
      case force theLines of ....

`
It tries to 'optimize' away invisible columns/rows with 'dropUnused'
But with values of 10000 (at this point of rendering inside a viewport), the actual visible cols/rows can't be selected (and rendered), it seems..

**Comment by jtdaugherty** [comment]
With values of `10000`, that means it's very likely that `str` will *always* show all of the text it is given, and it is up to the `viewport` to crop away invisible lines. Does that make sense?

In the case of the editor, since the contents are rendered in a viewport, whatever you do to draw the contents should *by definition* not worry about the number of rows and columns since the `viewport` crops and pans automatically.

However, if that means the `viewport` is getting your way, perhaps the built-in `Editor` is not appropriate for what you are trying to do. (For example, the built-in editor is *not* intended to be used to build complex text editors for large documents; it is provided only as a basic input convenience.)

**Comment by clojj** [comment]
> With values of 10000, that means it's very likely that str will always show all of the text it is given, 
That is exactly what I am trying to optimize
I would like to base my new editor on Edit.hs which is using a viewport.. necessary for having a scroll-view of a large document.

So can I get at this cropping information of the viewport ?

**Comment by jtdaugherty** [comment]
The information is available:

http://hackage.haskell.org/package/brick-0.17/docs/Brick-Main.html#v:lookupViewport

However, please note that the information is about the *most recent rendering*, which means that will probably be out of date by the time you need it. The data flow path will be
```
1. Event handler calls lookupViewport, stores in application state
2. Rendering function runs, draws UI, which looks at stored viewport state
3. Rendering completes, viewport is updated as a result of rendering
```

**Comment by clojj** [comment]
> the information is about the most recent rendering, which means that will probably be out of date by the time you need it.

If that viewport never changes in size (by any neighbors/layout..?), wouldn't it be up-to-date all the time ?

**Comment by clojj** [comment]
I just checked this... in my setup _vpSize never changes between events

**Comment by clojj** [comment]
> 1. Event handler calls lookupViewport, stores in application state
2. Rendering function runs, draws UI, which looks at stored viewport state
3. Rendering completes, viewport is updated as a result of rendering

That plan works for now. Thanks!

**Comment by jtdaugherty** [comment]
It might not change now, but if you resize the window, just after the resize, the viewport state will be stale. It will also be stale any time anything *else* causes your viewport size to change, so resizes aren't the only possible cause.

**Comment by jtdaugherty** [comment]
Given the warning I've provided here, if there is anything else I can do, please let me know. If not, please close this ticket.

**Comment by clojj** [comment]
It would be nice to have lookupViewport inside Widget ... before rendering.
