### ISSUE TITLE
Infinitely many resource names

### ISSUE THREAD

**Issue by JacksonGariety** [jtdaugherty/brick#119]
I'm working on a text editor in which you will be able to split the window as many times as you please (an infinite number, if you will). Only one widget will report a cursor position.

It seems like each resource name needs to be a data type, and each name is associated with a cursor location report. How would I go about having an infinite number of widgets, one of which reports a cursor, with `brick`?

I love this software. Thanks!

**Comment by jtdaugherty** [comment]
You might have a resource name type like
```
data Name = WindowPane PaneID
          | ...
```
where `PaneID` is the sufficiently large type (say `Integer`) that you use to assign unique identifiers to the panes that make up a split window. Does that make sense?

**Comment by jtdaugherty** [comment]
Reading your questions again, I now see another one I missed: the one about how to report one among many cursor locations. To do that, your `App` field for choosing the cursor, `appChooseCursor`, could look at your application state and return the resource name corresponding to the currently "focused" window pane. For example,
```
App { ...
    , appChooseCursor = \st _ -> Just $ WindowPane $ activePaneID st
    , ...
```
If appropriate it would look at the second parameter (here `_`) of type `[CursorLocation n]` and choose the one from the list that it deems appropriate given the application's current state.

**Comment by JacksonGariety** [comment]
Thank you. This is helpful.
