### ISSUE TITLE
incorrect size for widget between horizontal borders

### ISSUE THREAD

**Issue by simonmichael** [jtdaugherty/brick#12]
```
      l = list ...
      border = borderWithLabel label
      hborder w = hBorderWithLabel label
                  <=>
                  w
                  <=>
                  hBorder
      ui1 = border l
      ui2 = hborder l
```
ui1 is a list inside a border; it is sized correctly. ui2 is the same list without the side borders; it overflows the bottom of the screen by one or two rows, so you can't see the bottom border or the bottom-most list row.

**Comment by jtdaugherty** [comment]
Would it be possible for you to post a complete working example program here?

**Comment by simonmichael** [comment]
It was my error, figured out from looking at your border code. I needed to limit the size of the wrapped widget.

**Comment by jtdaugherty** [comment]
Okay. Once you confirm that things are working as desired, feel free to close this issue.
