### ISSUE TITLE
The `HandleEvent` type class is missing without trace (except git history)

### ISSUE THREAD

**Issue by deepfire** [jtdaugherty/brick#121]
The `CHANGELOG.md` has no migration hints on how to transcend into the post-`HandleEvent` state of existence.

Moreover, the documentation and comments still refer, in several places, to `HandleEvent` as if it were a thing.

Makes one wonder : -)

(For the record, the type class disappeared in  3081e7367d50e45a518457782c5233d8261fe449, dated `2016-03-05 01:42:49`, and the change first featured in `0.7`, released `2016-05-27`)

**Comment by jtdaugherty** [comment]
Thanks for this report! I kinda can't believe I didn't mention the removal of `HandleEvent` in the changelog. I'll definitely update the docs to ensure that it isn't mentioned anywhere.

As to how to live without it, for any types that instanced it before, there is now a corresponding handler function that you can call: `handleListEvent` and `handleEditorEvent`.

**Comment by jtdaugherty** [comment]
(And `handleDialogEvent`.)

**Comment by jtdaugherty** [comment]
For what it's worth, the User Guide actually does specifically point out how to handle events in the first paragraph of the section entitled `Widget Event Handlers`.

**Comment by jtdaugherty** [comment]
I've committed https://github.com/jtdaugherty/brick/commit/cf96e9e8eae33b7d2644cbed7e96e7769635f5e4; if that addresses your concerns, please close this ticket (or let me know what else I can do). Thanks!

**Comment by deepfire** [comment]
Thank you!
