### ISSUE TITLE
Increasing the utility of the focusRing

### ISSUE THREAD

**Issue by JacksonGariety** [jtdaugherty/brick#122]
It would be really great if we could push and pop names onto and off of the focusRing as well as manually set the focused index.

As of right now it seems the only way to do this is to reconstruct the ring with the desired focus at index 0.

**Comment by jtdaugherty** [comment]
Those operations would indeed be useful. The `FocusRing` API is pretty lean right now, but if I broaden it I'd really like to avoid having to add all those features myself; one approach would be to make the `FocusRing` use a `CList` internally:

**Comment by JacksonGariety** [comment]
`CList` looks perfect.

**Comment by jtdaugherty** [comment]
This is now released in version `0.18`.
