### ISSUE TITLE
And an instance of `MonadTransControl` to EventM

### ISSUE THREAD

**Issue by jfischoff** [jtdaugherty/brick#123]
I would like to be able to catch exceptions or basically anything I could do with `IO` in the `EventM` but this not possible with merely `MonadIO`. 

With a `MonadTransControl` instance from the `monad-control` package this would be possible by using the `lifted-base` package. Here is what I think the implementation would be:

```haskell
instance MonadTransControl (EventM n) where
  type StT EventM a = StT (ReaderT (EventRO n) (StateT (EventState n) IO) a) a
  liftWith = defaultLiftWith EventM runEventM
  restoreT = defaultRestoreT EventM
```

It is possible that this is totally ill conceived and I should structure my program in a way where I don't catch exceptions in EventM but from what I can tell this is where the bulk of the program logic is expected to live, and thus I should be able to do these things.

An alternative to this approach would be to use the `exceptions` package, although `MonadTransControl` also enables other features of `IO` like `forkIO`, however it is unclear to me what aspects of `brick` (and more importantly it's underlying dependencies) and if it would be advisable to fork threads in the `EventM` anyway.

**Comment by jtdaugherty** [comment]
Thanks for the explanation and proposal; I would be happy to consider a pull request to add this instance (and package dependency).

**Comment by jfischoff** [comment]
I will do that, but I'm also found a fairly obvious workaround in retrospect (just using `liftIO . try`). If I get stuck I will reopen and make the PR.

**Comment by jtdaugherty** [comment]
Okay. Sounds good! I was going to suggest `liftIO . try`, so I'm glad you know about that now.
