### ISSUE TITLE
Expose the types `EventRO`  and `EventState`

### ISSUE THREAD

**Issue by jfischoff** [jtdaugherty/brick#124]
The type `EventM` exposes constructors that expose the types `EventRO`  and `EventState` but they are not exposed ... or at least haddock does not think they are. 

I don't need the constructors but I would like to be able to make an orphan instance for `EventM` of the `MonadTransControl` (issue #123) class, and I require the types to be in scope. Additionally it is better documentation wise to have the types be linkable in haddock even if the constructors are not exposed.

**Comment by jtdaugherty** [comment]
If #123 is resolved, will this still be important to you?

**Comment by jfischoff** [comment]
No it is not important to me.

**Comment by jtdaugherty** [comment]
Okay - then on that note, I'll close this in accordance with your comment. Thanks!

**Comment by jfischoff** [comment]
:)
