### ISSUE TITLE
Markup doesn't seem to work

### ISSUE THREAD

**Issue by mitchellwrosen** [jtdaugherty/brick#130]
This widget renders white:

```haskell
markup ("Hello" @@ (defAttr `withForeColor` red))
```

whereas this widget renders red:

```haskell
raw (Graphics.Vty.Image.text (defAttr `withForeColor` red) "Hello")
```

Am I misunderstanding something about the markup API? Thanks so much!

**Comment by jtdaugherty** [comment]
Interesting - is there a difference for you between that and this?
```
import Brick.Util (fg)
markup ("Hello" @@ fg red)
```

**Comment by jtdaugherty** [comment]
There *shouldn't* be, but I'm looking at `programs/MarkdupDemo.hs` and wondering how it could be broken.

**Comment by jtdaugherty** [comment]
In fact, there won't be, since it just does what you did anyway. Hm.

**Comment by jtdaugherty** [comment]
If you run the Markup demo from the `brick` demo directory, does it work as the code suggests it will?

**Comment by mitchellwrosen** [comment]
It does! Odd.

**Comment by mitchellwrosen** [comment]
I figured out the issue. I was using `const (forceAttrMap defAttr)` as an "empty" attr map, instead of `const (attrMap defAttr [])`

**Comment by jtdaugherty** [comment]
Ah, that would do it!
