### ISSUE TITLE
other kinds of IO

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [jtdaugherty/brick#132]
Suppose you wanted to write a Brick program that asks the user for a name of a file, and then reads it into a widget. The type signatures for the fields in the App type suggest to me that it can't be done from within Brick. The suspend-and-resume idiom (as shown in one of your demo programs) seems like it could do the job, though. Is that correct?

**Comment by jtdaugherty** [comment]
1. Yes, you could do it with `suspendAndResume`.
2. But you could also do it without exiting brick at all, by using an editor widget (see the edit demo).

**Comment by jtdaugherty** [comment]
Actually, I just noticed:
> The type signatures for the fields in the App type suggest to me that it can't be done from within Brick.

What makes you say this?

**Comment by jtdaugherty** [comment]
Are you aware that `EventM` is a `MonadIO` instance? So that you can do any IO you please in any event handler, just by using `liftIO`:
```
handleEvent state ev = do
  result <- liftIO $ someIOAction ...
  continue $ s & storedResult .~ result
```

**Comment by JeffreyBenjaminBrown** [comment]
Fantastic! I was hoping that was the case. (Understanding monad transformers is high on my to-do list ...)

**Comment by jtdaugherty** [comment]
Just so you're aware this is also mentioned at https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#apphandleevent-handling-events

**Comment by JeffreyBenjaminBrown** [comment]
Nice! I didn't realize there was documentation -- let alone so much of it.

**Comment by jtdaugherty** [comment]
Great - you might consider checking this section of the README, which links to all documentation sources:

https://github.com/jtdaugherty/brick#documentation

**Comment by JeffreyBenjaminBrown** [comment]
Very cool.
