### ISSUE TITLE
Q: App's display region in terminal

### ISSUE THREAD

**Issue by afgno** [jtdaugherty/brick#137]
Hi, is it possible to specify how many lines the App uses in the terminal? For example, If I wanted to display it only in the bottom half of the terminal without clearing the whole screen. If not, would this work using vty directly?

Thanks

**Comment by jtdaugherty** [comment]
I'm afraid not; `vty` (and thus `brick`) is designed to take control over the entire available screen area. If you want to do this sort of thing you might consider integrating with `tmux`, which lets you split the screen as you see fit and run different programs in each section.
