### ISSUE TITLE
Add a list handler w/ vi keybindings?

### ISSUE THREAD

**Issue by rhofour** [jtdaugherty/brick#139]
In my own project I'm adding vi keybindings for list movement. Would there be any interest in upstreaming this?

I was thinking something like:
`handleListEventVi :: Ord n => (Event -> List n e -> EventM n (List n e)) -> Event -> List n e -> EventM n (List n e)
`
So instead of: `handleListEvent event list`, you could use `handleListEventVi handleListEvent event list` to add the extra keybindings. Alternatively, these bindings could just be added to handleListEvent.

**Comment by jtdaugherty** [comment]
Which `vi`-style bindings are added by your handler?

**Comment by rhofour** [comment]
Just movement stuff. Up, Down, Page Up, Page Down, Half Page Up, Half Page Down, and maybe start and end. So nothing particularly interesting.

**Comment by jtdaugherty** [comment]
I'd be okay with a patch to `brick` for this provided it's implemented as a separate function as you proposed above.

**Comment by rhofour** [comment]
If it doesn't prove too hard I'll also add: top-of-screen, middle-of-screen, and bottom-of-screen

I don't think these are currently possible to implement with the exposed functions so I'll also probably add another function like listMoveToRelative where listMoveToRelative 0 moves to the first element displayed. Does that also sound reasonable?

**Comment by rhofour** [comment]
Also, I was thinking it made sense to showcase this in brick-list-demo. Let me know if you disagree.

**Comment by jtdaugherty** [comment]
I think that `listMoveToRelative 0` is actually `listMoveToAbsolute`; there is already `listMoveBy` for relative movement, and `listMoveTo` for absolute movement, so those already exist. You can implement `listMoveToTop` and `listMoveToBottom` in terms of `listMoveTo`.

**Comment by jtdaugherty** [comment]
(I now see what you mean by "first element displayed." I'm not sure how valuable bindings for that would be, but the rest would be okay with me.)

**Comment by jtdaugherty** [comment]
As for the list demo, I'd prefer a separate list demo that shows these bindings in use, just so the list demo that I already have can remain as simple as possible and the extra demo can show how it can be extended. I realize the code will be almost entirely the same, but my goal with the demos is to show only one feature at a time.

**Comment by rhofour** [comment]
I personally find those bindings useful in vi and I can imagine them being quite useful in navigating a particularly long list, but I understand if you think they're too much to include here. Could I add least add `listMoveToRelative` so it's possible to implement them outside of Brick? I'm open to a better name for it and it would be documented to make it what it does (I'm thinking a short example would help).

I'll make a new brick-list-demo-vi which adds the vi keybindings instead of changing the existing one.

**Comment by jtdaugherty** [comment]
* For the demo, please call it `brick-list-vi-demo`.
* For `listMoveToRelative`, let's work out a concise description of what it does and perhaps a better name will be more self-evident.

**Comment by jtdaugherty** [comment]
(Also please call the source file `ListViDemo.hs` to be consistent with the others.)

**Comment by jtdaugherty** [comment]
Thanks for the extra changes! Please close this ticket if the merge takes care of it, or let me know what else you would like.

**Comment by jtdaugherty** [comment]
The changes in the merge are now released in `0.26`.

**Comment by rhofour** [comment]
Ok. I might want to add listMoveToRelative later, but I'll open another issue then.

**Comment by jtdaugherty** [comment]
Sounds good!
