### ISSUE TITLE
Forms: custom validation

### ISSUE THREAD

**Issue by angerman** [jtdaugherty/brick#154]
The validation logic only allows to take `b -> Maybe a`.  Now for my current use case, I need to
validate through some IO action, this seems impossible now.

The documentation also does not say *when* the input is validated. E.g. for my current use case
(validating a password against a database), I want the validation to happen only if I ask for `allFieldsValid`, and I certainly would not want it to run on each say keypress, but it looks like it
is run on every redraw.

The alternative would be to allow some custom validation and allow me to set fields as invalid. E.g.
allow me to set fields as valid/invalid by hand.

**Comment by jtdaugherty** [comment]
> The documentation also does not say *when* the input is validated.

From the User Guide:

> Whenever an input field in the form handles an event, its contents are validated and rewritten to the form state (in this case, a UserInfo record).

And from the Haddock for `handleFormEvent`:

> In all cases where an event is forwarded to a form field, validation of the field's input state is performed after the event has been handled

If those don't make it clear enough, I'm happy to improve the wording.

As for your use case, that makes sense that you'd want to do that kind of thing, but the form validation API is intended to provide value validation, not environmental validation. I'll look at writing e.g. `setFieldValid :: Bool -> n -> Form s e n` soon.

Thanks!

**Comment by jtdaugherty** [comment]
This is now done on a branch - check it out and let me know if that works for you: https://github.com/jtdaugherty/brick/commit/23b8f291e21fd200c940f49b43518e67b6624d8c

**Comment by jtdaugherty** [comment]
Have you had a chance to take a look at this? I'd like to release it soon, if it works for you.

**Comment by angerman** [comment]
Hi @jtdaugherty, I'm sorry I haven't gotten around to it yet. I'll try to see if I can manage to get around to it today. Latest tomorrow.

**Comment by jtdaugherty** [comment]
Oh, I don't mean to hurry you. I was just eager to release it if it works. :)

**Comment by angerman** [comment]
Alright. This seems to work quite nicely.
![](https://user-images.githubusercontent.com/40449/34858743-fb9d5c56-f78c-11e7-8cdc-615dba751efe.png)
![](https://user-images.githubusercontent.com/40449/34858744-fbce2dfe-f78c-11e7-9725-89aada88f8c0.png)

**Comment by jtdaugherty** [comment]
Okay, great!

**Comment by jtdaugherty** [comment]
This is now released in `0.33`.
