### ISSUE TITLE
Do not wrap around dialog button selection with arrow keys

### ISSUE THREAD

**Issue by kostmo** [jtdaugherty/brick#156]
Tab/shift-tab can cycle back to the beginning/end, respectively, to focus within a set of dialog buttons.

However, there should also be a "saturating" cycle mechanism available, so as to disambiguate which button is actually selected when there are only two buttons.  This may as well be the arrow keys.

I will post a PR for this change.

**Comment by kostmo** [comment]
As an example, unless there are some other context cues from the application, it can still be ambiguous which button is currently selected below:
![selection1](https://user-images.githubusercontent.com/261693/35706348-4f160e96-075a-11e8-9c25-11af21fec3b9.PNG)
![selection2](https://user-images.githubusercontent.com/261693/35706354-53f85f4a-075a-11e8-8397-71d51f9bdfd2.PNG)

In such a scenario, with the saturating behavior a user will at least be able to use the right arrow key to verify that they have landed on the right-most dialog button.

**Comment by jtdaugherty** [comment]
That makes sense - thank you for the patch!
