### ISSUE TITLE
Scrolling a list widget that isn't at the top of the screen can result in an off-screen selected item

### ISSUE THREAD

**Issue by ktvoelker** [jtdaugherty/brick#17]
The program I'm working on has a list widget, but above the list widget are a fixed number of lines of plain-old text. The presence of those header lines seems to screw up the scrolling/visibility logic a bit.

Terminal version: iTerm2 2.1.1 and Terminal 2.5.3 (both on OS X Yosemite)
GHC version: 7.10.2
brick version: 0.2
vty version: 5.4.0
A simple repro program: https://github.com/ktvoelker/brick-demo

Steps to reproduce:
1. Run the program
2. Press the Down key until the last visible item is selected.
3. Press the Down key one more time.
4. An item is selected which is not visible.

Expected behavior:
4. The list scrolls and the item becomes visible.

Note that if you press Down a few more times, eventually the list does start scrolling in the right direction. But it never catches up, so the selected item is always off-screen. The size of this "offset" appears to be equal to the number of lines of header text, plus one.

I would be glad to work on fixing the bug myself, but I wanted to make sure that it actually is a bug, first.

**Comment by jtdaugherty** [comment]
Thanks for the fantastic bug report. I've pushed a fix in a89df7b04c95782d8f0c1ba3306bcf7ab427a1c1. Give it a try!

**Comment by ktvoelker** [comment]
Works for me, thanks!

**Comment by jtdaugherty** [comment]
Okay.  If this is resolved to your satisfaction, please close the ticket.

**Comment by jtdaugherty** [comment]
FYI, this fix has been released as part of `0.2.1`.
