### ISSUE TITLE
Inconsistent coordinates in MouseDown and MouseUp events

### ISSUE THREAD

**Issue by goodsoft** [jtdaugherty/brick#173]
https://github.com/jtdaugherty/brick/blob/master/src/Brick/Main.hs#L268

As I see from the code above, the `MouseDown` event coordinates are adjusted to viewport scroll position.
Though, this doesn't happen for `MouseUp` event.
As a result, when I click in one screen position, I get different coordinates for these events.

Is this behaviour deliberate, or an unfortunate mistake?

**Comment by jtdaugherty** [comment]
Thanks! This is now fixed and released in `0.36.3`.
