### ISSUE TITLE
Non-Both viewport doesn't defer its sizing policy to widget

### ISSUE THREAD

**Issue by goodsoft** [jtdaugherty/brick#174]
https://github.com/jtdaugherty/brick/blob/master/src/Brick/Widgets/Core.hs#L955

According to the code above, viewport is always greedy in both directions, irregardless of its type and widget's sizing policy.
I suppose `Vertical` viewport should defer its horizontal sizing policy to widget, and vice versa for `Horizontal` viewport.

**Comment by jtdaugherty** [comment]
The rationale for using `Greedy` regardless of the child widget's policy is that the viewport's size doesn't depend on the child, but on the surrounding layout. It could work as you describe, but that's somewhat counter to the intent and changing it now could break some interfaces.

Is there a layout you're wanting to implement that caused you to run into this?

**Comment by goodsoft** [comment]
Basically, I have a custom list view on the left, and a details view on the right.
I want the list view to be exactly the size of its largest element and vertically scrollable, while details view to cover the whole remaining screen.

**Comment by jtdaugherty** [comment]
The way to get what you want is to `hLimit` the list:
```
hLimit listWidth someList <+> detailsView
```

**Comment by goodsoft** [comment]
Okay, if you consider current behaviour correct, then I will probably resort to creating a custom `hLimit` widget, which will take underlying image dimensions.

**Comment by jtdaugherty** [comment]
Okay, I'm glad you have a path forward. Thanks for the tickets!

**Comment by goodsoft** [comment]
In case someone else stumbles on this issue, here's my workaround:
```
fixedViewport
  :: (Ord n, Show n)
  => n
  -> ViewportType
  -> Widget n
  -> Widget n
fixedViewport name vpType p = case vpType of
  Both -> Widget Greedy Greedy render
  Vertical -> Widget (hSize p) Greedy render
  Horizontal -> Widget Greedy (vSize p) render
  where
    render = do
      result <- render p
      render $
        limit result .
        viewport name vpType $
        Widget (hSize p) (vSize p) (return result)
    limit :: Result n -> (Widget n -> Widget n)
    limit result = case vpType of
      Vertical -> hLimit (result ^. imageL & imageWidth)
      Horizontal -> vLimit (result ^. imageL & imageHeight)
      Both -> id
```

**Comment by jtdaugherty** [comment]
I'm afraid that won't quite work: `render p` takes place under the original rendering context, which has not had its available width and height fields relaxed by the `viewport` functionality. So this means that the result of `render p` here, for most values of `p`, will never be larger than the area described by the active rendering context. (Contrast this with `viewport`, where the context's available width and/or height are set to an obscenely high value depending on the viewport type, thus permitting `p` to take up more room than the viewport has in its parent layout.)

To test what I'm talking about, try this with a `p` that is larger than the space of the viewport itself and notice that you never get to see more of `p` than will fit in the viewport itself.

**Comment by goodsoft** [comment]
Surprisingly enough, it works for me even in your described case.
Probably, because I'm not using `avail*` in underlying widget at all, just generating an `Image`.

Though, even if I used `avail*`, it should be trivial to relax them the same way you do it in `viewport`.

**Comment by jtdaugherty** [comment]
> Probably, because I'm not using avail* in underlying widget at all, just generating an Image.

Yeah, that would explain it. When I said "most values of `p`", I was referring to the fact that most widget constructors will crop their results to fit in the space described by the context. You're right that you could use the same technique as the `viewport` constructor, if you wanted to.

**Comment by goodsoft** [comment]
Not sure if cropping the content of a viewport yourself is a good idea anyway :)

**Comment by jtdaugherty** [comment]
Yes, the cropping is optional. But the tendency for most of the built-in constructors to do that is just something to be aware of, since in many cases (other than the one you have going right now), it will make `fixedViewport` not behave as you want. The widgets are *supposed* to honor the context, which is why the viewport constructor does the weakening that it does.
