### ISSUE TITLE
Reported extents don't take into account widget greediness

### ISSUE THREAD

**Issue by goodsoft** [jtdaugherty/brick#175]
My use case:
1. Create a widget with fixed vertical and greedy horizontal sizing policies.
2. Render fixed-size text in the top-left corner (think shell prompt)
3. Wrap it in `clickable`

Expected result: `MouseDown` events are generated for the whole actual extent of widget.
Actual result: events are generated only for extent of rendered image.

Interestingly, if I wrap it in `viewport` instead of `clickable`, clicks are reported correctly.
Judging from the source, there's a filler image created with `availWidth`/`availHeight` dimensions in `viewport`, but `clickable` just takes initial rendered image size.

Though, I don't need viewport functionality for the described widget, so it would be preferable to get away with `clickable` for it.

**Comment by jtdaugherty** [comment]
The behavior you observed is expected. If you want the desired result without a viewport, you can just add a box and a fill and wrap that with `clickable`:
```
clickable $ vLimit 1 $ (str prompt) <+> (fill ' ')
```

**Comment by goodsoft** [comment]
Well, `vLimit 1` is not acceptable, because the widget can grow in height with user input, but I get your idea, thanks.

**Comment by jtdaugherty** [comment]
Okay, great. I used the `vLimit` because `fill` will expand vertically; if you don't want that behavior, a limit will be necessary, or use `padRight Max` instead, which expands horizontally only, and not vertically.
