### ISSUE TITLE
It's too painful to respond to keyboard events

### ISSUE THREAD

**Issue by diegospd** [jtdaugherty/brick#191]
I find it too clumsy to write code for specific keybindings since I have to unwrap the whole event for pattern matching. I would like to have an easier way to declare the keybindings, preferably as a string a la emacs. 
e.g. instead of typing `(VtyEvent (EvKey (KChar 'c') [MCtrl] ))` I would like just to type `"C-c"`

Is there already a way to get around this?

The [EZConfig](https://hackage.haskell.org/package/xmonad-contrib-0.13/docs/XMonad-Util-EZConfig.html#g:3) module for Xmonad implements something like that.

**Comment by jtdaugherty** [comment]
There is not currently a way to do what you want in the core library. We did this very thing on `matterhorn` (https://github.com/matterhorn-chat/matterhorn/blob/master/src/Types/KeyEvents.hs) so it is definitely possible to do without any special help from the core library, and if this were to be developed as a general solution, it would be great as an add-on package like `brick-keybindings`.
