### ISSUE TITLE
Question regarding brick's potential use-cases..

### ISSUE THREAD

**Issue by clojj** [jtdaugherty/brick#192]
Some time ago, you said
"...Brick's editor is really intended to just provide the most basic editing interface to permit user input; more sophisticated editors should probably not be based on it just because the data structures it uses aren't going to be suitable for editing, say, large files or doing syntax highlighting."

Since brick is based on the text-zipper package, I recently just replaced Text by YiString from the yi-rope package. I only had to do some minor adaptations (just handling Yi's Maybe types, nothing fancy) because YiString has mostly the same interface as Text.

My benchmarks (bench package wih adapted Spec-tests from text-zipper) actually showed that text-zipper is 1 order of magnitude faster than using YiString... no matter if small or larger text-content.

So I am wondering, if text-zipper has become faster since, or if I am just using YiString incorrectly (putting it 'inside' the text-zipper instead of using it directly...?) ? (you can't probably answer the latter without ma example or knowing internals of yi-rope... butI wanted to ask anyway)

Regards

**Comment by clojj** [comment]
Ok.. so to be more concrete... do you see editing of typical source code files as an apt usecase ?

**Comment by jtdaugherty** [comment]
I'll also say that nobody has really tried what you're describing as far as I know. So it could turn out to be quite workable. :)

**Comment by jtdaugherty** [comment]
I'm wondering if there was more you wanted to discuss here, or if you had other specific questions. If not, would you mind closing this if you got what you were looking for?

**Comment by clojj** [comment]
sure, thx for the infos!
