### ISSUE TITLE
IO actions in Event-Handlers ?

### ISSUE THREAD

**Issue by clojj** [jtdaugherty/brick#193]
Is there some example, showing the recommended approcah to doing IO in event-handlers (or anywhere else) ?

btw, my base example would be MouseDemo.hs...

**Comment by jtdaugherty** [comment]
At the end of this section:

https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#apphandleevent-handling-events

If you look at the type class instance list for `EventM` at

http://hackage.haskell.org/package/brick-0.41.2/docs/Brick-Types.html#t:EventM

then you'll see `MonadIO` listed there. That means that `IO` can be done in `EventM` by "lifting" the `IO` action with `liftIO` from

http://hackage.haskell.org/package/base-4.11.1.0/docs/Control-Monad-IO-Class.html#t:MonadIO
