### ISSUE TITLE
Performance issues with rendering list items

### ISSUE THREAD

**Issue by romanofski** [jtdaugherty/brick#196]
I've filed a bug against https://github.com/purebred-mua/purebred/issues/208 in regards to sluggish scroll performance with lists and a more ... sophisticated(?) use of the combinators to render the list items. We've mulled over a few ideas, but I thought I might better raise the issue here in case there is actually a better solution for it. At least if there isn't, I guess it's always good to be aware of it and perhaps extend the documentation?

Feel free to close :)

**Comment by jtdaugherty** [comment]
Thank you for letting me know! If you have something specific to report if that gets investigated more, I'll be happy to take a look. I'll close this for now since I left a comment on the other ticket.
