### ISSUE TITLE
Question: alternative Widget for str / txt

### ISSUE THREAD

**Issue by clojj** [jtdaugherty/brick#203]
Hi,

Would it be possible to have a "txtNoPadding" Widget, that would produce a vty Image like so ?
![grafik](https://user-images.githubusercontent.com/4367963/49526123-7888da00-f8af-11e8-9d2f-d6aa855fd200.png)

As I see it, the only 'context' in which txt or str can be used is hBox / vBox (...?)
In the screenshot, the actual Image should be the **inner** boxes..together.

Would it then be possible, to just let several "txtNoPadding" widgets flow one after another ?

My use-case is, that I have a data structure (with a reference to Data.Text) which I want to render as  `[Widget n]`, thereby using the "\n" as the "vertical layout" automatically.

**Comment by jtdaugherty** [comment]
I'm not quite sure I understand what you want, but as for your last point,
> My use-case is, that I have a data structure (with a reference to Data.Text) which I want to render as [Widget n], thereby using the "\n" as the "vertical layout" automatically.

Both `str` and `txt` already do this. Is that not working for you?

**Comment by jtdaugherty** [comment]
Other comments:

* In general, if you want to make a custom widget that has the behavior you want, it is definitely possible.
* In general, if you already have a function that makes a Vty `Image`, it can be embedded in your Brick UI with the `raw` function from `Brick.Widgets.Core`.

**Comment by clojj** [comment]
> Both `str` and `txt` already do this. Is that not working for you?

these are space-padding the smaller lines.
I need to render the next "txt" immediately after the one before.

**Comment by clojj** [comment]
Maybe I should better explain it this way:
If I do (pseudocode!) `hBox $ [txt "aaaaaaa\n"]` I don't get the Image I want...
it should be like the natural text-flow.

**Comment by jtdaugherty** [comment]
What do you mean by "natural text-flow"?

**Comment by jtdaugherty** [comment]
Can you give some example code and some example output that you'd like it to produce, using code block syntax?

**Comment by clojj** [comment]
good idea..  I will give you a small exaple with the extracted core issue...

**Comment by clojj** [comment]
![src-brick-test](https://user-images.githubusercontent.com/4367963/49541543-599c3f00-f8d3-11e8-8c16-4b9f4ed72888.png)
gives me this
![output-brick-test](https://user-images.githubusercontent.com/4367963/49541545-599c3f00-f8d3-11e8-8fd0-5de5a92e13b7.png)

..what I want is this
![wishedfor](https://user-images.githubusercontent.com/4367963/49541650-b4359b00-f8d3-11e8-978c-62b13bab9d99.png)

**Comment by clojj** [comment]
like so

```
ui :: Widget ()
ui = hBox [withAttr "wog" $ txt "aaa ", withAttr "red" $ txt "111 \n222 \n", withAttr "yob" $ txt "ccc ", txt "ddd "]

```

**Comment by jtdaugherty** [comment]
Then for that you might consider looking at `Brick.Markup`.

**Comment by clojj** [comment]
Oh! absolutely did not see that... wonderful

**Comment by jtdaugherty** [comment]
Yes, please do. That module doesn't get used much, I think, but it might be just right for what you are trying to do.

**Comment by clojj** [comment]
`
  markup $ ("Hello" @@ fg V.blue) <> ", " <> ("world!\n still red?" @@ fg V.red) <> ("...and so on" @@ fg V.blue)
`
![fits](https://user-images.githubusercontent.com/4367963/49543304-290ad400-f8d8-11e8-86c5-ae0b3259e144.png)

Fits the bill perfectly, thanks

**Comment by clojj** [comment]
anything special to know about it, like limitations of some sort ?

**Comment by jtdaugherty** [comment]
Mostly that it's slow, and because it doesn't get much use, the API could probably be better. :)

**Comment by clojj** [comment]
hm.. slow meaning 'vastly slower than hBox $ txt' or just not optimized much (yet) ?

**Comment by jtdaugherty** [comment]
It'll depend on how much processing of the text you're doing. You might consider render-caching the markup if it gets to be too slow, assuming the underlying text doesn't change often.

**Comment by clojj** [comment]
Because I'd like to use this in combination with the Edit widget... in 'real time'... editing and continuously updating the markup

**Comment by clojj** [comment]
> It'll depend on how much processing of the text you're doing. You might consider render-caching the markup if it gets to be too slow, assuming the underlying text doesn't change often.

Ok, that makes sense.. and I did see some caching example somewhere I think .. is that demo about render-caching ?

**Comment by clojj** [comment]
is CacheDemo.hs the correct example for render-caching the markup  ?

**Comment by clojj** [comment]
anyway, that will give me enough options to continue, thx
and I think this issue can be closed !

**Comment by jtdaugherty** [comment]
Yes, `CacheDemo.hs` is demo of render caching. The User Guide covers it, too. Be advised that the `Markup` structure will probably be slow for rendering edited text once the documents get large enough, and a faster and better system should be used at some point. Good luck!
