### ISSUE TITLE
Filebrowser selecting multiple files

### ISSUE THREAD

**Issue by romanofski** [jtdaugherty/brick#204]
Thank you for the splendid addition to Brick: a file browser. Unfortunately I did realise too late, that I should have actually contributed our file browser upstream instead of hacking it into Purebred. My bad.

Eager to deprecate our implementation, I've realised that the file browser in Brick can only select a single file. For an application like Purebred in which it is not uncommon to select multiple files I wonder if you're interested in perhaps changing the current implementation to allow multiple file selections? If the current API shouldn't change and you have a different idea I'm all ears.

Cheers for considering :)

**Comment by jtdaugherty** [comment]
Done!

**Comment by jtdaugherty** [comment]
This is now released in `0.43`.
