### ISSUE TITLE
Add instance IsString (Widget n)?

### ISSUE THREAD

**Issue by bawolk** [jtdaugherty/brick#214]
I added the orphan instance
`instance IsString (Widget n) where
    fromString = str`
to my project and was able to type "This is a label" instead of `str "This is a label"`
throughout my project.  Why not add this to Brick?  Brick already overloads string literals to create attrName.

**Comment by jtdaugherty** [comment]
Incidentally I'm not entirely happy about my choice to add `IsString` for `AttrName`, and that same feeling extends to this. While `IsString` is definitely convenient, in my view being explicit about this is better in this case, especially when a `Text` value could be used instead with `txt`.

Thanks for asking!
