### ISSUE TITLE
joinBorders causes performance problems

### ISSUE THREAD

**Issue by mpickering** [jtdaugherty/brick#217]
I'm not sure there is really very much that can be done about this but my application was performing quite slowly due to a single call to `joinBorders`. Feel free to just close this issue but I felt the need to make it in case someone else encountered bad performance and wanted something to try. 

Here is how it looks with `joinBorders`.

<img width="753" alt="screen shot 2018-12-23 at 18 44 48" src="https://user-images.githubusercontent.com/1216657/50386655-3e0ea200-06e3-11e9-9de2-3ffafb0927ea.png">

Here is without the call to `joinBorders`, it is much faster.

<img width="750" alt="screen shot 2018-12-23 at 18 45 53" src="https://user-images.githubusercontent.com/1216657/50386656-3ea73880-06e3-11e9-856a-c19e9202d0ec.png">

**Comment by jtdaugherty** [comment]
I would definitely expect `joinBorders` to have a cost, although I don't think its impact has been measured for more complex interfaces with border elements. Do you have a rough idea of the difference in redraw cost in your case?

**Comment by jtdaugherty** [comment]
Also, is this a case where you want the visual effects of `joinBorders` but at smaller cost, or is the case that you didn't know what `joinBorders` was going to do and consider removing it a solution to the problem? (I can't quite tell from the original report.)

**Comment by mpickering** [comment]
I would prefer the effect of `joinBorders` as I think it looks better but it isn't a huge deal to not have it. 

The difference I would describe as going from unacceptable to acceptable. I'm not sure how to quantify it further than that. 

Adding caching for each of the list elements also makes performance much better after the cache has been populated. Perhaps a way to prepopulate the cache would also be one way to solve this problem.

**Comment by mpickering** [comment]
I realise now it probably wasn't clear from the original ticket. The problem is witnessed because there is a list element in the page which becomes very slow to respond to up/down key presses.

**Comment by mpickering** [comment]
It will be a little bit difficult to extract a minimal example. The whole application is not ready to release yet but I'll post a link once I have either the minimal example or do the release.

**Comment by jtdaugherty** [comment]
Okay, thank you!

**Comment by Ramadas2410** [comment]
deleted

**Comment by jtdaugherty** [comment]
(Ramadas2410 reported.)

**Comment by jtdaugherty** [comment]
@mpickering I'm closing this for now; please re-open if you end up with a demonstration program that exhibits troublesome behavior. Thank you!
