### ISSUE TITLE
What does the `CursorLocation` type mean?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [jtdaugherty/brick#223]
(Motivation: I would like to implement a `FocusTree` type, similar to `FocusRing` in `Brick.Focus`. That means I can't use `focusRingCursor`; I have to implement my own function of some kind that returns a `Maybe (CursorLocation n)`, for `Brick.Main.appChooseCursor` to consume.)

I don't understand what the `CursorLocation` type means.

According to one constructor, it could be an actual 2d coordinate. In this case I assume it indicates a position in the currently focused window, relative to the top-left corner. Is that correct?

The other constructor is a `Maybe Name`. Why would someone want, in response to the question "where is the cursor?", to return one of those? 

(My guess: If the focused window asks where the cursor is, it actually receives a 2d coordinate response. If the window that asks is not focused, but one of its children is, then it receives `Just (name of child)` -- or grandchild, etc. if appropriate. And if the focus is outside of the window that asks, it receives `Nothing`. Is that the idea?)

**Comment by jtdaugherty** [comment]
A bit of terminology: there is only one *constructor* for `CursorLocation`, and that is `CursorLocation`. The constructor has two *fields*: one is `cursorLocation` (type `Location`), and the other is `cursorLocationName`. This is structurally equivalent to another way of writing the type,
```haskell
data CursorLocation n = CursorLocation Location (Maybe n)
```
So this means that a `CursorLocation` has within it both a `Location` and an (optional) resource name `n`.

Does that make sense?

**Comment by JeffreyBenjaminBrown** [comment]
Doh! I saw a sum where there was a product, because the Brick.Types page on Stackage says "Constructors" even though there's only one. This makes perfect sense. Thanks!

**Comment by jtdaugherty** [comment]
Okay, great. I'm glad it's cleared up. :)
