### ISSUE TITLE
Is there a way to ask for the top-left coordinates of a Widget?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [jtdaugherty/brick#224]
I'm experimenting with [cursoring aroudn a tree of windows in Brick](https://github.com/JeffreyBenjaminBrown/rslt-haskell/blob/scroll-nest/src/ScrollNest/Zipper.hs). I would need a FocusTree instead of a `FocusRing`. Rather than do that, I've been just skipping the convenience functions like `withFocusRing`.

The app almost works, but it always thinks the cursor is on the first line. That's because my `appChooseCursor` function returns a `CursorLocation` consisting of the name (in my code names are called `Path`s) of the widget and the cursor's location relative to the top-left corner of that widget.

Brick appears to need that cursor location to be reported in absolute terms, not relative ones. (Which makes me wonder why `cursorLocationName` is one of the fields in `CursorLocation`; maybe I misunderstand.) Anyway, for that I need to know the coordinates of the top-left corner of the currently focused widget. Is there a way to get that?

```
-- | Broken. Lifted with little understanding from Bricks.Widgets.Edit.
appChooseCursor ::
  St -> [B.CursorLocation Path] -> Maybe (B.CursorLocation Path)
appChooseCursor st _ = let
  e = st ^. windows . zLabel . windowEd
  z = e ^. B.editContentsL
  cp = TextZ.cursorPosition z
  toLeft = TextZ.take (cp ^. _2) (TextZ.currentLine z)
  (cursorLoc :: B.Location) = B.Location (textWidth toLeft, cp^._1)
  (n :: Path) = getName e
  in Just $ B.CursorLocation cursorLoc $ Just n
```

**Comment by jtdaugherty** [comment]
There's a lot in this ticket that I'm not sure how to respond to, but I can at least respond to the title: the way to get the coordinates of a part of the UI is to use [reportExtent](http://hackage.haskell.org/package/brick-0.46/docs/Brick-Widgets-Core.html#v:reportExtent) (also [mentioned in the user guide](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#id27)).

**Comment by JeffreyBenjaminBrown** [comment]
Sweet, thanks!

Sorry for writing a messy question. I guess disregard most of it, please :) But one mystery still nags me: Is the `CursorLocation` returned by an `appChooseCursor` function supposed to be relative to the `Widget` containing the cursor, or should it be absolute?

**Comment by jtdaugherty** [comment]
The cursor location returned by `appChooseCursor` is in global (absolute) coordinates.

**Comment by JeffreyBenjaminBrown** [comment]
Fantastic. Thanks!
