### ISSUE TITLE
Query the visible region of a viewport

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [jtdaugherty/brick#225]
Is it possible to find out which line of which sub-widget is at the top or bottom of a scrolled viewport? (Motivations: I'd like to code a shortcut for putting the cursor at the top or bottom of the viewport. I'd also like to display an ellipsis on either side of the viewport if there are more contents out of view on that side.)

**Comment by jtdaugherty** [comment]
This is a tricky situation. The short answer is that this isn't really possible if you actually use `viewport`. The only way to do what you want is to *not* use `viewport` at all and to use a custom widget that draws what it wants (and then it can determine that it ran out of room before drawing the rest of its contents and then draw the ellipsis). I had to do this in [matterhorn](https://github.com/matterhorn-chat/matterhorn). The consequence of this is that you essentially lose the stateful functionality that `viewport` gives you, which may or may not be a problem.

**Comment by jtdaugherty** [comment]
Did my response prove helpful? Please let me know what else I can help with (or close this if you have what you need). Thanks!

**Comment by JeffreyBenjaminBrown** [comment]
Helpful, yes, thanks! I'll just leave those features out of this version of my project, and wait until someone is clamoring for it.
