### ISSUE TITLE
Extent reporting wrong widget?

### ISSUE THREAD

**Issue by mnn** [jtdaugherty/brick#227]
I have a list box on left and thumbnail on the right. However it doesn't matter where I put the `reportExtent`, it always returns the list box.

![Screenshot_20190502_203434_PIX](https://user-images.githubusercontent.com/1975567/57098533-9e10f700-6d1a-11e9-894d-930407a7a7e5.png)

```hs
imageWidget :: String -> T.Widget WName
imageWidget path =
  T.Widget T.Greedy T.Greedy $ do
    ctx <- T.getContext
    let maxHeight = ctx ^. T.availHeightL
    let maxWidth = ctx ^. T.availWidthL
    T.render $ str path <=> (vLimit (maxHeight - 1) $ hLimit maxWidth $ str "xx\nyy")

drawUI :: St -> [T.Widget WName]
drawUI st = [ui]
  where
    list = st ^. videoList
    curIdxMay = list ^. L.listSelectedL
    cur = curIdxMay <&> \idx -> list ^. listElementsL ^?! element idx
    listBox = hLimitPercent 25 $ L.renderList listDrawElement True list
    detailStr = cur <&> formatVideo & fromMaybe "No video selected." & strWrap
    thumbPath = cur <&> (^. thumbnail)
    thumb = padLeftRight 3 $ padTopBottom 1 $ imageWidget (show thumbPath)
    detailBox = reportExtent ImagePreview thumb <=> C.hCenter detailStr
    ui =
      withBorderStyle unicode $
      joinBorders $ B.borderWithLabel (str "YouTube Check by monnef") $ listBox <+> B.vBorder <+> detailBox

```

I tried moving reporting onto imageWidget and detailBox, no change, it still reports listBox. Those `#` symbols are from external program run in event handler which only draws a rectangle on given postion of given size. I am also printing Extent and you can see "upper left" and "offset" are very low. I expected at least one giving me an absolute position of a widget on screen.

Am I using it incorrectly or is it a bug?

**Comment by jtdaugherty** [comment]
Thanks for the report!

Would you be willing to put together an example and screenshot without the obscured contents? I'm having a hard time seeing the UI's relationship to the code with the current example.

**Comment by mnn** [comment]
Oh, didn't think about that. Here's a layout pic:

![Selection_061](https://user-images.githubusercontent.com/1975567/57101758-2e066f00-6d22-11e9-9148-a6d7142c5da6.png)

Code is available here: https://gitlab.com/monnef/yt-check/blob/tui/app/YTC/TerminalUI.hs (`tui` branch; it's not very complex, mainly based on the list example). It needs YouTube API key and a channel ID filled in config if you want to run it (copy/rename `yt-check.sample.json` to `yt-check.json`).

**Comment by jtdaugherty** [comment]
Thanks! The reason you're seeing this behavior is because you're re-using the same resource name (`ImagePreview`) for both the reported extent as well as the list itself. The construction of the list in `
`terminalUI` uses the same value that `reportExtent` is given.

**Comment by mnn** [comment]
Damn, such a silly mistake, I feel stupid now :sweat_smile:. Sorry and thank you for helping me :slightly_smiling_face:.

**Comment by jtdaugherty** [comment]
It's no problem at all. I'm glad it wasn't a bug in the library. You're welcome!
