### ISSUE TITLE
Check `rtsSupportsBoundThreads` on startup

### ISSUE THREAD

**Issue by mpickering** [jtdaugherty/brick#242]
`brick` requires `-threaded` to work correctly. I believe you can consult `rtsSupportsBoundThreads` at runtime to check whether `-threaded` is enabled and issue a good warning about needing to compile with `-threaded`.

**Comment by jtdaugherty** [comment]
Doesn't the RTS already issue such a warning?

**Comment by mpickering** [comment]
Sorry for the noise. I grepped the wrong repo it seems.

**Comment by jtdaugherty** [comment]
No problem. Brick doesn't currently issue any warning for this explicitly, but I just have a memory of other applications I've worked on spitting out a warning about use of threads in the absence of the threaded RTS. That might not be the case anymore, or maybe the apps I was working on used libraries that did this on their own - I'm not sure. But if the RTS doesn't take care of this, I'd be happy to consider something in brick.
