### ISSUE TITLE
[Question] Fixed-sized widget?

### ISSUE THREAD

**Issue by Javran** [jtdaugherty/brick#244]
I've been playing with brick for few days but I couldn't figure this out, and for some reason my post to brick-users google group never show up, therefore I'm opening this issue to see if there's something I missed.

In short I want to have a centered grid (say 8x8) of fixed sized widgets with borders between them, what I come up with is:

```haskell
import Brick
import Brick.Widgets.Center
import Brick.Widgets.Border
import Data.List

vhLimit :: Int -> Int -> Widget a -> Widget a
vhLimit v h = vLimit v . hLimit h

ui :: Int -> Int -> Widget ()
ui v h = joinBorders $ center $ border $ vhLimit (v*8+7) (h*8+7) grid
  where
    grid = center $ vBox (intersperse hBorder (replicate 8 row))
    row = center $ hBox (intersperse vBorder (replicate 8 cell))
    cell = vhLimit v h $ str "#"
```

While `ui 1 1` is exactly what I want: 
![2019-09-14_153632_3840x1080_scrot](https://user-images.githubusercontent.com/1096354/64914406-7d639f80-d705-11e9-894e-7cb551aa934c.jpg)

However I start to get funny results on horizontal direction:
`ui 3 3` looks like this: 
![2019-09-14_154217_3840x1080_scrot](https://user-images.githubusercontent.com/1096354/64914427-4b9f0880-d706-11e9-95b9-4f9df724621b.jpg)
While vertical spaces are indeed evenly distributed, leftmost and rightmost cell in horizontal direction seems to take all rest of the space, which I don't know how to fix except to pad the content myself (below is result by changing to `cell = vhLimit v h $ str " # \n #  \n # "`):

![2019-09-14_154605_3840x1080_scrot](https://user-images.githubusercontent.com/1096354/64914451-d08a2200-d706-11e9-8c48-b252e6fb604f.jpg)

But I don't feel this is intended usage - my question is how to make a widget of some specific width and height regardless of its content?

**Comment by jtdaugherty** [comment]
> my question is how to make a widget of some specific width and height regardless of its content?

The trick I use to do this is to combine `hLimit` and/or `vLimit` with `fill`, `pad`, `center`, or other combinators that make things take up space.

For example, if I wanted a string `foo` to be centered and always take up exactly 10 columns and 5 rows, then I'd do
```haskell
hLimit 10 $ vLimit 5 $ center $ txt "foo"
```
Does that help? The way I think of it is "make the thing take up infinite space, then limit that to the size you want."

**Comment by Javran** [comment]
Yup, that solves the problem - I thought about doing something with padding but never realized  `center` can do just that, thanks!

**Comment by jtdaugherty** [comment]
Great, you're welcome!
