### ISSUE TITLE
TranslateBy and Layers on Widgets

### ISSUE THREAD

**Issue by juakacc** [jtdaugherty/brick#245]
Brick is fantastic, I'm using it for a university graduation project, link, I'm having trouble working with translateBy and Layers, is it possible to work relatively? in relation to just a specific widget, or is it only allowed in the drawUI function? I tried to use vBox and hBox, but they do not work the way I expect, I believe that joining the widgets in the list distorts the translateBy, I wanted for example:
```
translateBy (Location (0,0)) $ resultBox 10 20
translateBy (Location (0,10)) $ resultBox 10 20
```
Inside this widget:
![issue](https://user-images.githubusercontent.com/16393190/65342888-0f5a2500-dbaa-11e9-9930-0cbe4e73ed77.png)

Thank very much

**Comment by jtdaugherty** [comment]
I'm glad you are enjoying using Brick!

`translateBy` is intended to be used only with top-level layers, not inside of widgets, so putting the result of `translateBy` inside a box will not get very nice results, just like you are seeing.

However, if you want to translate a top-level layer using information about the position of a widget in another layer, you may be able to get what you want to by:

* Having the renderer track the `Extent` of the desired widget using `Brick.Widgets.Core. reportExtent`
* Storing the `Extent` in your application state when events get handled using `Brick.Main.lookupExtent`
* Using the stored `Extent` to build your call to `translateBy` at drawing time

For information on extents, see [this section of the User Guide](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#extents).

**Comment by juakacc** [comment]
Thank very much my friend
