### ISSUE TITLE
Loosen version bounds for base on Hackage

### ISSUE THREAD

**Issue by martijnbastiaan** [jtdaugherty/brick#248]
Commit https://github.com/jtdaugherty/brick/commit/baa1630bc6b084e767c36fecd9815c43b22b0f4d loosened the version bounds of `base` to include the one shipped with GHC 8.8. This hasn't been changed on Hackage yet, leaving the package unbuildable on 8.8. Could this be changed? :) I believe package maintainers can do that [over here](https://hackage.haskell.org/package/brick/maintain).

**Comment by jtdaugherty** [comment]
Done, for the most recent three versions. Let me know if there's another version you need to use that doesn't specify that bound. Thanks!
