### ISSUE TITLE
ansi escape codes don't work

### ISSUE THREAD

**Issue by mitchellwrosen** [jtdaugherty/brick#25]
```haskell
import Brick
import System.Console.ANSI -- ansi-terminal

main = simpleMain (str (setSGRCode [SetColor Foreground Dull Red] ++ "hi"))
```

For some reason, this displays `...` instead of a red `hi`

**Comment by jtdaugherty** [comment]
I wouldn't expect this to work; `vty` manages the terminal state so trying to emit your own escapes is likely going to wreak havoc.  Have you considered using `vty`'s functions for this?

**Comment by mitchellwrosen** [comment]
Oh - I didn't notice `Brick.Markdown`. Thanks, closing the issue.

**Comment by jtdaugherty** [comment]
Also take a look at the functions in the "Attribute mangement" section of the Haddock documentation for `Brick.Widgets.Core`.  You could use the markup module but that interface is experimental (read: try it and give me feedback so I can find out if it's useful); the functions in the `Core` module are more stable.  (And if you really need to, you can always resort to doing "raw" Vty operations and constructing `vty` image values yourself and lifting them into `brick` with the `Brick.Widgets.Core.raw` function.)
