### ISSUE TITLE
Vi keybindings for FileBrowser

### ISSUE THREAD

**Issue by Yvee1** [jtdaugherty/brick#259]
Hello,

I like the `handleListEventVi` function for list widgets, is it an idea to add a similar function for the file browser? I had a quick look but I don't see an easy way of doing this at the application level using the existing `handleListEventVi` function, since the internal list is not accessible. Thus, adding this as an option to the library would be nice. A function `handleFileBrowserEventVi` would do the trick I think.

What do you think?

**Comment by jtdaugherty** [comment]
Since I want to avoid a proliferation of event handling functions and would instead want the API to be more user-extensible, I would rather see if we can expose more file browser functionality to make this possible. (The vi-style handler for list is there but I added it only grudgingly. I would prefer to just make it possible for users to implement their own handlers.)

Can you enumerate the list of operations you would want to support so I can add functions for them? So far I could imagine bindings (and new functions) like:
* `j` - `fileBrowserMoveCursorDown`
* `k` - `fileBrowserMoveCursorUp`
* `G` - `fileBrowserMoveCursorEnd`

Are there other sorts of operations you'd like to be able to support?

**Comment by Yvee1** [comment]
I agree that that's a better way to go. Mirroring he list functions would make most sense to me, so having
- fileBrowserMoveUp
- fileBrowserMoveByPages

etc.

**Comment by Yvee1** [comment]
I'm not sure about the implementation details, but maybe making the internal list accessible would be an option? Then the duplication of all these functions would not be needed

**Comment by jtdaugherty** [comment]
I'd rather not expose the list. Instead I'd rather expose new functions (which I am happy to write) to provide access to the abstract functionality that you'd need. I might even already have those functions, just not exported - and if not, any new functions I wrote for this ticket would just get used by the library internals, so there would be no duplication.

**Comment by Yvee1** [comment]
That makes sense, preserving the divide between the implementation details and the interface.

**Comment by jtdaugherty** [comment]
> fileBrowserMoveUp
> fileBrowserMoveByPages
> etc.

**Comment by Yvee1** [comment]
These are the ones I personally want:
- fileBrowserMoveDown
- fileBrowserMoveUp
- fileBrowserStart
- fileBrowserEnd

**Comment by Yvee1** [comment]
Though `fileBrowserMoveToElement` would also be good to have I think. And also kindof makes fileBrowserStart redundant

**Comment by Yvee1** [comment]
> For page movement, that's going to be possible only if the page size is known, and it won't in general be knowable. So instead of that one, `fileBrowserMoveBy :: Int -> ...` would be possible instead.
How is this currently implemented then? The PgUp and PgDn keys seem to work for me, or is only fractional page movement impossible?

**Comment by jtdaugherty** [comment]
It's implemented using a Brick `List`, which I forgot. The list supports pagination so the `FileBrowser` can, too.

**Comment by Yvee1** [comment]
Okay, well then I think that for every `listMove...` there should be a `fileBrowserMove...` function. Furthermore, I think `fileBrowserMoveToEnd` should also be added since the number of elements in the file browser can't be accessed (I think). Following from this, a `fileBrowserMoveToStart` would be logical, and it may also be nice to have these functions for the `List` too to make the API consistent.

**Comment by jtdaugherty** [comment]
Let's maybe go about this a different way. If I could just add some vi-style bindings to the current handler, what would they be? `j`/`k`/`C-f`/`C-b`?

**Comment by Yvee1** [comment]
- k = up
- j = down
- Ctrl-b = page up
- Ctrl-f = page down
- g = first element
- G = last element
- Ctrl-u = half page up
- Ctrl-d = half page down

But the last two are less important in my opinion, I wouldn't use them probably

**Comment by jtdaugherty** [comment]
Thanks! I just pushed a patch to add those. Give that a try!

**Comment by Yvee1** [comment]
Thank you!

**Comment by jtdaugherty** [comment]
If you are going to try out that branch, let me know and close this ticket if it meets your needs (or let me know how it doesn't). If you aren't planning on trying it out before I release it, let me know and we can close this ticket if you think that's enough. Thanks!

**Comment by Yvee1** [comment]
I probably won't try it out, but this does suit my needs and fixes this particular issue. I don't think this is the best solution to the problem because as you already mentioned yourself, it's nicer to make the API more user-extensible. But this is a different problem and would be best treated in a separate issue. Thanks again

**Comment by jtdaugherty** [comment]
The changes discussed here are now released in `0.52`.
