### ISSUE TITLE
Leak in Brick?

### ISSUE THREAD

**Issue by ksaric** [jtdaugherty/brick#260]
Working on https://github.com/input-output-hk/cardano-node we used Brick to draw the terminal UI (TUI) with some information regarding the node behavior. 

![tui](https://user-images.githubusercontent.com/6264437/73824086-d689b800-47f9-11ea-9c2a-700debdd9000.png)

It works really nice and there were no real issues with it until we went into a leak hunt.
The current conclusion is that there is a small leak in the Brick library (around 6.5 MB/day in our case). The actual module responsible for this is https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Node/TUI/LiveView.hs
No, I did not write that.

![cardano-node-long-run](https://user-images.githubusercontent.com/6264437/73824107-e0abb680-47f9-11ea-8b9f-471018b5373a.png)

After trying out several things, I found that displaying the cost centers using `-hc` resulted in a nice graph that can show the culprit.

![visualization-brick-leak](https://user-images.githubusercontent.com/6264437/73824285-2b2d3300-47fa-11ea-82b6-6d0d3287e92e.png)

My own conclusion is that the leak comes from https://github.com/jtdaugherty/brick/blob/758d8138301ce521214247bd9190abbff7ec0f3d/src/Brick/Main.hs#L177-L200, specifically from `runInner` where the state is involved (yay, state).

I would also like to mention that the state we use is currently evaluated to NF and checked if in NF, so there would be no reason why the state we use for Brick would leak there.

In any case, my finding point that there is a small leak in the Brick library, but the leak is rather small, and we will not pursue any further leak hunting (for now). The next steps would be running the more involved examples with profiling turned on and watching for small leaks there.
Not sure if this is useful, but we considered opening up an issue might be helpful.

**Comment by jtdaugherty** [comment]
Yes, that’s very helpful. Thank you for the detailed report!

**Comment by jtdaugherty** [comment]
I got around to looking at this. It turned out that some fields of `RenderState` were not strict, and that was leading to a very small leak. That's now fixed. Thanks again for this detailed report!

**Comment by jtdaugherty** [comment]
The fix is now released in `0.57.1`.
