### ISSUE TITLE
Text wrapping widgets do not behave entirely greedy

### ISSUE THREAD

**Issue by Garmelon** [jtdaugherty/brick#263]
A while ago, this commit (926d317c46b19d4e576748891a1702080287aa03) was made to fix the behaviour of `txtWrapWith` to use all the available horizontal space since it is greedy horizontally (see also issue #234). But it doesn't seem to add the padding when it consists of only a single line.

Example test program and screenshot:
```haskell
import Brick
import Brick.Widgets.Border

line :: Char -> Widget ()
line = vLimit 1 . fill

widget :: Widget ()
widget = vBox
  [ border (line 'a') <+> border (line 'b')
  , border (strWrap "multiple lines\nare padded") <+> border (line 'b')
  , border (strWrap "single line is not padded") <+> border (line 'b')
  ]

main :: IO ()
main = simpleMain widget
```

![image](https://user-images.githubusercontent.com/11077553/75454577-8c65a380-596d-11ea-921f-a8d81edbb144.png)

This was tested with version 0.52.

**Comment by jtdaugherty** [comment]
Thank you for your report! This is now fixed. I overlooked the single-line case. Please close once you are satisfied that this has been addressed.

**Comment by jtdaugherty** [comment]
(Also, thank you for digging up the relevant links; that made this much easier for me to get reacquainted with.)

**Comment by Garmelon** [comment]
Shouldn't the padding also be applied if the widget has no lines (`strWrap ""`)?

**Comment by jtdaugherty** [comment]
As far as `strWrap ""`, I'd have to think about that. I can see it both ways. The problem with padding in the empty string case is that it depends on the caller's intention. Padding an empty string requires choosing a height; an empty string has no height, and assuming a height of a single row might not be right from the caller's perspective. This is another area where "greedy" has two meanings that sometimes shouldn't be conflated: "use all available space" is one meaning (thus the padding) and "please take priority in assigning space in box layouts" is the other meaning (realized in the implementation of `hBox` and `vBox`). The latter meaning doesn't necessarily require the former and in some cases it can lead to annoying situations when they have to get conflated.

As far as upgrading, yes, it's true - the old behavior, while inconsistent with the "greedy" convention and behavior I had implemented elsewhere, was probably going to be relied upon. Unfortunately correcting that may break some layouts, but hopefully it breaks them in ways that lead to fixes that simplify the layout programming required!

**Comment by Garmelon** [comment]
I didn't know a non-zero height was required in order to specify a width. If that is the case, you probably can't have anything with a width of zero and a non-zero height either. I can see how `strWrap ""` and `str ""` having a width and height of 0 make sense.

Sadly, the behaviour change made the old layout far more difficult to reproduce. Here is a screenshot of the old and the new layout:
![image](https://user-images.githubusercontent.com/11077553/75554627-9d2c1d00-5a32-11ea-9963-1a08eb282c9c.png)
![image](https://user-images.githubusercontent.com/11077553/75554259-e0d25700-5a31-11ea-9fe5-45eec48f06f7.png)
Reproducing the new layout using the old `txtWrap` behaviour is easy: I can simply wrap it in a `padRight Max`. I don't know if reproducing the old layout using the new `txtWrap` behaviour is possible or if you'd have to write a custom widget rendering function.

**Comment by jtdaugherty** [comment]
Now I'm a little bit confused, because it seems that the fix you requested broke your layout desire. I think the new behavior is correct (or at least consistent), and I think that really does mean that the layout you want isn't going to be easy to achieve unless you constrain the width of the text wrapping area for each of your tree nodes above.

**Comment by Garmelon** [comment]
I opened this issue because the behaviour of `txtWrap` was inconsistent (different behaviour for single-line and multi-line strings).

I posted the screenshots to show why I preferred the old behaviour (one reason being that the new behaviour is easy to emulate using the old behaviour, but not the other way around), but the new behaviour conforms to the docstring of `Greedy`. That's why I closed the issue.

If I really wanted, I could just manually implement the old behaviour using the old source code from before 0.52. Alternatively, you could maybe include a variant of `txtWrapWith` (called `txtWrapWith'` or something like that) with the old behaviour in the library with a warning that it is greedy horizontally, but doesn't grow to fill the space it is given (and maybe the invariant that
```haskell
txtWrap == padRight Max . txtWrap'
```).

**Comment by jtdaugherty** [comment]
> I posted the screenshots to show why I preferred the old behaviour

Ah, I see. That wasn't clear to me (and in fact, I was confused and I then assumed that the report of the problem took precedence over preferring the old behavior).

> I'd say it is correct now, and I should probably not have relied on its behaviour before. That's why I closed the issue.

Okay, thanks for clarifying!

> Alternatively, you could maybe include a variant of txtWrapWith (called txtWrapWith' or something like that) with the old behaviour and include a warning that it is greedy horizontally, but doesn't grow to fill the space it is given.

I'd like to avoid that and instead try to think about what you want to accomplish, and whether there is another way within the design framework of the library to accomplish it, rather than include something that explicitly takes exception to the (intended) standard behavior.

You could definitely re-use the old implementation; that sort of thing is partly why custom widget implementations are supported, so you can get exactly the behavior you want (and break the rules when you see fit).

Thank you again for your report, your patience, and your screenshots!
