### ISSUE TITLE
contributing to brick:

### ISSUE THREAD

**Issue by zeta-00** [jtdaugherty/brick#266]
hello there, this project looks very interesting, and i would like to maybe contribute to it, would you like to discuss this with me sometime? we could talk about this here, or i'm always on irc freenode, so we could discuss this there as well, let me know, thanks

**Comment by jtdaugherty** [comment]
I'd be happy to discuss it with you. For me, e-mail works best; would that way of communicating work for you?

**Comment by zeta-00** [comment]
@jtdaugherty  , ok sounds good, communicating through email will work for me, my email is: tomas_jose_gallegos@protonmail.com

**Comment by jtdaugherty** [comment]
Okay, I sent you a message. I'm closing this and we can discuss there. Thanks!
