### ISSUE TITLE
Why does brick not support ghc-8.10.x?

### ISSUE THREAD

**Issue by peti** [jtdaugherty/brick#278]
The latest release still excludes `base-4.14.x`, which makes the package unbuildable with ghc-8.10.x. Is that intentional?

**Comment by jtdaugherty** [comment]
Not really. Just a little while ago I merged a PR to support other 8.10 releases, though!

**Comment by peti** [comment]
The fix does not appear to be on Hackage though?

**Comment by jtdaugherty** [comment]
I've just updated the metadata for `0.55` to incorporate the new constraint.
