### ISSUE TITLE
ProgressBar - Special case for values almost equal to 1.00 (but less than 1.00)?

### ISSUE THREAD

**Issue by saurabhnanda** [jtdaugherty/brick#281]
Should there be a special case in `progressBar` which ensures that the `leftPart` is one less than the available width if the progress is less than `1.00`? Otherwise it gives a false impression of completion even though you are _almost_ there.

**Comment by jtdaugherty** [comment]
Thanks! I agree with this and also similarly with values approaching zero. I've just pushed a fix for these cases to `master`.
