### ISSUE TITLE
recommended method for marquee text

### ISSUE THREAD

**Issue by emekoi** [jtdaugherty/brick#283]
i was wondering what the best way to create text that scrolls and wraps like [this](https://www.html.am/html-codes/marquees/html-scrolling-text.cfm).

**Comment by jtdaugherty** [comment]
Can you be more specific about the help you are looking for? Are you needing assistance with using the library?

**Comment by emekoi** [comment]
Sorry for the unclear question. I wanted to know if there was built-in functionally for automatic horizontal scrolling of text when it's larger than some given width. But I managed to come up with a solution on my own by padding and splicing the text myself.

**Comment by jtdaugherty** [comment]
Okay, thanks for your clarification. You're right that there is not a built-in way to do what you want; you'll have to program it yourself, although it should be possible to do. If you have questions about the library, feel free to email me or create a new ticket!
