### ISSUE TITLE
Determine available width/height in event handler?

### ISSUE THREAD

**Issue by emilaxelsson** [jtdaugherty/brick#287]
Is there any way to do what the title says?

I was able to do it in the following way:

  * Create a background widget that fills the available area
  * Use `reportExtent` on that widget
  * Use `lookupExtent` to access the size in the event handler

But that feels like a going across the river for water (as we'd say in Sweden). Is there no way to get the size directly in `EventM`?

Background: I've implemented my own scrolling widget (inspired by #280), and I need the size in order to implement things like page-up/down.

**Comment by jtdaugherty** [comment]
There is a way:
```haskell
import Graphics.Vty (outputIface, displayBounds)
import Brick.Main (getVtyHandle)

someEventMThing = do
    vty <- getVtyHandle
    (width, height) <- liftIO $ displayBounds $ outputIface vty
```

**Comment by emilaxelsson** [comment]
Excellent, thanks!
