### ISSUE TITLE
Is it possible to make a non-Greedy viewport?

### ISSUE THREAD

**Issue by thomasjm** [jtdaugherty/brick#290]
I'd like to make a vertical viewport widget that sizes itself in a `Fixed` way, i.e. if it only has a couple of lines of content in it, then its overall height is only a couple lines. But if it has more content then it grows, up to a certain limit. I'd like to be able to write it like this:

```haskell
growableViewport contents = vLimitPercent 33 $ fixedViewport myName Vertical contents
```

At the moment the greediness of the viewport seems to be baked in. But I saw a proposed implementation in this comment: https://github.com/jtdaugherty/brick/issues/174#issuecomment-385558138. The discussion in that thread said this implementation wasn't fully correct though. Is there a way to write the `fixedViewport` function correctly without a library change? Thanks!

**Comment by jtdaugherty** [comment]
Is there any way you can determine how many rows your viewport's contents are going to need? For example, if you know you have `n` rows' worth of stuff to show in your viewport, you could use that information to impose the appropriate height limit on the `viewport` itself, e.g.,
```haskell
let things :: [Text]
    things = ["one", "two", "three"]
    maxHeight = min 5 $ length things
in vLimit maxHeight $
   viewport myName Vertical $
   vBox $ txt <$> things
```

**Comment by thomasjm** [comment]
Hmm, I don't think I could do that because I want to use `strWrap` on some of the items. It's a good thought though if I were to give up on wrapping.

I think the ideal situation for me would be if a viewport could have its growth policies controlled, just like other widgets.

**Comment by jtdaugherty** [comment]
For what it's worth, no widget can have its growth policy controlled directly. The only way to influence the behavior of something is to wrap it in something else that changes its behavior (like `vLimit`).

It *is* possible to do what you want without changing the library, though. It would just require a little bit of custom widget development:
```haskell
fixedHeightOrViewport :: n -> Int -> Widget n -> Widget n
fixedHeightOrViewport vpName maxHeight w =
    Widget Fixed Fixed $ do
        -- Render the viewport contents in advance
        result <- render w
        -- If the contents will fit in the maximum allowed rows,
        -- just return the content without putting it in a viewport.
        if imageHeight (image result) <= maxHeight
            then return result
            -- Otherwise put the contents (pre-rendered) in a viewport
            -- and limit the height to the maximum allowable height.
            else render (vLimit maxHeight $
                         viewport vpName Vertical $
                         Widget Fixed Fixed $ return result)
```

**Comment by jtdaugherty** [comment]
And if you would prefer that integer argument to represent a percentage, you could get the rendering context (with `getContext`) to determine what `maxHeight` should be by looking at the `availHeight` field of the context.

**Comment by thomasjm** [comment]
Oh, that's great! It goes especially well with the `windowHeightL` thing from my PR when embedding it inside another viewport :).

This solves the problem perfectly and the issue can be closed as far as I'm concerned. FWIW I think it might be nice to include code like this as a helper alongside `viewport` or as an example so it's discoverable. But I'm happy, thanks!
