### ISSUE TITLE
Composability: should Widget be a Functor?

### ISSUE THREAD

**Issue by JEphron** [jtdaugherty/brick#291]
Hanging out in over here in the peanut gallery (enjoyed the few small experiments I've done with Brick), I've been trying to think a bit about composability, with the aim being to come up with some conceptual model for building reusable components. Looking at Matterhorn, it seems like all the names and events are defined centrally in `Types.hs`. I guess that's working out (it's certainly nice to see everything in one place), but from an outsider's perspective it seems like it'd be hard to build abstractions around widgets that need to define their own sets of events and names. Ideally these widgets could exist without knowing anything about one another, and could even be distributed as separate packages. 

There's a pattern in Elm where one module defines it's own `Model`, and `Msg`, and then some other module "embeds" it by wrapping those types and mapping over the values that the child's `update` and `view` produce. 

(paraphrasing from https://github.com/rtfeldman/elm-spa-example/blob/master/src/Main.elm)

```elm
type Model 
    = Home Home.Model
    | Login Login.Model

type Msg
    = GotHomeMsg Home.Msg
    | GotLoginMsg Login.Msg

view : Model -> Html Msg
view model =
    case model of
        Home homeModel ->
            Html.map GotHomeMsg (Home.view homeModel)

        Login loginModel ->
            Html.map GotLoginMsg (Login.view loginModel)
```

This leads to a nice sort of fractal pattern, where parent and child are architecturally similar.

It seems like we can almost do that in Brick, except there isn't a way to go from `Widget a -> Widget b` (and likewise with `EventM`)

Just spitballing an example here, but imagine we had a module like this, representing a component we'd like to use:

```hs
module BrowserTab where

data TabState = ...

data TabName = DomElement ElementId | ContextMenu ...

data TabEvent = Loaded HTML | Failed HTTPError

handleEvent :: State -> BrickEvent TabEvent -> EventM TabName (Next TabState)
...
draw :: State -> Widget [TabName]

```

then you could imagine embedding that component, like:

```hs
module WebBrowser where

import qualified BrowserTab
import qualified UrlBar

data State = {tab: Tab.TabState, ...}

data Event = TabEvent BrowserTab.Event | UrlBarEvent UrlBar.Event | ...

data Name = TabName BrowserTab.Name | UrlBar UrlBar.Name | BackButton | FwdButton ...

handleEvent :: State -> BrickEvent Event -> EventM Name (Next State)
handleEvent s ev = do 
    case (getFocus s, ev) of 
        (Tab tabName, AppEvent (TabEvent e)) ->  
            -- map over EventM: how does this work? 
            handleEventSubcomponent s tabLens $ BrowserTab.handleEvent tabName (AppEvent e)
        ...

draw :: State -> [Widget Name]
draw s = 
    -- fmap over widget here
    [TabName <$> tabWidget | tabWidget <- BrowserTab.draw (s ^. tab)] ++ ...
```

I could be totally off the mark here, but would it make sense to try to support a pattern like that?

**Comment by jtdaugherty** [comment]
> Looking at Matterhorn, it seems like all the names and events are defined centrally in Types.hs. I guess that's working out (it's certainly nice to see everything in one place), but from an outsider's perspective it seems like it'd be hard to build abstractions around widgets that need to define their own sets of events and names.

Yeah, in Matterhorn the things we're building don't need to be provided to other applications as generic abstractions. We abstract as needed in the context of the application, but we don't need to ever change the name or event types.

> Ideally these widgets could exist without knowing anything about one another, and could even be distributed as separate packages.

I agree, and usually it's enough to just make a package that provides things in terms of `n`, e.g. `Widget n`, and then take arguments of type `n` as needed. Libraries providing such extensions should not need to care about the name type.

> It seems like we can almost do that in Brick, except there isn't a way to go from Widget a -> Widget b (and likewise with EventM)

Widgets are drawing state monad computations in terms of a rendering state that uses the name type for a bunch of things. While it *might* be possible to map `Widget a` to `Widget b` just by mapping over the `a`s found in the monad's state, I am not sure that is necessary to support better composability.

I think there are bigger challenges to better composability currently: event handlers need to know about state and event types, and that prevents extensions from providing their own event types. I've thought about ways to address that, and the only idea I've come up with that I think could work is to make it possible to compose at the `App` level where control over the terminal transitions from one `App` to the other (and thus a change in state and event type). While that worked okay in the prototyping I did, it has an issue that is not easily resolved, which is that applications can spawn threads to produce custom events and inject them into the Brick event handling loop. If a "backgrounded" `App` does that, it would not be good for those events to queue up, nor would it necessarily make sense for them to get handled.

**Comment by jtdaugherty** [comment]
@JEphron any thoughts on my commentary above?

**Comment by JEphron** [comment]
Yep, thanks for writing up a thoughtful response. I took a bit of a break from the project I was using Brick for, and ended up getting pretty distracted. Sorry I let this sit so long! 

I'll admit that Brick is my first experience with this kind of declarative UI in Haskell. I've worked on a few (smallish) commercial Elm application in the past, and was pretty excited to find something in the same vein for Haskell TUI. The way we did composition was basically by nesting types, so each page or widget would have its own set of "event handlers" (subscription function), its own update function, and its own views, and corresponding `Model`, and `Msg` types. Then we'd compose them together by mapping the return types of the child into the types of the parent (ie, the parent would wrap the types of the child). This worked reasonably well, although there was a significant amount of boilerplate required to wire everything together. 

In some ways it sounds similar to what you said about composing at the `App` level, although without the added complexity of dealing with backgrounded processes (if we wanted to stop a page from doing stuff we'd just unhook it's `subscription` and stop calling its `update`)

I don't really have much more to offer than that, other than to say that this is a cool project! Feel free to close if you want.

**Comment by jtdaugherty** [comment]
> if we wanted to stop a page from doing stuff we'd just unhook it's subscription and stop calling its update

Yeah, this definitely one way to do it, and I can't (in general) know whether that will work for all applications. It definitely won't work for some scenarios I can think of.

Thanks for your follow-up. I'm glad my response was helpful. I just wanted to revive this in case there was more we needed to discuss. I'm glad you've gotten some value from Brick!
