### ISSUE TITLE
Markup with wrapping

### ISSUE THREAD

**Issue by NorfairKing** [jtdaugherty/brick#293]
Hi @jtdaugherty I'm trying to use markup with user-supplied input for [sparep](https://github.com/NorfairKing/sparep) (for the fill exercises.)

It would be nice if the cards could always have the same width, so I use `hLimit 40`.
But then the markup gets cut-off. Is there any way to have the markup be wrapped?
In the meantime I've removed the `hLimit`.

Thanks again for Brick, I'm loving it!

**Comment by jtdaugherty** [comment]
Ney @NorfairKing - unfortunately the library's markup abstraction is not composable with line-wrapping. You'll need to perform line-wrapping on your data before converting it to markup. If you want to do it on Markup, you'll have to extract the data with `toList`, wrap it, and then call `fromList` on each line. I know it isn't super helpful that markup can't be wrapped, but wrapping behavior tends to depend on a lot of application decisions so the markup abstraction doesn't provide support for it.

**Comment by NorfairKing** [comment]
Alright thanks!
