### ISSUE TITLE
Bump up base bound for GHC 7.10

### ISSUE THREAD

**Issue by FranklinChen** [jtdaugherty/brick#3]
Please bump up base bound to support GHC 7.10.

**Comment by jtdaugherty** [comment]
I'm not running 7.10 and switching would be somewhat costly at the moment, but I would be more than happy to accept a pull request making this change if you can first do a sandbox build to ensure that it succeeds.

**Comment by jtdaugherty** [comment]
And a bonus would be checking that the change does *not* break things on 7.8.3. :)
