### ISSUE TITLE
failed to install brick via Hackage

### ISSUE THREAD

**Issue by greggaree** [jtdaugherty/brick#308]
I tried to install brick using:

```
$ cabal update
$ cabal install brick
```
 
I got the following error:

```
usr/bin/ld.gold: error: cannot find -ltinfo
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
cabal: Failed to build vty-5.32 (which is required by brick-0.60.1). See the
build log above for details.
```

I am using ghc version 8.10.3.

All seemed to be going well until cabal had to build vty-5.32. Here are excerpts from the log:

```
Failed to build vty-5.32.
Build log (
/home/greg/.cabal/logs/ghc-8.10.3/vty-5.32-e8149f76df07cb945b7640d4402df4c99f6fcb1b131bdabcda71e1b03305cdd1.log
):
Configuring library for vty-5.32..
Preprocessing library for vty-5.32..
Building library for vty-5.32..
[ 1 of 40] Compiling Codec.Binary.UTF8.Debug ( src/Codec/Binary/UTF8/Debug.hs, dist/build/Codec/Binary/UTF8/Debug.o, dist/build/Codec/Binary/UTF8/Debug.dyn_o )
```
Later in vty build process:
```
[21 of 40] Compiling Graphics.Vty.Input.Loop ( src/Graphics/Vty/Input/Loop.hs, dist/build/Graphics/Vty/Input/Loop.o, dist/build/Graphics/Vty/Input/Loop.dyn_o )

<no location info>: warning: [-Wmissed-extra-shared-lib]
    libtinfo.so: cannot open shared object file: No such file or directory
    It's OK if you don't want to use symbols from it directly.
    (the package DLL is loaded by the system linker
     which manages dependencies by itself).

src/Graphics/Vty/Input/Loop.hs:227:42: warning: [-Wunused-record-wildcards]
    No variables bound in the record wildcard match are used
      Possible fix: omit the ‘..’
    |
227 |               , termName = Just theTerm, .. } <- readIORef $ _configRef input
    |                                          ^^
[22 of 40] Compiling Graphics.Vty.Input.Terminfo.ANSIVT ( src/Graphics/Vty/Input/Terminfo/ANSIVT.hs, dist/build/Graphics/Vty/Input/Terminfo/ANSIVT.o, dist/build/Graphics/Vty/Input/Terminfo/ANSIVT.dyn_o )
```

At the end of vty build:
```
[40 of 40] Compiling Graphics.Vty.Inline ( src/Graphics/Vty/Inline.hs, dist/build/Graphics/Vty/Inline.o, dist/build/Graphics/Vty/Inline.dyn_o )
/usr/bin/ld.gold: error: cannot find -ltinfo
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
cabal: Failed to build vty-5.32 (which is required by brick-0.60.1). See the
build log above for details.
```

I tried building brick with cabal using ghc 8.8.4, but it also failed while building vty. From the build log:

```
Failed to build vty-5.32.
Build log (
/home/greg/.cabal/logs/ghc-8.8.4/vty-5.32-1982a48172cd723683d4dfda5db184b0214cb24d485ed68ee9822e3277c72e62.log
):
Configuring library for vty-5.32..
Preprocessing library for vty-5.32..
Building library for vty-5.32..
[ 1 of 40] Compiling Codec.Binary.UTF8.Debug ( src/Codec/Binary/UTF8/Debug.hs, dist/build/Codec/Binary/UTF8/Debug.o )
```
Later in the build:
```
[21 of 40] Compiling Graphics.Vty.Input.Loop ( src/Graphics/Vty/Input/Loop.hs, dist/build/Graphics/Vty/Input/Loop.o )

<no location info>: warning: [-Wmissed-extra-shared-lib]
    libtinfo.so: cannot open shared object file: No such file or directory
    It's OK if you don't want to use symbols from it directly.
    (the package DLL is loaded by the system linker
     which manages dependencies by itself).
```
At the end of vty build:
```
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
cabal: Failed to build vty-5.32 (which is required by brick-0.60.1). See the
build log above for details.
```

**Comment by jtdaugherty** [comment]
Thanks for the report! This looks like a `vty` build issue specifically. Which Linux distribution is this occurring on?

**Comment by greggaree** [comment]
Ubuntu Mate 18.04 LTS

**Comment by jtdaugherty** [comment]
Do you have any version of `libtinfo` installed on your system? (If not, you can find out which package provides it by running `sudo apt-get install apt-file && sudo apt-file update && apt-file search libtinfo`).

**Comment by jtdaugherty** [comment]
@glguy - I'm wondering if you have run into this issue. There have been two Vty patches ([here](https://github.com/jtdaugherty/vty/pull/183), [here](https://github.com/jtdaugherty/vty/pull/181)) submitted about this issue, but I got stuck trying to figure out why these would make sense *in vty*. Vty doesn't seem to even have an explicit dependency on `ncurses` or `tinfo`, and judging by my google searches ([example](https://github.com/commercialhaskell/stack/issues/257)), this `tinfo` issue comes up with a ton of Haskell projects on some platforms like Arch and some versions of Ubuntu.

**Comment by greggaree** [comment]
I searched /usr/lib and /usr/bin, but couldn't find libtinfo.  Are there any other directories I should search?

**Comment by jtdaugherty** [comment]
@greggaree I don't think so; it probably just isn't installed. Your best bet is probably to try the commands I posted above and then install whatever package provides `libtinfo`.

**Comment by greggaree** [comment]
I searched the web and found libtinfo-dev. vyt and brick got built and installed. However, I got a warning at the end:

```
$ cabal install brick
Resolving dependencies...
Build profile: -w ghc-8.10.3 -O1
In order, the following will be built (use -v for more details):
 - vty-5.32 (lib) (requires build)
 - brick-0.60.1 (lib) (requires build)
Starting     vty-5.32 (lib)
Building     vty-5.32 (lib)
Installing   vty-5.32 (lib)
Completed    vty-5.32 (lib)
Starting     brick-0.60.1 (lib)
Building     brick-0.60.1 (lib)
Installing   brick-0.60.1 (lib)
Completed    brick-0.60.1 (lib)
Warning: You asked to install executables, but there are no executables in
target: brick. Perhaps you want to use --lib to install libraries instead.
```
Should I have used  --lib?

**Comment by jtdaugherty** [comment]
You can find out more information about why you got that warning [here](https://stackoverflow.com/questions/61488500/cabal-install-tidal-ends-with-warning). If your goal is to install `brick` in order to develop against it, I would recommend making a new Haskell package that depends on it, and then running a sandbox build with `cabal new-build`.

If you just want to try out the demo programs in the library, then I recommend fetching the brick source with `git` and then running `cabal new-build -f demos`; that will compile all the demos in `programs/` and you'll then be able to run them with `cabal new-run -f demos <program name>`.

**Comment by jtdaugherty** [comment]
@greggaree Did you get things working?

**Comment by greggaree** [comment]
Hi Jon,

Thanks for checking back with me. (Hey! Now that's great service!)

Short answer is yes.  I'll give a longer reply in a few days or so...

**Comment by jtdaugherty** [comment]
Okay, great. I'll close this since it's resolved, but I'd love to know what happened.
