### ISSUE TITLE
Support GHC-9.0

### ISSUE THREAD

**Issue by vrom911** [jtdaugherty/brick#316]
Hey @jtdaugherty ,

It would be nice to upgrade `base` (and maybe other) versions to support GHC-9.0.

Thanks a lot!

**Comment by jtdaugherty** [comment]
Hi @vrom911 - brick supports GHC 9.0 as of version 0.58. Are you running into an issue?

**Comment by vrom911** [comment]
Yes, I see that the upper bound for `base` in version `0.60.2` is `<=4.15` on Hackage.
However, when I build summoner, I see the following:

```
[__3] rejecting: brick-0.60.2 (conflict: base==4.15.0.0/installed-4.15.0.0,
brick => base<=4.15)
```

I have added the following line to my `cabal.project` and everything worked:

```haskell
allow-newer: brick:base
```

Seems like `<=4.15` doesn't include `4.15.0.0`. As per PVP, `4.15` is smaller than `4.15.0.0`.
See the following check with the standard function used to check this:

```haskell
$ cabal repl -b Cabal
ghci> import Distribution.Types.Version
ghci> compare (mkVersion [4, 15]) (mkVersion [4, 15, 0, 0]) 
LT
```

I think that this could be an issue..

**Comment by jtdaugherty** [comment]
Ah, that was fixed in the source tree but not on Hackage. I've updated the metadata for all versions starting with 0.58. Let me know if that resolves this for you, and then we can close this.

**Comment by vrom911** [comment]
Fantastic! I see the updates now. Thanks so much for fixing this so quickly 👍🏼

**Comment by jtdaugherty** [comment]
Great, thanks for reporting it!
