### ISSUE TITLE
Could not specialise imported function ‘Brick.Main.customMain1’

### ISSUE THREAD

**Issue by DamienCassou** [jtdaugherty/brick#318]
I get this warning when [compiling my code](https://github.com/DamienCassou/hyahtzee2/runs/2375241943?check_suite_focus=true#step:6:52):

```
app/Main.hs: warning: [-Wall-missed-specialisations]
    Could not specialise imported function ‘Brick.Main.customMain1’
    Probable fix: add INLINABLE pragma on ‘Brick.Main.customMain1’
```

I found some [documentation about INLINABLE pragma](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/pragmas.html#inlinable-pragma) and some [documentation about the compiler flag](https://mpickering.github.io/users_guide/using-warnings.html#index-15).

**Comment by jtdaugherty** [comment]
@DamienCassou out of curiosity, do you have `-Weverything` set? Ordinarily this warning does not appear, even with `-Wall`.

**Comment by DamienCassou** [comment]
> do you have -Weverything set

I indeed do. To hide the warnings I added `-Wno-all-missed-specialisations` and `-Wno-missed-specialisations`. I don't care about the problem reported here, I just wanted to tell you so you know about it and get a chance to fix it.

**Comment by jtdaugherty** [comment]
Okay, thanks! I talked to some GHC developers I know, and the answer I got was that this is not something I am likely able to do much about, especially given that the function in question is from GHC-generated code (`customMain` is a Brick library function, but `customMain1` is not). Thank you for the report, though!
