### ISSUE TITLE
ok to add project to list?

### ISSUE THREAD

**Issue by 2mol** [jtdaugherty/brick#319]
Hi, I just discovered the list of projects in the README.

If you want, you can add https://github.com/2mol/pboy (or I can send you a PR).

I've had a really great time using brick, so thank you very much for the project and the continued maintenance!

**Comment by jtdaugherty** [comment]
Yes, I’d be happy to add it - please open a PR. Thanks! I’m glad you are enjoying using brick!

**Comment by 2mol** [comment]
Super. Here it is: #320 

Closing this already :)
