### ISSUE TITLE
Question: how best to handle lists with separators?

### ISSUE THREAD

**Issue by byorgey** [jtdaugherty/brick#336]
My overall goal is to have a list with occasional separators in it, something like this:
```
Item1
Item2
--- Separator ---
Item3
Item4
```
But I don't want the separators to ever be highlighted and I want them to be skipped over when scrolling through the list.  For example, if `Item2` is highlighted in the above example and the user presses the down arrow key, then `Item3` should be highlighted.

1. At first I just kept track of which list items should have a separator immediately preceding them, and rendered those items with an extra line for a separator (which I forced to use a different attribute).  This seemed to work well, but then I read the warning about all the list items being the same height, and found some of the historical discussions of this warning in the issue tracker, and I now realize this is not a good solution (indeed, I was seeing some strange issues when scrolling near the end of the list).
2. The only other solution I can think of is to have separators represented by special items in the list, but change the way key events are handled to always skip over them.  I think I can see how to do this but it's going to be a bit tedious, as it means copy-pasting and slightly modifying a bunch of functions from `brick` (such as `handleListEvent`, `listMoveBy`, `listMoveByPages`, ...)

I was just wondering whether there is a better way to do this, or if anyone has already done it.

**Comment by byorgey** [comment]
Incidentally, this is for https://github.com/byorgey/swarm/ , which I haven't announced publicly yet, but you're welcome to add it to the list of featured projects if you like!

**Comment by jtdaugherty** [comment]
Howdy, thanks for opening this. I'm glad you found the historical discussions on this - that will save me time! I think your option (2) might actually have legs. I suspect you don't need to copy any code from `brick`, but rather intercept key events and deal with them in your own way prior to (or instead of) forwarding them to the list with `handleListEvent`. For example, if you got a `Down` keypress, you could check to see if you should forward *two* down keypresses to the list or just one, based on the next element in the list after the current selection. Does that make sense? (The same would need to be done for any other movements that you want to support, and that could still be tedious, but perhaps it could be generalized enough to prevent the implementation from being too untidy.)

**Comment by jtdaugherty** [comment]
(Also, that looks like a super cool project and I would be happy to add it to the list whenever you like. Let me know if now's a good time; otherwise I could wait until you consider it stable/released.)

**Comment by jtdaugherty** [comment]
I realized I didn't respond to something else you said, as well: this does come up from time to time, and I've even wanted to do it in one or two of my own applications. I'm sorry I don't have a better story for how to do it. The design of `List` makes the trade-off for drawing efficiency in lieu of item size variability, and that does sometimes create headaches when people want the opposite trade-off.

In [one application](https://github.com/matterhorn-chat/matterhorn) that I maintain, we ditched `List` entirely (when drawing the list of channels in the sidebar) and went with a zipper structure (for other reasons), but the main reasons why we can get away with that at rendering time are that 1) the zipper doesn't don't need to change all that often and 2) we render-cache it.

**Comment by byorgey** [comment]
> For example, if you got a Down keypress, you could check to see if you should forward two down keypresses to the list or just one, based on the next element in the list after the current selection.

Thanks! That does make sense, and sounds easier than what I was thinking.  I was a bit worried about e.g. `PgDown`, since that's not just an issue of sending one or two page down events, but now that I think about it more I can see doing something like sending a page down, then potentially sending another up or down keypress if it happened to land on a separator.

> (Also, that looks like a super cool project and I would be happy to add it to the list whenever you like. Let me know if now's a good time; otherwise I could wait until you consider it stable/released.)

Thanks!  And I must say it has been an absolute joy building the UI for it with `brick`.  You can go ahead and add it now.  I mean, it's in a public repo on GitHub so it's not like I'm trying to prevent people from looking at it.  It could still be a good example for someone wanting to use `brick` for something similar, even in its current state.

I'll close this issue for now, but I'll try to come back later and add a link to whatever I end up with, in case someone has a similar question in the future.

**Comment by jtdaugherty** [comment]
> And I must say it has been an absolute joy building the UI for it with brick.

That's great to hear! And please stay in touch with me with feedback/questions as you use it.

> You can go ahead and add it now. I mean, it's in a public repo on GitHub so it's not like I'm trying to prevent people from looking at it. It could still be a good example for someone wanting to use brick for something similar, even in its current state.

Done: 3227bf91809bdb94b72577fa0ec7a3b997bc046f

**Comment by byorgey** [comment]
> this does come up from time to time, and I've even wanted to do it in one or two of my own applications. I'm sorry I don't have a better story for how to do it. The design of `List` makes the trade-off for drawing efficiency in lieu of item size variability, and that does sometimes create headaches when people want the opposite trade-off.

No worries, makes sense.  If I end up with something general enough I may submit a PR or release it as a separate package.

**Comment by jtdaugherty** [comment]
Sounds good!

**Comment by byorgey** [comment]
You can see what I came up with here: https://github.com/byorgey/swarm/commit/58129bb693808ddb6e2b1053f0c8dc2cf05ddf8b#diff-f6926f63293862711ec1416733173102eb24c0397dc33921510bd9230eaf3940R714-R771

I'm reasonably happy with it for now.  I made a generic "find" operation that searches backward or forward through the list for the next item satisfying a predicate (inspired by `listFindBy`) and used that to make sure we always find something to land on that isn't a separator.

The only remaining issue is that if the very first item in the list is a separator (as it is in my case), then after you scroll it off the top of the viewport, you can't get it back!  Since none of the operations will ever make it the currently selected item, it always stays off the top of the viewport (I assume it would become visible again if the list became short enough for the entire thing to fit in the viewport).  Any suggestions on what to do about this?  I guess what I want is some way to tell `brick` to include that first element in the rendered view even though it's not the currently selected item.

**Comment by jtdaugherty** [comment]
> I assume it would become visible again if the list became short enough for the entire thing to fit in the viewport

Maybe not, because Brick will only "scroll the viewport up" if something that is out of view needs to be brought into view.

> I guess what I want is some way to tell brick to include that first element in the rendered view even though it's not the currently selected item.

As long as you know when to ask for this and when not to (e.g. only when the second element is selected?) then you can just use [`visible`](https://hackage.haskell.org/package/brick-0.64.1/docs/Brick-Widgets-Core.html#v:visible) to wrap the initial separator.

**Comment by byorgey** [comment]
Ah, perfect, I didn't know about `visible`.  Thanks!

**Comment by jtdaugherty** [comment]
You're welcome. You might also consider checking out [`VisibilityDemo.hs`](https://github.com/jtdaugherty/brick/blob/master/programs/VisibilityDemo.hs) for a simple example of how it can be used.
