### ISSUE TITLE
listMoveToEnd uses wrong index?

### ISSUE THREAD

**Issue by byorgey** [jtdaugherty/brick#337]
```
listMoveToEnd l = listMoveTo (length $ listElements l) l
```

Shouldn't that be `length (listElements l) - 1` ?  Normally it doesn't matter since the index gets clamped somehow.  But I am having some strange issues trying to apply a transformation to a list immediately after calling `listMoveToEnd` and I'm wondering if it ends up in a slightly inconsistent state.  I don't know for sure whether this is what's causing my problem but regardless, it seemed worth questioning.

**Comment by byorgey** [comment]
I can confirm that if I replace the call to `listMoveToEnd` in my code with a version that subtracts 1 from the length, then everything seems to work as I expect.

**Comment by jtdaugherty** [comment]
Yes, thanks! Fixed (slightly differently) in f0ceb81ed4220230ec775aea438afab1e61b93ad.
