### ISSUE TITLE
Fix `base` dependency bounds in brick <=0.26

### ISSUE THREAD

**Issue by exaexa** [jtdaugherty/brick#341]
Hello!

Would it be possible to fix the dependency bounds in historical versions of Brick in hackage so that they do not get selected for newer, incompatible GHCs?

In particular, we found the following issue (on ghc-9.0.1, cabal-3.6):
- installing brick with unbounded versions results in cabal picking brick-0.26, which is the last version of brick with base compatibility specified as `base <= 5`
- technically that's a bit of cabal weirdness (why not select the newer version?), but not a bug -- hackage metadata says that the version combination is perfectly valid, and some additional constraints could reasonably guide cabal&user into thinking that brick-0.26 is indeed the best option
- compilation of brick-0.26 (and lower) on base 4.15 fails due to Semigroup/Monoid incompatibility
- compilation on any newer `base` (say `4.latest` + `0.1` :] ) will fail too before brick dependencies get bumped, because 0.26 would be the newest version that would look compatible at that time

Is there anything that could be done with this? We had some discussion on #haskell and it seems that version bounds of the older packages in hackage could be fixed by maintainers.

Please let me know in case this issue should be forwarded/reopened elsewhere.

Thanks!

**Comment by jtdaugherty** [comment]
Thanks for reporting this. I can understand why a metadata update would be helpful. I took a look, and there are over 40 versions of `brick` that would need to be updated. I'm not excited about doing that by hand, so I'm wondering if there's an alternative.

One alternative that comes to mind is for you to specify a lower bound on `brick`; I'd be concerned that if you don't, you'll get different versions of `brick` depending on what GHC you use, and that could be problematic.

Do you know whether there's any way to do bulk updates of package metadata like this?

**Comment by exaexa** [comment]
Hi! Thanks for quick response. Alas, I don't know if there's a quick one-command way to resolve the version problems en masse (I never maintained anything on hackage) but people suggested looking at the hackage build matrix, which for Brick would be this link: https://matrix.hackage.haskell.org/#/package/brick . That could at least provide a complete view of version bounds that should be added.

**Comment by jtdaugherty** [comment]
In the mean time, can you add a brick lower bound? That's going to be important for API compatibility anyway, regardless of GHC version.

**Comment by exaexa** [comment]
Yeah, adding the lower bound fixes it perfectly and I'm actually doing that everywhere. The reason I'm solving this is mostly because of the students, who type something like `cabal pls install brick` and get an error message which, at that point, is completely incomprehensible to them.

**Comment by jtdaugherty** [comment]
Oh, I see. (They could install a specific version that way, too -- also, don't forget about `-fdemos`!)

**Comment by exaexa** [comment]
> Is this for a course?

Yes, "practical haskell" programming course. I'm using Brick&Gloss as switchable alternatives for first/second homeworks. Both are great ways of getting something moving on the screen quickly, and like half of the students actually likes the terminal interfaces better. :]

**Comment by jtdaugherty** [comment]
Awesome! I'm glad to hear it!

**Comment by jtdaugherty** [comment]
All of the `base` bounds on all versions of `brick <= 0.24.2` have been set to `base <= 4.7.0.0`. It turned out to be really easy with the [hackage-cli tool](https://github.com/hackage-trustees/hackage-cli). Once you get a fresh package index, let me know if this helps!

**Comment by exaexa** [comment]
Yeah, looks working perfectly! Thank you very much, issue solved, closing! :]
