### ISSUE TITLE
possible to get viewport's current scroll position ?

### ISSUE THREAD

**Issue by simonmichael** [jtdaugherty/brick#345]
I haven't been able to figure this out even from the excellent docs. 

It looks like I could get it with unsafeLookupViewport, but only in RenderM which I think I could access only within a custom Widget ?

Here's why I think I need this: I'm showing a large List. I'd like the mouse scroll wheel to scroll it up and down. The standard List won't scroll if it would move the selected element out of sight. I need to move the selection to allow the scroll.. but I don't want to do that when the selection is in the middle of the screen - only when it's at the edge.

Any help welcome! Thanks for brick as always!

**Comment by jtdaugherty** [comment]
Hmm, perhaps you want [`lookupViewport`](https://hackage.haskell.org/package/brick-0.64.2/docs/Brick-Main.html#v:lookupViewport). That runs in `EventM` and it gets you the [`Viewport`](https://hackage.haskell.org/package/brick-0.64.2/docs/Brick-Types.html#t:Viewport) for the most recent rendering. The `_vpTop` field of that structure will tell you where the top of the viewport is. So, for example, if `_vpTop` was `5`, that'd mean that the first visible row of the viewport would be the fifth row of the viewport's contents. To tell whether your list selection was "near the top of the viewport" you'd use your list item height times the selection index (plus 1). So, the first row of the viewport that is selected in your list is `(selected_index + 1) * list_item_height`. If that equals (or is close enough to) `_vpTop vp` (or `_vpTop vp + (snd $ _vpSize vp)`) then you'd know whether you could mouse-wheel-scroll your list. Let me know if that helps you get what you're looking for!

**Comment by simonmichael** [comment]
Wonderful, thanks! I failed to find that one.

I was able to make it work in the end, with code like [this](https://github.com/simonmichael/hledger/blob/e0b145a5c8a359feb84e51269691edcb55016fcd/hledger-ui/Hledger/UI/AccountsScreen.hs#L338:L367).

**Comment by jtdaugherty** [comment]
Great!

**Comment by simonmichael** [comment]
Just for the record, [here's](https://github.com/simonmichael/hledger/blob/4d1a3e9cd996c577777b6e72c8f04aa644bbc6fb/hledger-ui/Hledger/UI/UIUtils.hs#L366:L383) a listScrollPushingSelection helper which I think others might find reusable.
