### ISSUE TITLE
debouncing mouse button presses ?

### ISSUE THREAD

**Issue by simonmichael** [jtdaugherty/brick#347]
I seem to see two MouseDown events being received when I click/tap once, about 25% of the time. I'm using the touchpad on a macbook air m1. Have others seen this ? Is there any debouncing done within brick/vty, or should there be ?

[Perhaps it would be enough to discard successive MouseUps or MouseDowns, enforcing strict alternation of one MouseDown, one MouseUp ?]

**Comment by jtdaugherty** [comment]
I don't know of others who have seen that behavior. Vty and Brick don't do anything to the event stream; both of those libraries just translate and forward whatever comes from the terminal emulator.

As far as doing more clever things, it can be tricky to get right in general, so I'd want to be very careful about adding anything to the libraries. For example, two successive clicks on the same location might seem spurious, but depending on the terminal emulator's behavior, you could do something like

* Mouse down at location X
* Move mouse out of the window
* Release mouse button
* Move mouse back to location X
* Mouse down again

These are two legitimately independent clicks, but the terminal emulator will likely not send a Mouse Up event at any point in this sequence and the library will not be able to tell that the mouse left the area in between the two events to consider them independent.

This might not be too messy to handle in the application, where the last-clicked location is recorded and only reset when a mouse-up event is received. I've implemented click-and-drag in `tart` and that got tricky to get right, though, so I'm not sure what the edge cases might be.

**Comment by simonmichael** [comment]
Good point about moving out of window. 

For the record, I'm seeing this in apple Terminal, iTerm3, and VS Code's terminal pane, whether running from GHCI or compiled. It's less often than 25%, but easy to reproduce within a few seconds.

I have never seen MouseUp duplicated, so it seems a cheap workaround will be to act on that instead.

(Debugging was complicated by one of my screens always receiving `VtyEvent (EvMouseDown x y BLeft [])` instead of the usual `MouseDown name BLeft [] location`, I can't for the life of me see why, but this is a separate issue.)

**Comment by jtdaugherty** [comment]
You'll get a `VtyEvent (EvMouseDown ...)` if Brick got a mouse down event but couldn't match it with any known clickable region (as marked with `Brick.Widgets.Core.clickable`). That way you get all mouse events but events in clickable regions get "upgraded" to `MouseDown` from Brick so you get more information about the click.

**Comment by simonmichael** [comment]
Ahhh! Thank you sir!

**Comment by simonmichael** [comment]
>  it seems a cheap workaround will be to act on that instead.

Not quite.. I want to use shift-click, and MouseUp doesn't provide modifiers.

**Comment by jtdaugherty** [comment]
Yeah, you'd have to ignore modifiers to reset on a mouse-up event. (The terminal doesn't give us modifier data on mouse-up, unfortunately.)

**Comment by jtdaugherty** [comment]
In case you're interested, the code that translates Vty mouse-down events into (possibly) Brick mouse-down events is [here](https://github.com/jtdaugherty/brick/blob/master/src/Brick/Main.hs#L317).

**Comment by jtdaugherty** [comment]
(As you can see from the code, Brick's mouse-down events are also more useful if they were in viewports, since the click coordinates become modified to be relative to the viewport offset -- so viewport-local coordinates rather than screen-space coordinates.)

**Comment by jtdaugherty** [comment]
Brick mouse events in clickable regions always come with the local coordinates within the clickable region, too - the general case of what happens with viewports specifically.

**Comment by simonmichael** [comment]
Thanks!

Using MouseUp has been a successful workaround, I guess mouse up doesn't suffer from bouncing. For better visual feedback, I still use MouseDown to move the selection, but MouseUp to do the non-idempotent action. (Eg [here](https://github.com/simonmichael/hledger/pull/1760/commits/f01eddbba71cc3f1dba5010c8704ace75eb8f32d)).

**Comment by jtdaugherty** [comment]
Okay, I'm glad you found an approach that works. Is there more that we should discuss on this ticket?

**Comment by simonmichael** [comment]
I don't have a patch right now, but if no debouncing is done (eg timer based) I think it would be helpful to mention the issue in MouseDown's haddock. "MouseDown events can sometimes be duplicated, for actions which should only run once consider using MouseUp instead."

**Comment by simonmichael** [comment]
(And likewise in VtyEvent's haddock.)

**Comment by jtdaugherty** [comment]
The library does not duplicate events, though; that's a terminal emulator behavior. I could mention that in the docs, but I'm not sure how useful it is if it the repetition is hard to predict.

**Comment by jtdaugherty** [comment]
I'd also be curious if you have used other input devices beyond your touchpad. Those can *easily* duplicate clicks if you use touch-to-tap.

**Comment by simonmichael** [comment]
Ok, I'm not sure how widespread this is; I can only report that it happens in three different terminals I've tried using a macbook touchpad. I haven't compared a mouse (don't have to test at the moment).

**Comment by jtdaugherty** [comment]
Okay. If you find that it happens with other input devices, I'd be happy to reconsider a documentation update. I'd just like to make sure we know enough to know that this isn't isolated to the particular input device in this case since I don't have any reports or personal experience with this happening before.

**Comment by jtdaugherty** [comment]
Thanks for the discussion! On the assumption that we're good to go on this for now, I'll close this. Please re-open if needed!
