### ISSUE TITLE
Attr Semigroup is not working

### ISSUE THREAD

**Issue by yaitskov** [jtdaugherty/brick#351]
Hi,

I noticed that `<>` is not working for merging foreground and background:

```
import Brick 
import Brick.AttrMap
import Graphics.Vty

blueOnGreen :: AttrName
blueOnGreen = attrName "blueOnGreen"

myMap () = attrMap defAttr [ (blueOnGreen, bg blue <> fg green) ]
```

just last operand of `<>` (green here) takes effect.

workaround:
```
myMap () = attrMap defAttr [ (blueOnGreen, blue `on` green) ]
```

**Comment by jtdaugherty** [comment]
Hi, thanks for asking about this! The behavior you describe [is the intended behavior](https://hackage.haskell.org/package/vty-5.33/docs/src/Graphics.Vty.Attributes.html#line-119) for the `Attr` type. I didn't write that instance, but I believe its override behavior is depended on in various spots in the `vty` library. The solution you found with `on` is what I would have recommended to get the attribute you wanted.

**Comment by jtdaugherty** [comment]
I'll look into whether the instance could be rewritten and see what impact that might have.

**Comment by jtdaugherty** [comment]
It turns out that there are actually not that many spots where the current instance is even relied upon, so that's nice. But interestingly, now I'm wondering why the original behavior didn't just work as you expected. I'll take a closer look, probably tomorrow.

**Comment by jtdaugherty** [comment]
Would you be willing to try out `master`? There are actually unreleased patches there that rewrote the `MaybeDefault` `Semigroup` instance, which would affect `Attr`.

**Comment by jtdaugherty** [comment]
Well, even on `master` I don't seen an improvement:
```haskell
*Graphics.Vty Graphics.Vty.Attributes> (defAttr `withBackColor` black) <> (defAttr `withForeColor` blue)
Attr {attrStyle = Default, attrForeColor = SetTo (ISOColor 4), attrBackColor = Default, attrURL = Default}
```

**Comment by jtdaugherty** [comment]
So the issue is that the `Semigroup` instance for `MaybeDefault` has the preference for the RHS:
```haskell
  instance Semigroup (MaybeDefault v) where
      _        <> v@(SetTo _) = v
      x        <> KeepCurrent = x
      _        <> Default     = Default
```
That might be a tougher thing to change. I'll look into it.

**Comment by jtdaugherty** [comment]
I am starting to think that `Semigroup` is not even the right place for this functionality (which for various reasons does need to have a preference for the RHS argument). That leads me to think that `Semigroup` instances for `MaybeDefault` and `Attr` probably don't even make sense because they lose information too easily (if e.g. both attributes provide a foreground color, one must always be discarded). Only some fields of `Attr` can be sensibly combined (e.g. `style`) and even then, only under certain conditions.

**Comment by jtdaugherty** [comment]
I wouldn't say I "fixed" this, but I did make a change to address it in https://github.com/jtdaugherty/vty/commit/f8f45c2af5aaeeeb12b8fae8568a307c5d89ef38. Let me know if I can help with anything else.
