### ISSUE TITLE
How to flip background/foreground colors?

### ISSUE THREAD

**Issue by yaitskov** [jtdaugherty/brick#352]
Hi,

I am trying to build an alternative progress bar based on ASCII graphics.
UTF alphabet is rich, but I need to take advantage of colors inversion, because there is only half of characters I need (" ▁▂▃▄▅▆▇█"). 
It is easy when colors are set through widget argument, but it doesn't follow attribute approach and it would be more continent if background could be inherited from the app. 
I see there is an option KeepCurrent, but when it comes to flipping foreground and background colors it is not enough. I think adding Inverse data constructor next to KeepCurrent and interpreting it as take KeepCurrent from opposite (i.e. use KeepCurrent background for foreground and vice versa).

**Comment by yaitskov** [comment]
I found out about reverseVideo style. It solves my problem, thought there is a warning that it is not supported by all vterms.

```
setVideoReverse a = a { 
        attrStyle = case attrStyle a of 
                      SetTo s -> SetTo $ s .|. reverseVideo
                      Default -> SetTo $ standout .|. reverseVideo 
                      KeepCurrent -> SetTo $ standout .|. reverseVideo 
      }

```

**Comment by jtdaugherty** [comment]
Great, I'm glad you found that - I was going to recommend it.

**Comment by jtdaugherty** [comment]
Also, in the future it might be helpful to open Vty issues on [the Vty repository](https://github.com/jtdaugherty/vty). Anything that is specific to Vty can be discussed there.
