### ISSUE TITLE
No auto scrolling to keep current list element visible

### ISSUE THREAD

**Issue by yaitskov** [jtdaugherty/brick#353]
Hi,

I noticed that a list widget doesn't scroll itself, so user with keys can navigate to an element 
located behind terminal window.
I would expect scrolling to follow current element.
As workaround I scroll manually:

```
do
  vScrollBy (viewportScroll SpecListViewportName) 1
  handleListEvent vtyev speclistview
```

I tried to use show request inside list widget, but wrapping item widget into `visible` for current list element doesn't change anything.

```
drawUI =  viewport SpecListViewportName Both listView 
  where
    listView =  hLimitPercent 100 $ vLimit 1000 $ renderList renderItem False [ show i | i <- [ 0 ..999]]

renderItem :: Bool -> String -> Widget UIName
renderItem True msg = visible $ str msg
renderItem False msg = str msg
```

**Comment by jtdaugherty** [comment]
> I noticed that a list widget doesn't scroll itself, so user with keys can navigate to an element located behind terminal window.

I'm not sure I understand what behavior your are looking for. Can you say more?

**Comment by yaitskov** [comment]
I realized my app has wrong layout (list widget is wrapped into viewport).
ListDemo.hs doesn't use ViewPort at all and vertical scrolling is working very well there.

While developing horizontal scrolling in ListDemo (throught wrapping hLimit of max list item into ViewPort) I noticed another minor issue - scrolling is not reset after widget width changes i.e. add a long item to the list wider than ViewPort - scroll to its rightmost part and press `-` to remove. Widget is drawn in an ugly state then and the UI is fixed after horizontal scrolling manually (pressing left/right ).

Workaround is to send scroll after item removal. 
It is working but abstraction is totally broken.

```
                  let l' = L.listRemove i l
                  hScrollBy (viewportScroll ViewPort1) (-1)
                  M.continue l'
```

```

import Data.Maybe (fromMaybe)
import Control.Monad
import Control.Lens
import qualified Graphics.Vty as V

import qualified Brick.Main as M
import qualified Brick.Types as T
import qualified Brick.Widgets.Border as B
import qualified Brick.Widgets.List as L
import qualified Brick.Widgets.Center as C
import qualified Brick.AttrMap as A
import qualified Data.Vector as Vec
import Brick.Types
  ( Widget, ViewportType (Horizontal)
  )
import Brick.Widgets.Core
  ( (<+>)
  , str
  , vLimit
  , hLimit
  , vBox
  , withAttr, viewport
  )
import Brick.Util (fg, on)
import Brick (ViewportScroll(hScrollBy), viewportScroll)

class WidthEstimate a where
  estimateWidth :: a -> Int 

instance WidthEstimate [a] where
  estimateWidth = (+ length ("Item <\"\">" :: String)) . length

drawUI :: (Show a, WidthEstimate a) => L.List Name a -> [Widget Name]
drawUI l = [ui]
    where
        label = str "Item " <+> cur <+> str " of " <+> total
        cur = case l^.(L.listSelectedL) of
                Nothing -> str "-"
                Just i -> str (show (i + 1))
        total = str $ show $ Vec.length $ l^.(L.listElementsL)
        box = B.borderWithLabel label $
              hLimit 25 $
              viewport ViewPort1 Horizontal $
              hLimit (maximum [25, maximum $ estimateWidth <$> L.listElements l]) $
              -- vLimit 15 $
              L.renderList listDrawElement True l
        ui = C.vCenter $ vBox [ C.hCenter box
                              , str " "
                              , C.hCenter $ str "Press +/- to add/remove list elements."
                              , C.hCenter $ str "Press Esc to exit."
                              ]

appEvent :: L.List Name String  -> T.BrickEvent Name e -> T.EventM Name (T.Next (L.List Name String))
appEvent l (T.VtyEvent e) =
    case e of
        V.EvKey (V.KChar '+') [] ->
            let el = nextElement (L.listSelected l) (L.listElements l)
                pos = Vec.length $ l^.(L.listElementsL)
            in M.continue $ L.listInsert pos el l

        V.EvKey (V.KChar '-') [] ->
            case l^.(L.listSelectedL) of
                Nothing -> M.continue l
                Just i -> do
                  let l' = L.listRemove i l
                  hScrollBy (viewportScroll ViewPort1) (-1)
                  M.continue l'
        V.EvKey V.KLeft [] ->  
          hScrollBy (viewportScroll ViewPort1) (-1) >> M.continue l
        V.EvKey V.KRight [] ->  
          hScrollBy (viewportScroll ViewPort1) 1 >> M.continue l
        V.EvKey V.KEsc [] -> M.halt l
        V.EvKey (V.KChar 'q') [] -> M.halt l        

        ev -> M.continue =<< L.handleListEvent ev l
    where
      nextElement :: Maybe Int -> Vec.Vector String -> String
      nextElement mi v = 
        case mi of
          Just i -> 
            (Vec.toList v !! i) ++ "+" ++ (Vec.toList v !! minimum [Vec.length v - 1, i + 1])
          Nothing -> 
            case reverse $ Vec.toList v of
              l:l2:_ -> l ++ "+" ++ l2
              _ -> "new asdf asdf asdf asdasdf "

appEvent l _ = M.continue l

listDrawElement :: (Show a) => Bool -> a -> Widget Name
listDrawElement sel a =
    let selStr s = if sel
                   then withAttr customAttr (str $ "<" <> s <> ">")
                   else str s
    in C.hCenter $ str "Item " <+> (selStr $ show a)

initialState :: L.List Name String
initialState = L.list L ((:"12345") <$> Vec.fromList ['a'..'z']) 1

customAttr :: A.AttrName
customAttr = L.listSelectedAttr <> "custom"

theMap :: A.AttrMap
theMap = A.attrMap V.defAttr
    [ (L.listAttr,            V.white `on` V.blue)
    , (L.listSelectedAttr,    V.blue `on` V.white)
    , (customAttr,            fg V.cyan)
    ]

theApp :: M.App (L.List Name String) e Name
theApp =
    M.App { M.appDraw = drawUI
          , M.appChooseCursor = M.showFirstCursor
          , M.appHandleEvent = appEvent
          , M.appStartEvent = return
          , M.appAttrMap = const theMap
          }

data Name = L | ViewPort1 deriving (Show, Eq, Ord)          

main :: IO ()
main = void $ M.defaultMain theApp initialState

```

**Comment by jtdaugherty** [comment]
I see, you figured out the list issue; yes, indeed, it internally uses a viewport so you won't need to wrap it in an additional one.

> scrolling is not reset after widget width changes

In general, I don't agree that it should reset. If you want it to reset, it ought to be possible to use the API to do that. The reason why I don't think this should be true in general is that there will be plenty of cases when doing that automatically would lead to undesirable scrolling resets. If you're putting a list in a horizontal viewport, then you definitely will have to make choices about how to deal with the scrolling position. I wouldn't recommend doing this at all, but if you must do it, you'll need to decide when and how to deal with the horizontal scroll position.

> It is working but abstraction is totally broken.

Just to be explicit, this is really not that helpful or accurate. I am happy to help you with any Brick issues you encounter, but it would also be helpful if you're open to changing your approach in case there is a more effective way to use the library. I'd be happy to provide feedback along those lines.

**Comment by yaitskov** [comment]
>  yes, indeed, it internally uses a viewport so you won't need to wrap it in an additional one.

> I wouldn't recommend doing this at all, but if you must do it, you'll need to decide when and how to deal with the horizontal scroll position.

Does it mean that the list widget can do horizontal scrolling on its own?
As for now I was able to figure out just 1 way involving dynamic hLimit and a viewport which requires to scroll after item removal. I could live with this if I write some adapters. 

Sorry if I said some harsh.

**Comment by jtdaugherty** [comment]
> Does it mean that the list widget can do horizontal scrolling on its own?

The built-in list does not do any horizontal scrolling on its own. It is just intended for vertically-scrolled lists of elements.

> As for now I was able to figure out just 1 way involving dynamic hLimit and a viewport which requires to scroll after item removal. I could live with this if I write some adapters.

One possibility is that the built-in List is not the best fit for what you want to do, but I recognize that it might be undesirable to re-implement something like the List. If you have a working application I could try out, then I'd be happy to take a look and see if I have any alternative ideas for how to accomplish what you want.

**Comment by jtdaugherty** [comment]
I also wanted to follow up and say that I'm not sure if there is more you wanted to discuss on this ticket. If so, let me know - or close it if we've addressed your question(s). Thanks!
