### ISSUE TITLE
Scrolling viewport is limited till evaluated items

### ISSUE THREAD

**Issue by yaitskov** [jtdaugherty/brick#355]
Hi,

List widget doesn't have all items ready for rendering so vScrollBy cannot be used to show list tail.
When first item is selected vScrollBy has no effect.
When 2nd item is selected vScrollBy can scroll by 1 element down.
When 3nd item is selected vScrollBy can scroll by 2 elements down.
etc.

**Comment by jtdaugherty** [comment]
Can you provide more information? I'm not sure I understand what the problem is.

> When 2nd item is selected vScrollBy can scroll by 1 element down.

`vScrollBy` is for scrolling the viewport, not the list selection, in case that matters.

**Comment by jtdaugherty** [comment]
Hi @yaitskov - I am still curious to know more about what behavior you are looking for on this report. As with other reports, a small test program that exhibits an undesirable behavior, as well as a description of what you are looking for, would be really helpful for me to understand. Thanks!
