### ISSUE TITLE
str with escape chars (color) not being cropped accurate

### ISSUE THREAD

**Issue by dynnamitt** [jtdaugherty/brick#359]
I'm using a set of lines (str) inside a [vBox](https://github.com/dynnamitt/hask-hex/blob/main/Tui.hs#L42), 

Issue: as soon as the line (image) introduces **escape chars for coloring** ,
that line is not being cropped like the normal lines ? 

(Even the border wrapping the vbox is affected)

It is drawn shorter as seen in  picture: https://github.com/dynnamitt/hask-hex/blob/main/bmps/random-cells.png

Why is this?

**Comment by dynnamitt** [comment]
Reading other similar issues  I will point out that I wish to use ALOT of colors splattered around the grid, and breaking the images up one char at a time to give it an attrib would sink the performance I think.

Maybe Vty is a better framework for solving a colorfull ascii carpet app (game) ?

It's unclear to me if I would face same issues there re [width](https://hackage.haskell.org/package/vty-5.25.1/docs/Graphics-Vty-Image.html#t:Image) calculation

**Comment by jtdaugherty** [comment]
You can use Vty images embedded in brick by using `Brick.Widgets.Core.raw`. I suggest you either use that or write a custom widget; if you plan on using a lot of small images, then building your own in a custom widget will give much better performance than using a giant vBox or hBox. I'm happy to help if you would like to know more about how to do this.

But to answer your original question, you should use Vty attributes (Attr) to set the color and style of your output. Manual escapes are unnecessary but also forbidden in the output for exactly this reason: the library is responsible for that (to help you!) so you shouldn't need to emit escapes yourself for any reason. The docs for many functions in the Core module also explicitly point out that the embedded output should never contain escapes.

As for width calculations, you may definitely need to deal with that if you're going to be emitting wide Unicode characters. Let me know if so, and I'm happy to point you at the right functions. But before we go into that level of detail, it might be better to first move in one of the directions I described above and then see if width calculation issues will need to be addressed.
