### ISSUE TITLE
Why does `suspendAndResume` have to terminate the event handler?

### ISSUE THREAD

**Issue by gnull** [jtdaugherty/brick#360]
Why does

```haskell
suspendAndResume :: IO s -> EventM n (Next s)
```
have `Next` in its signature? Can I implement something that is similar but has a signature of `liftIO`?

I want to run external terminal apps in my program, and I would love to simply `suspendAndResulme` some program and then another one inside the same `EventM` action. (Embedding things into `Next` is harder for me because I keep my state inside a StateT wrapped around EventM, so I don't normally use `Next` in my event handlers unless I talk to Brick.)

Is it possible to implement `suspendAndResume :: IO s -> EventM n s` or is there some deeper reason I shouldn't be doing this?

**Comment by jtdaugherty** [comment]
Thanks for opening this.

> I want to run external terminal apps in my program, and I would love to simply suspendAndResulme some program and then another one inside the same EventM action.

I think it would be helpful to me if we can just start with this bit here. Can you help me understand why `suspendAndResume` is not currently helping you do what you want to do? The use case it seems you are describing ("run external terminal apps") is pretty much exactly why `suspendAndResume` exists.

**Comment by gnull** [comment]
Sorry if I made it confusing :)

Right now `suspendAndResume` returns `Next s` which I have to return in order to have my `IO` action executed. For example, if I do

```haskell
action :: s -> EventM n (Next s)
action s = do
  _ <- suspendAndResume $ system "vim /tmp/some-file"
  _ <- suspendAndResume $ system "vim /tmp/another-file"
  -- The ignored values above are Next ExitCode. Imagine I don't care about exit codes :)
  continue s
```

Vim will not get executed even once since I ignored both values returned from `suspendAndResume`.

As I understand, the expected way to achieve what the code above fails to achieve is to do something like:

```haskell
action' :: s -> EventM n (Next s)
action' s = do
  suspendAndResume $ do
    system "vim /tmp/some-file"
    system "vim /tmp/another-file"
    pure s
```

In this example it's easy to transform and put all the `IO`s inside one `suspendAndResume` but I'd like to have my IOs inside separate `suspendAndResume`s and intermix them with normal `EventM` code.

**Comment by jtdaugherty** [comment]
Thank you, that example is helpful!

> In this example it's easy to transform and put all the IOs inside one suspendAndResume but I'd like to have my IOs inside separate suspendAndResumes and intermix them with normal EventM code.

What is important to you about being able to mix your IO (terminal-controlling) program invocations with other `EventM` code?

**Comment by gnull** [comment]
I don't have a specific case where it would be critical for my app. But it seemed like a natural thing to want when I was designing it.

I can give you a made-up but reasonable example. Imagine I want to open a temporary file in an external editor, let the user type something in it, and when they close it I want to read what they put there and update my state based on that. Say, the user puts in a code snippet to be executed by my app (similar to what Ctrl+x Ctrl+e does in Bash). Right now, the changes I can make to the state after I executed the editor are limited to `IO s`, I can't do other things that `EventM (Next s)` allows (like scrolling a viewport).

This example is close to what I'm trying to do in my app. In my case just `IO s` should be enough though.

Is there a function like `redrawScreen :: EventM ()` (or a pair `suspendScreen` + `resumeScreen`) that one could combine with `liftIO` in order to achieve what `suspendAndResume` does?

**Comment by jtdaugherty** [comment]
> Say, the user puts in a code snippet to be executed by my app (similar to what Ctrl+x Ctrl+e does in Bash). Right now, the changes I can make to the state after I executed the editor are limited to IO s, I can't do other things that EventM (Next s) allows (like scrolling a viewport).

In case it helps, it's possible to do this right now via a slightly different route: custom application events. If you use a custom event type, then you can inject your own events into the event stream from your `IO` code (*even* values of type `EventM`!) and evaluate them in your event handler. If you're interested in this, I am happy to elaborate, but essentially it would just entail sending a custom event over the application's event channel so that the very next event handler invocation after your `IO` code runs would be to handle the custom event(s) you just queued up.

> Is there a function like redrawScreen :: EventM () (or a pair suspendScreen + resumeScreen) that one could combine with liftIO in order to achieve what suspendAndResume does?

No. The reason in a nutshell is because `EventM` isn't designed to let you relinquish control of the terminal *within* an `EventM` block. You can only relinquish at the end (i.e. with `suspendAndResume`) so that Brick can do its internal shutdown of its Vty handle, invoke your `IO` code, and then create a new Vty handle to resume control of the terminal.

**Comment by gnull** [comment]
Sure, the custom events idea makes sense to me! Although I've already found a way to neatly integrate the `suspendAndResume` into my code (thanks to the discussion we had here ☺).

Thanks a lot for your replies @jtdaugherty !

**Comment by jtdaugherty** [comment]
You're welcome, thanks for your patience as we sort it all out. I am happy to help!
