### ISSUE TITLE
Vty support for rxvt (was: problems with mouse click detection)

### ISSUE THREAD

**Issue by byorgey** [jtdaugherty/brick#366]
I want to add mouse support to https://github.com/swarm-game/swarm/ , but I have been unable even to get the `brick-mouse-demo` working.  I can build and run it fine with `cabal build -fdemos brick-mouse-demo` and then `cabal exec -fdemos brick-mouse-demo`.  But then no matter where I click nothing happens; the message at the bottom always says "last reported click: nothing".  I have tried running it in both rxvt-unicode and gnome-terminal with the same (non-)result.

I am very open to the possibility that I am doing something wrong, but curious at least to see if anyone else can reproduce this or if it's just me.

**Comment by jtdaugherty** [comment]
Huh, that is a bit of a mystery to me, especially if (as discussed in the Swarm issue) you were able to observe some kind of mouse detection in the terminal!

Out of curiosity, have you attempted this in `xterm`? I usually develop Vty and Brick and test them in iTerm2 and xterm on MacOS. I just tried `xterm` from Xquartz and the mouse demo worked as I expected there.

**Comment by jtdaugherty** [comment]
Also, just in case this is slipping by unnoticed: if you click and hold, does the `last reported click` message change? It only changes to `Just ...` while the mouse is down, but even so, it should be pretty noticeable that it changes if you click and release quickly.

**Comment by jtdaugherty** [comment]
Do you have access to other terminal applications that support mouse input, such as `tmux`? I'm wondering if we can get a positive control that isn't `vty`-based.

**Comment by jtdaugherty** [comment]
As an aside, there was a mouse mode bug fix in 0.68.1 that I strongly suggest you upgrade to. (The bug fix is unrelated to the behavior we're discussing, but I mention it so you can be aware as you try out mouse support.)

**Comment by jtdaugherty** [comment]
Another question: what is the value of `TERM` in the cases where mouse interaction isn't working in the Brick demo?

**Comment by byorgey** [comment]
- I can confirm that in `tmux` I am able to e.g. switch between panes by clicking with the mouse.
- Re: 0.68.1, noted.  I was in fact using 0.68.1 to build the mouse demo; I will look into upgrading the version `swarm` depends on as well.
- The value of `TERM` was `rxvt-unicode`.  When I tried running the mouse demo with `TERM` set to `xterm`, it worked!!

So it seems my `TERM` environment variable is the culprit, or perhaps the way that the `TERM` environment variable is handled by `vty`.  I honestly don't know much about what the `TERM` variable means or why one might set it to any value in particular. (Mine was set to `rxvt-unicode` so long ago that I no longer remember when or why.)

**Comment by jtdaugherty** [comment]
Concretely, you'd need to set the `termName` field of your vty `Config` to `xterm` as follows (using the `MouseDemo` code as a basis):
```haskell
main :: IO ()
main = do
    let buildVty = do
          cfg <- V.standardIOConfig
          v <- V.mkVty $ cfg { termName = "xterm" }
          V.setMode (V.outputIface v) V.Mouse True
          return v
    initialVty <- buildVty
    void $ M.customMain initialVty buildVty ...
```

**Comment by byorgey** [comment]
So one important thing I learned from your response is that I should not be setting my `TERM` variable manually!  I discovered that it was being set to `rxvt-unicode` in one of my files that runs when `zsh` starts up.  That meant it was *always* set to `rxvt-unicode`, even when I was actually running `xterm`!  (Again, I have no idea why.)  After deleting that, `TERM` is set to `xterm`, or `rxvt-unicode-256color`, etc. appropriately.

Also, all of this probably also explains why bracketed paste mode wasn't working for me either.

> The backend it chooses only supports features that have a terminfo presence, which unfortunately is not that many, and that means that you don't get mouse support in that backend because it isn't part of terminfo as far as I know.

I don't know much about this, but it seems like mouse support is part of terminfo, e.g. search for "mouse" at https://man7.org/linux/man-pages/man5/terminfo.5.html .  And all the mouse-related capabilities seem to indeed be listed in the output of `infocmp` for my terminal:
```
diophantus :: ~ » infocmp rxvt-unicode-256color | grep mous
	kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~, kslt=\E[4~,
```
Thanks for the suggestions re: setting the `termName` to `xterm` manually.  I'll play with that and see if it will work.

**Comment by jtdaugherty** [comment]
> Also, all of this probably also explains why bracketed paste mode wasn't working for me either.

Yes, that would explain it!

> it seems like mouse support is part of terminfo

Thanks! I will look into those capabilities and see if they seem to be widely available enough to depend on and also correspond to what Vty is currently doing. (Another problem with `terminfo` is that even if some capabilities exist, you can't always depend on all terminfo entries to provide them for your favorite emulator.)

**Comment by jtdaugherty** [comment]
For what it's worth, another thing I'd be happy to do is to add the string `"rxvt"` to the list of valid "xterm-alike" `TERM` values that Vty uses to select the Xterm backend. Vty doesn't have an Rxvt-specific backend and if Rxvt is reliably like Xterm enough for Vty's purposes, that would be a fine thing to do (albeit still a gross hack because it makes that assumption going forward). I should also point out that the Vty Xterm backend *still* uses `terminfo` when it can; it just goes beyond `terminfo` for things that have no `terminfo` presence.

**Comment by byorgey** [comment]
Thanks! I don't know enough about any of this to know whether it would be reasonable to add a special case for `"rxvt"`.  At least now I know what the issue is and several potential workarounds.  I'll leave it to you whether you want to close this issue --- I'm happy for it to be closed but maybe you want to keep it open as a placeholder for investigating this more.

**Comment by jtdaugherty** [comment]
Okay, thanks. I'll keep it open for now and will ultimately migrate it over to the `vty` repo.

**Comment by jtdaugherty** [comment]
This is now fixed in https://github.com/jtdaugherty/vty/commit/c15a9dd9e700e461fcd790de2d79e073415dae42.
