### ISSUE TITLE
Brick.Markup

### ISSUE THREAD

**Issue by qcc-na** [jtdaugherty/brick#367]
https://hackage.haskell.org/package/brick-0.67/docs/Brick-Markup.html

Latest stackage (version 68.1) shows this as gone.  Is this gone for good?  I was using this...

**Comment by jtdaugherty** [comment]
HI @qcc-na. Yes, that's right, `Brick.Markup` and `Brick.Widgets.Markup` were removed in `0.68`. I'm sorry to hear that this affected you, but both of those modules are self-contained enough that it should be pretty easy to integrate them into your own application if you like. Let me know if there's anything I can do to help!

**Comment by qcc-na** [comment]
Ok, that sounds like an appropriate path forward.  I knew they were experimental when I used them per the docs. Thank you.
