### ISSUE TITLE
Grid display

### ISSUE THREAD

**Issue by cdupont** [jtdaugherty/brick#371]
Hello, thanks a lot for this great library!
I'm trying to display things in a grid.
Looks simple enough with `<+>` and `<=>`. However, my widgets have different (and dynamic) sizes...
For instance, I need:
```
 .      .  
test    .
```
What do you advice?

**Comment by jtdaugherty** [comment]
Hi @cdupont - there are probably a few ways to do what you want. One option, depending on the kinds of things you want to display, is to use `Brick.Widgets.Table` to lay out your elements in a table format. (And if you want, you can disable the table and cell borders to just get a grid layout.)

However, if you have things to lay out that have more dynamic sizes than `table` will allow, typically the way to do this is to still use `hBox`/`vBox` (`<+>` and `<=>`) but use limiters (`hLimit` and `vLimit`) combined with the padding functions (e.g. `padAll` and friends) to get the box layout to have a grid shape that you can control.

If you would like more specific help, it might help me to see your code and understand what you are shooting for.

**Comment by cdupont** [comment]
I was worried with Table because the columns might not have all the same width, depending on the content (as far as I understand).
What I really want is to display things in the 2D plane, with XY coordinates...
Thank you so much for your help.

**Comment by jtdaugherty** [comment]
The table widget does not require the column contents to have the same width, although it renders them that way as you would expect from a table. 

But it sounds like you'd need something different anyway. Can you say a bit more about your use case?

**Comment by cdupont** [comment]
I need to display widgets at fixed positions: a regular grid. Widgets need to be padded/cropped accordingly. 
My draft code is here: https://github.com/cdupont/timetravel/blob/main/app/Tree2.hs#L143
I started to write the display functions (prettyXX), but I thought, hey, maybe some cool library exists out there!

**Comment by jtdaugherty** [comment]
If you want to display things in a regular grid, a `table` probably will be a good fit. A table will pad the cells so they are all the same size per-row and per-column (i.e. the size of the largest cell in each row and column, as you would expect). If you need to do cropping, that's just a matter of using a limiter on each cell as desired. I recommend checking out `Brick.Widgets.Table.table` and seeing if that works for you. I also suspect that you'll need to cache the result to make sure the performance doesn't suffer, so for that you'll need `Brick.Widgets.Core.cached`.

Both of those functions have demo programs that you can check out: `programs/TableDemo.hs` and `programs/CacheDemo.hs`.

**Comment by cdupont** [comment]
Is there a way to set the width of columns and height of rows (irrespective of the content)?

**Comment by jtdaugherty** [comment]
Tables get their cell dimensions from the dimensions of the cells' contents. Put another way, a table row is as high as its highest cell, and a column is as wide as its widest cell. Does that make sense?

**Comment by cdupont** [comment]
Yes, thanks!

**Comment by jtdaugherty** [comment]
Here are some tips:
* If you want a column to have width `n` and the widgets in that column are more than `n` wide, add `hLimit n` to each of them.
* If you want a column to have width `n` and the widgets in that column are less than `n` wide, pad one of the widgets with `Max` to make the table column wider (e.g. `padRight Max`) and then set the table column's alignment as desired.

**Comment by jtdaugherty** [comment]
And a word to the wise: if you are thinking of using `table` to make something with *many* rows and columns, you might be better off 1) caching the result with `Brick.Widgets.Core.cached` if it doesn't change too much or 2) building a Vty image by hand and embedding it with `Brick.Widgets.Core.raw`.

**Comment by jtdaugherty** [comment]
@cdupont - let me know if there is anything else I can help with on this ticket, or close it if you have what you need. Thanks!

**Comment by cdupont** [comment]
Oh, thanks for pointing me the "Max" argument.
I tried:
```
ui' :: Widget ()
ui' = center $ renderTable $ alignCenter 0 $ alignCenter 1 $ alignMiddle 0 $ alignMiddle 1 $ ta

cell :: Widget ()
cell = vLimit 5 $ hLimit 10 $ padRight Max $ padBottom Max $ str " "

ta :: Table ()
ta = table [[cell, str "B"],
            [str "C", cell]]
```

![image](https://user-images.githubusercontent.com/484033/174554163-702cf986-95cf-4587-b9df-c0e85e53f16d.png)

This works well, however I'm obliged to setup "template cells" on each row and column to get the result.

I also noticed that I cannot use `emptyWidget` instead of `str " "` in the `cell` function: the padding will be ignored.

Sorry for abusing your time :)

**Comment by jtdaugherty** [comment]
> This works well, however I'm obliged to setup "template cells" on each row and column to get the result. The content of those cells will not be easy to center as the padding grows only on one side.

For those cells you can just use `emptyWidget`. There's no need to populate them with something that has exactly the right dimensions since the other cells (`long` and `B` here) will determine their width and height.

> I also noticed that I cannot use emptyWidget instead of str " " in the cell function: the padding will be ignored (maybe that's normal).

Just use `emptyWidget` without the padding. Padding only makes sense if you have something with a measurable padding dimension (i.e. you can't left-pad something of zero height). So all you need is

```haskell

ta :: Table ()
ta = table [[emptyWidget, str "B"],
            [str "long", emptyWidget]]
```

**Comment by jtdaugherty** [comment]
But, as you'll find out next, the table I posted means you lose the padding that made your rows and columns expand. You'll need to add it back on the strings. I recommend using `center` with limiters since that is visually giving you what you want. In that case you don't need the table to do the centering for you. So the full result would be:

```haskell
ui :: Widget ()
ui = center $ renderTable ta

centerCell :: Widget n -> Widget n
centerCell = hLimit 10 . vLimit 5 . center

ta :: Table ()
ta = table [[emptyWidget, centerCell $ str "B"],
            [centerCell $ str "long", emptyWidget]]
```
