### ISSUE TITLE
Table problem

### ISSUE THREAD

**Issue by cdupont** [jtdaugherty/brick#372]
Hi, I'm opening this new issue not to overflow the other one.
I noticed this behavior of tables:
```
tab :: Table ()
tab = table [ [txt "A\nB", txt "C"]
            , [txt "D",  txt "E"]
            ]
```
![image](https://user-images.githubusercontent.com/484033/174474406-4c8043b4-a58f-4f49-93b8-b7b2d803e078.png)

Should the rows be aligned?

**Comment by jtdaugherty** [comment]
As it happens, this behavior was just fixed yesterday 0.69.1!
