### ISSUE TITLE
Brick 1.0 tasks

### ISSUE THREAD

**Issue by jtdaugherty** [jtdaugherty/brick#384]
* [x] Merge `refactor/event-state-monad`
* [x] Merge `feature/custom-keybindings`
  * [x] Write module-level Haddock documentation for custom keybindings API usage
  * [x] Review and update Haddock for all functions and types in the custom keybinding modules
    * Done as of eb54e536a17bcf9cda9f295057127bd49ebbd548
  * [x] Add support for reading INI files of keybinding configurations using `config-ini`
    * Done as of 0561cccda07a83e3248b3ac2591577bebddd5510
  * [x] Update User Guide with custom keybindings features
    * Done as of d9d62f4853c72a53382fdac46e414b3769e02957
  * [x] Clean up `Widget` formatting of keybinding help
  * [x] Introduce attributes to allow control over `Widget` help formatting
  * [x] Resolve section heading API wart with `keybindingHelpWidget`
  * [x] Write demo program for custom keybindings machinery
  * [x] Make `keyEvents` raise an exception if any input events have the same name (ignoring case)
  * [x] Make `Binding`s ignore (and normalize) ordering of modifiers
* [x] Fix `AttrName` API
  * Done as of 6f1b62ae535bdb42b1b3426ab1d8247da72d423e
* [x] Update User Guide for EventM changes
  * Happening on `documentation/brick-1.0-staging`
* [x] Write 1.0 upgrade guidance (location TBD)
* [x] Update changelog, as usual
* [x] Update README with pointer to 1.0 upgrade guidance
* [x] Prepare a `brick-skylighting` release to be put out concurrently with Brick 1.0
  * Implementation updates done on `brick-1.0` branch of `brick-skylighting`

**Comment by jtdaugherty** [comment]
@byorgey @xsebek you might like to take a look at the `feature/custom-keybindings` branch which I'm going to include in the 1.0 release that ships with the `EventM` changes. You can start by looking at the docs in `Brick.Keybindings` and go from there. (Relevant to https://github.com/swarm-game/swarm/issues/523)

**Comment by jtdaugherty** [comment]
@byorgey @xsebek See also `programs/CustomKeybindingDemo.hs` that I just pushed to that branch for a complete working example.

**Comment by jtdaugherty** [comment]
The keybindings work has been merged to `master` and will continue to get polished there before release.

**Comment by jtdaugherty** [comment]
@xsebek @byorgey You might be interested to know that the keybinding demo program now demonstrates how to load custom keybindings from an INI file. See `master` as of ad91a0b7270c3a72ad283cfc6e64a42c9ad31dba.

**Comment by jtdaugherty** [comment]
Hi everyone, Brick 1.0 is out including these changes! https://github.com/jtdaugherty/brick/blob/master/CHANGELOG.md#10

**Comment by cdupont** [comment]
Congratulations!
