### ISSUE TITLE
Custom character

### ISSUE THREAD

**Issue by cdupont** [jtdaugherty/brick#385]
Hello,
As far as I understand, Widgets are created from unicode characters. 
But is it possible to create a custom Widget with some random bitmap?
Thanks

**Comment by jtdaugherty** [comment]
Hi @cdupont - by bitmap do you mean image data, such as like [this](https://askubuntu.com/questions/97542/how-do-i-make-my-terminal-display-graphical-pictures)?

**Comment by cdupont** [comment]
I mean, I don't always find a unicode character that matches what I want.
So I thought why not drawing it pixel by pixel.

**Comment by jtdaugherty** [comment]
Okay, I see. Terminals don't give us that kind of control. If you're building an application where you want that kind of control over the graphics, you'd need to use something like SDL, but that would also mean not building a terminal application anymore. I hope that helps!

**Comment by cdupont** [comment]
OK, thanks.
I see that Unicode supports a lot of emojis/icons: http://xahlee.info/comp/unicode_food_drink.html
Do you recommend using them?

**Comment by jtdaugherty** [comment]
You can use those, but in general, terminals are not very good about supporting emoji. Many will not be rendered with the correct width, which means that when they are displayed in Brick UIs, many will cause the layout to break. Every so often, people report issues on this repo and the Vty repo about this. I can go into more detail on why this happens, but in general I'd say just try out the emoji you want to use and see if they work in your UI. Some will, some won't.

**Comment by cdupont** [comment]
So I need to choose my emojis based on trial and error?
Or is there a set of unicodes guaranteed to work on any terminal (Linux, Mac, windows...)?

**Comment by jtdaugherty** [comment]
I'm afraid your guess is right: trial and error may be necessary. There is sadly no guarantee about whether any given emoji will render correctly in every terminal emulator, and most will not render correctly.

**Comment by jtdaugherty** [comment]
I should point out that this is only a problem for terminal emulators, though; if you want to use emoji heavily in your application, then you might consider using a graphical UI framework instead of a terminal-based one. A graphical framework will not have any problem with emoji.

**Comment by cdupont** [comment]
Thanks, I like Brick so I think I will stick around for now!
It's also great for prototyping.
Latter if my game concept is validated I might consider to port it to a graphical platform (possibly Web oriented).
