### ISSUE TITLE
Normalize input directory for FileBrowser

### ISSUE THREAD

**Issue by kquick** [jtdaugherty/brick#387]
If the `FileBrowser` is initialized with a path of `/foo/bar/`, then everything appears to work correctly except if the `..` (parent dir) entry is selected.  Nothing appears to happen when it is selected, but when it is selected a second time then the `FileBrowser` moves to the parent directory as expected.

Closer inspection of the top line reveals that the first parent directory selection moved from `/foo/bar/` to `/foo/bar` due to the subtle ambiguity of directory v.s. file for trailing slashes.

To avoid this unexpected/awkward behavior, the input to the `FileBrowser` could be normalized  to remove any solo trailing slashes.

**Comment by jtdaugherty** [comment]
Fixed, thanks!
