### ISSUE TITLE
Cumulative attributes

### ISSUE THREAD

**Issue by cdupont** [jtdaugherty/brick#388]
Hello,
I have trouble working with attributes.
In my application, the various objects can have properties, such as "selected" or "paired". Those properties are independent and cumulative, i.e. you can be selected, paired, both or none. I wrote it like this:

```
w = withAttr (select <> paired) $ str "XXX"
select = attrName "Selected"
paired = attrName "Paired"
   
theMap :: AttrMap
theMap = attrMap 
  V.defAttr [(select, fg VA.blue), 
             (paired, VA.withStyle VA.defAttr VA.standout)] 
```

But this only display the XXX's as blue, not standout:

![image](https://user-images.githubusercontent.com/484033/189350691-d99e6604-5ba6-4ef5-9be9-fe858ed5e96a.png)

**Comment by jtdaugherty** [comment]
The expression `select <> paired` constructs a new attribute name rather than requesting a combination of attributes. (You can read more about that [here](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#how-attributes-work).)

I think what you'll need is just

```
w = withDefAttr select $ withDefAttr paired $ str "XXX"
```

The renderer will automatically merge the attributes for you.

**Comment by cdupont** [comment]
Thanks, it works!

**Comment by jtdaugherty** [comment]
By the way, another way to get what you want is to use the attribute structure to describe how you want merging to happen. For example:

```haskell
paired = attrName "Paired"
select = paired <> attrName "Selected"
```

By basing `select` on `paired`, whenever you used `select`, it will merge `select` with `paired`. Then in your drawing code you can skip all the `withDefAttr` calls and just do something like this:

```haskell
let addAttr = if selected then select else paired
in addAttr $ str "XXX"
```

If you are familiar with CSS, this is not that different from CSS style inheritance. In this example, `select` inherits from `paired`.

**Comment by cdupont** [comment]
I see, but in this case, it is possible to be selected with being paired?

**Comment by jtdaugherty** [comment]
Good question! No, it isn't, in fact. That example assumes the selection only ever happens on paired things. If you wanted them to be independent, you could use the first approach I posted.
