### ISSUE TITLE
new release to support base-4.17 (GHC 9.4)

### ISSUE THREAD

**Issue by frasertweedale** [jtdaugherty/brick#396]
https://github.com/jtdaugherty/brick/pull/391 added support for GHC 9.4 in git, but there was no release yet.
Could you please cut a new release and upload to hackage?

Thanks,
Fraser

**Comment by jtdaugherty** [comment]
Done! https://hackage.haskell.org/package/brick-1.2

**Comment by frasertweedale** [comment]
Thanks @jtdaugherty!
