### ISSUE TITLE
Difficulties upgrading 0.73 -> 1.1

### ISSUE THREAD

**Issue by AndreiUlmeyda** [jtdaugherty/brick#397]
Hi there, again. 'Hope you're doing well.

I am currently trying to migrate to the newest brick version and hit a bit of a roadblock due to my insufficient understanding of at least a few of the mechanisms involved.

In version 0.73 I've had several event handlers and some of them were down for some juicy IO action, [like ESA](https://en.wikipedia.org/wiki/Jupiter_Icy_Moons_Explorer).

Puns aside, could you provide guidance on how to properly write event handlers which perform IO?

What I've tried so far:

0.73 event handler
```
handleEvent :: AppState -> BrickEvent n e -> NextAppState
handleEvent currentState event
  | VtyEvent vtye <- event = handleVtyEvent vtye currentState
  | otherwise = continue currentState

handleVtyEvent :: Event -> AppState -> NextAppState
handleVtyEvent ArrowDown state = (continue . selectNextItem) state
handleVtyEvent ArrowRight state = continue =<< (liftIO . selectNextValue) state
```
with `AppState` being a self defined type and  `NextAppState` being a synonym for `EventM ResourceName (Next AppState)`.
Notice `selectNextValue :: AppState -> IO AppState` handled differently due to it performing IO stuff.

1.1 event handler
The relevant part for the migration is probably the change introduced in 1.0 where EventM got reworked.

I tried to read the example programs in order to get to grips with it. All the examples use lenses, which I am not too familiar with. I managed to get the normal event triggered state changes working by emulating the lens approach (modifying) and, later, using the mtl stuff directly (modify)
```
handleVtyEvent :: Event -> NextAppState
handleVtyEvent ArrowDown = modify selectPreviousItem
handleVtyEvent ArrowRight = (??? . modify) (??? . selectNextValue)
```
Where I've failed now, for longer than I'd like to admit, is to get the last line to work.

I've tried constructing an EventM directly while generously sprinkling 'lift' everywhere, but then GHC accused me of illegal use of the EventM constructor and called the friggin' cops on me. I am currently in hiding and am waiting for things to calm down out there. Please help, if you'd be so kind :')

**Comment by jtdaugherty** [comment]
Thanks for opening this! Would it be possible for you to link to the actual code affected here?

**Comment by jtdaugherty** [comment]
To answer your `liftIO` question, you'll need to get and put the state in separate steps as follows without using any of the lens API:
```haskell
handleEvent :: AppState -> BrickEvent n e -> EventM ResourceName (Next AppState)
handleEvent currentState event
  | VtyEvent vtye <- event = handleVtyEvent vtye currentState
  | otherwise = continue currentState

handleVtyEvent :: Event -> AppState -> EventM ResourceName (Next AppState)
handleVtyEvent ArrowDown state = (continue . selectNextItem) state
handleVtyEvent ArrowRight state = continue =<< (liftIO . selectNextValue) state
```
would become
```haskell
handleEvent :: BrickEvent n e -> EventM ResourceName AppState ()
handleEvent (VtyEvent e) = handleVtyEvent e
handleEvent _ = return ()

handleVtyEvent :: Event -> EventM ResourceName AppState ()
handleVtyEvent ArrowDown = modify selectNextItem
handleVtyEvent ArrowRight = do
    s <- get
    s' <- liftIO $ selectNextValue s
    put s
handleVtyEvent _ = return ()
```

**Comment by jtdaugherty** [comment]
If that's a common pattern then you could write e.g.
```haskell
modifyIO :: (s -> IO s) -> EventM n s ()
modifyIO f = do
    s <- get
    put =<< (liftIO $ f s)
```

**Comment by jtdaugherty** [comment]
And then you'd have something clean like
```haskell
handleVtyEvent :: Event -> EventM ResourceName AppState ()
handleVtyEvent ArrowDown = modify selectNextItem
handleVtyEvent ArrowRight = modifyIO selectNextValue
handleVtyEvent _ = return ()
```

**Comment by AndreiUlmeyda** [comment]
Hey there, sorry for being slow with example code. This

> ```haskell
> modifyIO :: (s -> IO s) -> EventM n s ()
> modifyIO f = do
>     s <- get
>     put =<< (liftIO $ f s)
> ```

is exactly what I was looking for. Everything works like a charm. Looks like I should finally go and learn about monad stacks/transformers. ^^'

Thank you, again. Have a nice day!

**Comment by jtdaugherty** [comment]
Okay, great! Let me know if I can help with anything else.
