### ISSUE TITLE
Multi-line markup

### ISSUE THREAD

**Issue by mitchellwrosen** [jtdaugherty/brick#41]
Hi, not sure if this behavior is intended...

```haskell
{-# LANGUAGE OverloadedStrings #-}

-- hi
-- there
main = simpleMain (txt "hi\nthere")

-- hi...
main = simpleMain (markup ("hi\nthere" @@ bg blue))
```

Multi-line markdown appears to just put an ellipsis where the first newline should go.

**Comment by jtdaugherty** [comment]
Thanks! You're right, that isn't the intended behavior. The ellipsis comes from vty not dealing with newlines, but the real problem is that the markup functions aren't multiline-aware.  I'll fix it in the next few days!
