### ISSUE TITLE
Terminal widget?

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#410]
Hi,

I have a question please.
Does Bricks have a Terminal Widget? If yes, where is it in the docs?
If no, could you please give some pointers on how would I impolement one myself? Using the Editor Widget perhaps?

Thanks.

**Comment by jtdaugherty** [comment]
Hi @refaelsh - no, Brick does not have a terminal widget. I don't think I can provide pointers for implementing a full terminal, but if you are just looking to get user input to execute commands, then yes, the `Editor` is a good place to start.

**Comment by refaelsh** [comment]
Got it. Thank you :-)
