### ISSUE TITLE
Impossible to position cursor at selected button in renderDialog

### ISSUE THREAD

**Issue by mlang** [jtdaugherty/brick#412]
Looking at the Dialog API, I don't see an obvious way to use putCursor
to indicate focus, as we have done for Forms for instance.
The reason is that neither the button specification nor the
renderDialog function does take a widget name.
So putCursor/showCursor can't be used as they would need a widget name.

Any ideas how to fix this without breaking the API too much?
Looks like Dialog is the last built-in widget of Brick which isn't
friendly to screen reader users.

**Comment by jtdaugherty** [comment]
I'll give it some thought!

**Comment by jtdaugherty** [comment]
I want to mention that the reason there is no focus API is because `Dialog` is intended to be for such simple use cases that it is intended to be a black box. I'll think about whether it would make sense to open up its API and add a notion of focus, but I suspect that really just amounts to implementing a new, more advanced `Dialog`-like thing.

**Comment by jtdaugherty** [comment]
I wrote up a patch to try to help with this issue on the `refactor/dialog-button-names` branch. Let me know what you think.

**Comment by mlang** [comment]
Yes, `dialogButtons :: [(String, n, a)]` is pretty much what I was thinking about.

**Comment by jtdaugherty** [comment]
Okay. Would you be willing to try out the new API in an application of yours and see if it meets your needs?

**Comment by mlang** [comment]
Running brick-dialog-demo is actually enough to confirm that this patch
would meet my needs.  The cursor nicely indicates which button is
currently selected.
I guess we assume a dialog is always modal? If so, this patch looks
great to me.

**Comment by jtdaugherty** [comment]
Okay, great! And yes, I'm assuming it's modal and I just pushed a patch to clarify that in the documentation. I'll merge the changes since they work for you. Thanks!

**Comment by jtdaugherty** [comment]
The changes are now released in `1.5`.
