### ISSUE TITLE
Some questions about the CustomEventDemo.hs

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#420]
Regarding this: https://github.com/jtdaugherty/brick/blob/master/programs/CustomEventDemo.hs.
On line 36, there is this thingy called `Counter`.
Sorry for the strange question, but where is it defined? I've scanned the entire file several times and I cant see it.

**Comment by jtdaugherty** [comment]
`Counter` is a data constructor for `CustomEvent` and is declared on [line 36](https://github.com/jtdaugherty/brick/blob/master/programs/CustomEventDemo.hs#L36).

**Comment by jtdaugherty** [comment]
In other words this is like any other declaration of data constructors like `data Foo = Bar | Baz | Stuff` where `Bar`, `Baz`, and `Stuff` are data constructors for `Foo`, just as `Nothing` and `Just` are data constructors for `Maybe`.

**Comment by refaelsh** [comment]
Yeap, I knew it was a stupid question. Sorry and thank you :-)

**Comment by jtdaugherty** [comment]
No problem, thanks for asking. I'm glad I could help.
