### ISSUE TITLE
Horizontally scrollable tabular list widget

### ISSUE THREAD

**Issue by amano-kenji** [jtdaugherty/brick#422]
I want help with implementing spreadsheet widget. I want it to be simple but functional.

A spreadsheet may or may not have a fixed header at the top. The header cannot be hidden by vertical scrolling.

Columns can have fixed widths or be as wide as the longest column content among all available rows. Maximum width for each column can be calculated and saved in the spreadsheet state whenever a new row is added or new rows are added.

If the last column doesn't outgrow the width of a viewport, I want an option to make it fill the remaining horizontal space greedily.

Each row can have a different number of lines.

I should be able to navigate cells by automatically scrolling the viewport horizontally. Optionally, I also want to manually scroll horizontally regardless of the selected column.

Since there can be millions of rows, it'd be beneficial to draw only visible rows.

How can I implement spreadsheet widget in a simple way? A simple tabular list demo gets close, so I think spreadsheet UI doesn't have to be complex.

**Comment by jtdaugherty** [comment]
> How can I implement spreadsheet widget in a simple way?

What counts as simple in your case? I doubt the implementation could possibly be simple, even if the UI that the user uses *looks* that way.

**Comment by jtdaugherty** [comment]
My suggestion is to start with the tabular list demo to build your spreadsheet, and check in here as you run into difficulties. I'm not really in a position to just tell you how to implement the whole thing.

**Comment by amano-kenji** [comment]
Simple because it's conceptually simple and doesn't have to account for all use cases.

A simple base that can satisfy most use cases.

**Comment by amano-kenji** [comment]
Is it difficult to render only visible rows that have variable numbers of lines? Or, is it already easy?

**Comment by jtdaugherty** [comment]
It sounds like it would be best if we don't spend time debating what "simple" means and just stick to the implementation issues. Have you attempted to start working on this? If so, have you run into specific issues that I could help with?

**Comment by amano-kenji** [comment]
I will start implementing it today. I just woke up.

What I'm trying to implement is basically tabular list demo with fixed-width columns or columns as wide as longest column content among all available or visible rows. When I navigate cell by cell, horizontal scrolling should be done automatically to show the chosen cells. Manual horizontal scrolling is also considered but may not necessarily be implemented if it's too complex. A column may span multiple lines if the content has line breaks.

I think it's good to assume one row spans one line anyway and draw as many rows as the number of lines in the viewport plus a few more. That's my intuition. But, I will have to read the implementations of table and list to actually guage what it'll take to implement a horizontally scrollable version of tabular list.

**Comment by amano-kenji** [comment]
It turns out that I needed a horizontally scrollable tabular list widget with cell-by-cell navigation.

A spreadsheet can have indefinite numbers of columns with or without variable numbers of lines for different rows.
I'm not actually going to implement a spreadsheet. I want to interact with databases in UI.

My tabular lists will have fixed numbers of columns. The list widget can only handle a fixed number of rows for every row.

It seems I can build on top of table and list to get a horizontally scrollable tabular list widget.

**Comment by jtdaugherty** [comment]
> It seems I can combine table and viewport and list to get a horizontally scrollable tabular list widget.

For what it's worth, you might need to fake horizontal scrolling yourself rather than use a horizontal viewport. Embedding a viewport in the list would work just fine, but you'd need a *per-item* viewport to make it work and you'd need to scroll them *all* horizontally to get the appearance you probably want. If you're using the tabular list demo as a basis for your work, since that implementation already needs to declare and use the width of each table column, you could use that information and track which "columns" are visible and show only a subset yourself to emulate a scrollable viewport.

**Comment by amano-kenji** [comment]
I used my internal intuition really hard today. Since I didn't have any finished concept I could iterate on in the code, I had to iterate scrolling concepts in my mind. I think I can put a list inside a horizontally scrollable viewport and manually calculate scrolling position.

I came up with the following data structure and the following rules. The rules are still subject to changes because I'm formulating a new unproven idea.

```
data ScrollAnchor = Left Word | Right Word

data GenericTabularList n t e = {
  list :: GenericList n t e
, curCol :: Word
, scrollAnchor :: ScrollAnchor
}
```

* The initial value for scrollAnchor should be `Left 0`.
* If scrollAnchor is `Left n`, the viewport shows nth column on the leftmost position.
* If scrollAnchor is `Right n`, the viewport shows nth column on the rightmost position.
* If the current column goes beyond the viewport by increasing curCol by one, `Left n` becomes `Right curCol+1`.
* If the current column goes beyond the viewport by pressing `Ctrl+PgDown`, `Left n` becomes `Left curCol+1`.
* If the current column goes beyond the viewport by dereasing curCol by one, `Left n` becomes `Left n-1`
* If the current column goes beyond the viewport by pressing `Ctrl+PgUp`, `Left n` becomes `Right n-1`
* If the viewport size becomes smaller than the right side of the current column, `Left n` becomes `Right curCol`.
* If the viewport size becomes samller than the left side of the current column, `Right n` becomes `Left curCol`.

**Comment by amano-kenji** [comment]
I largely figured out an efficient column drawing algorithm. I need to figure out containers for columns and column widths.

Do you know good data structures for columns and column widths?

**Comment by jtdaugherty** [comment]
> Do you know good data structures for columns and column widths?

I can't provide an answer without more information. What is a "column"? What kinds of operations do you need to perform on it?

**Comment by amano-kenji** [comment]
A column contains either text or anything that can be converted to text.

A row can be represented by either a list of column texts or a product data type that can be converted to a list of column texts.

A product data type like

```
data Row = Row Text Text Text
```

can be converted to something like `Vector Text`. But, the length of such a list should match the length of column widths.

For interacting with databases, Vector suffices for a list of column texts and a list of column widths. Even `[]` suffices for a list of column texts from a database row.

If anyone wants to use a tabular list to construct a spreadsheet, an efficient assignment to multiple columns is going to be necessary. I guess `Vector` got that covered, too?

**Comment by amano-kenji** [comment]
For sparsely populated rows and columns in a spreadsheet, one can use `Map Word (Map Word e)` for rows and `Map Word Word` for column widths. If `Map Word Word` returns `Nothing`, then a default column width should be used.

For a product data type, I think I will just use something like

```
class Columns a where
  intoColumns :: a -> Vector Text

instance Columns Row where
  intoColumns (Row a b c) = Data.Vector.fromList [a, b, c]
```

to display a product data type for a database table. I just need to figure out how to cache the result of intoColumns so that `intoColumns` is not called whenever rows need to be rendered.

**Comment by amano-kenji** [comment]
I actually have a question that I may or may not answer myself, given enough time, but you can help accelerate the process.

When rendering a column, I want to get the text content from a product data type or a spreadsheet data type.
A tabular list doesn't need to know how to manipulate data types behind columns. Manipulating data types behind tabular list would be a responsibility for application event handler. Tabular list only needs to get the text content for each column.

I was thinking of implementing something like this for getting the text content for each column.

```
class ShowColumn a where
  showColumn :: Word -> a -> Text
  -- Word is the column width for the given column. It is used to truncate text in order to fit the column width.
  -- a is the product data type or the spreadsheet data type.
```

Do you think this is good enough? Do you suggest any better approach? After studying List functions, I may change my mind.

**Comment by jtdaugherty** [comment]
The interface provided in the type class seems like it could work well enough. My only suggestion is to use a record type to carry the `showColumn` and `columnWidth` functions rather than a type class. Using a type class this way is very likely to create headaches later on when `RowInfo` constraints need to be captured or existentially quantified over. In those cases it becomes a huge pain to carry around a value whose type you don't know when you need to also carry a `RowInfo` constraint. The solution is easy: the type class can be converted to a record type declaration in a straightforward way:
```haskell
data RowInfo a =
    RowInfo { showColumn :: ColumnIndex -> ColumnWidth -> a -> Maybe String
            , columnWidth :: ColumnIndex -> a -> Maybe Word
            }
```
and then carry around a `RowInfo a` as part of whatever state is already in terms of `a`. This approach basically does what the compiler does (manufactures a record of functions) and stores it explicitly rather than implicitly, but it has the additional benefit that you can treat the record type as malleable business logic rather than a *universal behavior of the type* which it may very well not be, depending on the application context.

**Comment by amano-kenji** [comment]
Should `GenericTabularList` carry `RowInfo a`? Or, should `RowInfo a` be supplied to functions?

**Comment by jtdaugherty** [comment]
I suspect the best place for it is in `GenericTabularList` itself. Otherwise you run the risk of needing to pass the `RowInfo a` as an argument to one or more list-related functions, which could be cumbersome.

**Comment by amano-kenji** [comment]
Does vertical border between columns occupy extra space I need to worry about in the column drawing alogirhtm?

**Comment by jtdaugherty** [comment]
If you want to draw vertical borders, then they'd take up one terminal column's worth of width (assuming you use `vBorder`). That means that the total width of your `N` visible columns would be `(N-1) + SUM(N_i)` where `N_i` is the width of the contents of column `i`.

**Comment by amano-kenji** [comment]
By the way, beam was bragging about its extensive use of typeclasses by saying beam uses finally tagless encoding which I don't understand exactly.

What do you know about finally tagless encoding? Is it something I need to worry about?

**Comment by jtdaugherty** [comment]
I've only heard that term. I couldn't tell you anything about it.

**Comment by amano-kenji** [comment]
```
type ColumnIndex = Word
type ColumnWidth = Word
data RowHeader =
  RowHeader { getHeader :: ColumnIndex -> Maybe String, width :: Word, newWidth :: Maybe ColumnWidth }
data ColHeader = ColHeader { getHeader :: ColumnIndex -> Maybe String }

data GenericTabularList n t e = {
  list :: GenericList n t e
, curCol :: Word
, columnWidths :: t Word
, rowHeader :: Maybe RowHeader
, colHeader :: Maybe ColHeader
, newColumnWidths :: Map ColumnIndex ColumnWidth
}
```

This accounts for column header at the top and row header at the left.

Users of GenericTabularList are given an option to specify `RowHeader.newWidth` and `newColumnWidths` as the tabular list is rendered.

This means after rendering tabular list once, if a user specified new widths for row header or columns, the tabular list has to be rendered again. If new widths for columns are again demanded, then the tabular list is rendered again.

This means the tabular list can be rendered two or three times. Maybe even more times....

What do you think?

**Comment by amano-kenji** [comment]
Here's a generalized pseudo-code for GenericTabularList.

This accounts for column header at the top and row header at the left. Row header, column header, and column widths are generated by `IndexedContents`. `IndexedContents` is flexible enough for a spreadsheet and an interface to database table.

```
type Index = Word
type Width = Word
type Height = Word

data IndexedContents e = {
, get :: Index -> Maybe e
, set :: Index -> e -> IndexedContents e
}

data RowHeader = RowHeader
  { contents :: IndexedContents String, width :: Width, newWidth :: Maybe Width }

data RowInfo e = RowInfo {
  showColumn :: Index -> Width -> e -> Maybe String
, columnWidth :: Index -> e -> Maybe Width
}

data GenericTabularList n t e = {
  list :: GenericList n t e
, rowInfo :: RowInfo e
, curCol :: Index
, columnWidths :: IndexedContents Width
, newColumnWidths :: Map Index Width
, colHeader :: Maybe (IndexedContents String)
, rowHeader :: Maybe RowHeader
}

drawTabularList :: GenericTabularLis n t e -> ... -> Widget n
-- These functions are called by drawTabularList
-- drawRowHeader, drawColHeader, and drawColumn have default implementations,
-- but users can pass their own implementations to drawTabularList
drawRowHeader :: Index -> EventM n (GenericTabularList n t e) ()
drawColHeader :: Index -> EventM n (GenericTabularList n t e) ()
drawColumn :: e -> Index -> EventM n (GenericTabularList n t e) ()
-- These functions can be called by drawRowHeader, drawColHeader, and drawColumn
-- setRowHeaderWidth sets rowHeader.newWidth
setRowHeaderWidth :: Width -> EventM n (GenericTabularList n t e) ()
-- setColumnWidth inserts (Index, Width) into newColumnWidth
setColumnWidth :: Index -> Width -> EventM n (GenericTabularList n t e) ()
```

If setRowHeaderWidth and setColumnWidth were called in user's implementations of drawRowHeader, drawColHeader, or drawColumn, then GenericTabularList is drawn again. This means GenericTabularList can be drawn multiple times before
being shown on screen.

Do you suggest any better interface than what I just wrote above? I think the interface can benefit from some improvements.

**Comment by jtdaugherty** [comment]
> Do you suggest any better interface than what I just wrote above? I think IndexedContents is ugly. Also, storing new widths in GenericTabularList temporarily looks a bit ugly. The code is really just a rough draft.

At this point I really couldn't say whether it could be improved. In my experience, designs like this almost always change when you get down to actually writing the application, and it's only then that you find out what your design's flaws or ergonomic issues are. And I haven't been following along with your design here because I would rather help with library issues as they arise rather than helping you design your application from the ground up. That's a lot of work! :)

**Comment by amano-kenji** [comment]
Okay. I will come back when I have issues with brick library.

Can you see this tabular list widget in brick library when it's finished? Tabular data like SQL database table and CSV are common.

**Comment by jtdaugherty** [comment]
> Can you see this tabular list widget in brick library when it's finished?

No, but it seems to me like the sort of thing that would work really well as a third-party extension package similar to how [brick-filetree](https://github.com/ChrisPenner/brick-filetree) was published!

**Comment by amano-kenji** [comment]
As I was writing actual code, I discovered that EventM doesn't have access to viewport or widget size and RenderM can't modify application state.

I was going to update `data ScrollAnchor = AnchoredLeft n | AnchoredRight n` according to viewport size, current value of scroll anchor, and current column. Obviously, RenderM can calculate a new value for scroll anchor, but can't assign the new scroll anchor to application state. EventM is able to modify application state but cannot calculate scroll anchor.

This means I am stuck with stateless rendering?

Without scroll anchor, the next thing I can think of is to save calculated offsets for all columns whenever column widths are modified. Calculating column offset every time is going to be inefficient.

Is there anything I can take advantage of in brick's design to make the rendering efficient?

**Comment by jtdaugherty** [comment]
> As I was writing actual code, I discovered that EventM doesn't have access to viewport or widget size and RenderM can't modify application state.

`EventM` can get viewport info with [lookupViewport](https://hackage.haskell.org/package/brick-1.5/docs/Brick-Main.html#v:lookupViewport) but that's only *as of the last rendering*. And yes, `RenderM` cannot modify the application state by design.

> This means I am stuck with stateless rendering?

This is true and is by design. I hope this is not a surprise; if it isn't clear in the user guide then I'd be happy to make edits to make this clearer.

> Is there anything I can take advantage of in brick's design to make the rendering more efficient than saving calculated offsets for all columns after changes to column widths?

I don't really know much about the approach you have been developing, but I would recommend you take a close look at the `List` implementation. That has some detailed comments that talk about how it makes use of Brick's built-in render-time viewport states while still maintaining efficiency. You might be able to do something similar in your use case.

**Comment by amano-kenji** [comment]
> EventM can get viewport info with [lookupViewport](https://hackage.haskell.org/package/brick-1.5/docs/Brick-Main.html#v:lookupViewport) but that's only as of the last rendering.

Does this mean lookupViewport can return an outdated viewport size in vty resize event and possibly other events? This can result in graphical glitches if I rely on lookupViewport for scrolling calculation.

> This is true and is by design. I hope this is not a surprise; if it isn't clear in the user guide then I'd be happy to make edits to make this clearer.

I think it's a good idea to explain brick's high-level design concepts.

> That has some detailed comments that talk about how it makes use of Brick's built-in render-time viewport states while still maintaining efficiency. You might be able to do something similar in your use case.

`drawListElements` can have efficiency in offset calculation because the height for every list element is fixed. The width for any column can be different from that of any other. I can have something like

```
type Width = Word
type ColIndex = Word
type Offset = Word

data GenericTabularList n t e = TabularList {
  ...
-- (3, 0), (5, 3), (3, 8), (5, 11), (3, 16), ...
, columnWidths :: Seq (Width, Offset)
}

-- Its time complexity is O(n)
createColumnWidths :: [Width] -> Seq (Width, Offset)

-- This calculates offsets again after setting column widths in certain columns.
-- Time complexity seems less than O(n).
-- Assuming that microsoft excel has 2^14 = 16384 columns and tries not to change column widths
-- automatically, O(n) is still fast enough. For a few columns that change their widths often to fit in
-- viewport, O(n) is good enough.
setColumnWidths :: [(ColIndex, Width)] -> Seq (Width, Offset) -> Seq (Width, Offset)
```

**Comment by jtdaugherty** [comment]
> Does this mean lookupViewport can return an outdated viewport size in vty resize event and possibly other events? This can result in graphical glitches if I rely on lookupViewport for scrolling calculation.

Only "outdated" in the sense that it reflects what is currently on the screen, *not* what will happen in the next redraw. Basically, brick viewports are managed by the renderer, *not* by the user application. You can ask that the renderer scroll a viewport, but you don't get access to the underlying book-keeping.

> I think it's a good idea to explain brick's high-level design concepts.

Given that the user guide is many tens of pages doing exactly this, I think I have this covered. But if you found something in the user guide or Haddock docs that was confusing w.r.t. rendering being a pure function, please let me know and I'll do some editing.

> drawListElements can have efficiency in offset calculation because the height for every list element is fixed. The width for any column can be different from that of any other. If I can't calculate scroll anchor in EventM, I can still calculate scroll offsets in EventM. The cost of calculating scroll offsets for the first time and after changing column widths is O(n).

Calculating scrolling yourself outside of `RenderM` is just not going to work and is not how the library is designed. I directed you to the `List` code so you could begin to understand this.

> O(n) is probably good enough because the time cost is O(n) only when column widths change, and microsoft excel tries not to automatically change the widths of some of its 2^14 = 16384 columns. For a few columns that have to fit inside viewport, O(n) is nothing. I think sc-im's 702 columns are numerous enough. If you need more columns, you are probably doing something wrong and should simplify your data model.

For what it's worth, while I understand the importance of performance considerations, I think worrying about it now is premature. I don't see enough evidence that you understand the library and how to use it, so I think focusing on performance will just not be very productive. I think your mental model of performance is not going to be correct until you understand how the library works, i.e. how the renderer and its scrolling viewports can be used. As part of that, I consider it an *open question* as to whether Brick can even be made to support the kind of application that you want to build! It may turn out that even with a deep understanding of Brick, this application will either not be possible to build or will require some Brick hacking to support. That's why I keep asking you to attempt an implementation: so we can figure out what issues come up and then I can determine whether those are a consequence of you not understanding, a consequence of the library design, a consequence of a missing library feature, etc.

**Comment by amano-kenji** [comment]
> But if you found something in the user guide or Haddock docs that was confusing w.r.t. rendering being a pure function

I don't think the user guide explicitly tells anyone that RenderM cannot modify application state. But, reading the type of RenderM led to understanding that RenderM is pure.

**Comment by jtdaugherty** [comment]
> But, reading the type of RenderM led to understanding that RenderM is pure. I just felt stupid for designing a widget with an assumption that RenderM could modify application state.

I see, sorry to hear it. It's true that the type of `RenderM` can be understood not to modify the state at least because there is no application state type in the type signature; if `RenderM` was parameterized over the state type, that might be a clue that modification was possible (although even then you'd still need to look at the type classes that `RenderM` implemented -- such as `MonadState` -- to figure out whether modification was possible, and that might or might not be exposed as part of the public API).

**Comment by jtdaugherty** [comment]
Also, the other evidence for this, in case it helps, is that the only way to use the application state to draw is via the `App`'s pure `draw` function, which produces only a `Widget n` (which is just a `RenderM` computation). The fact that it does not also produce an `s` is a clue that it cannot modify the state. (It could modify the `s` it was given, but it'd never get returned, thus no modification.)

**Comment by jtdaugherty** [comment]
> It's true that the type of RenderM can be understood not to modify the state at least because there is no application state type in the type signature

Also, for what it's worth, this clue extends to the type `Widget n`, which can be understood to have nothing to do with any application state simply because no type is mentioned.

**Comment by amano-kenji** [comment]
I decided that calculating row header width and column width is not the responsibility of tabular list widget.
Calculating column widths doesn't require knowledge of possibly visible list indices.
However, adjusting row header width as a user goes up and down a list requires knowledge of possibly visible list indices.

This can be calculated by just dividing terminal's height by the height of each list element, but knowing viewport height makes it a bit more performant.

Programmers who use tabular list widget can independently develop a function to calculate possibly visible element indices, but that's not very convenient.

Should my tabular list widget provide a function that calcualtes possibly visible list indices with viewport height and list item height? Or, should brick's List module provide this?

**Comment by amano-kenji** [comment]
People may want to calculate visible row headers in EventM and set row header width based on visible row headers. For example, spreadsheet softwares show row numbers in row headers. Column width calculation doesn't need viewport information in EventM in all envisioned use cases. Dynamic column width calculation based on real viewport width may happen in RenderM for use cases that don't involve horizontal scrolling.

Is there a way to know whether lookupViewport returns outdated viewport information due to resize? Should I just set `outdated` value in my application state in a resize event? Or, should I just divide terminal height by list item height to calculate possibly visible row headers? I could get terminal height with vty in ghci.

**Comment by amano-kenji** [comment]
I finished fleshing out MixedTabularList and GridTabularList. In particular, GridTabularList's stateless scroll calculation algorithm is tiny and fast and looks absolutely beautiful. MixedTabularList is just a non-scrollable list with each row having one or more columns.

Calculation of column widths and scrolling information is only done once for each rendering and not repeated for each row. Thus, it is going to be fast.

I think it is going to crush microsoft excel in terms of rendering performance.

I just have to finish writing demos for two tabular lists and documentation. Before writing demos, I don't know whether they actually work.

**Comment by amano-kenji** [comment]
By the way, is the only way to force a specific width for a widget `hLimit width (a horizontally greedy widget)`?

I'm trying to minimize nested widgets for performance. Maybe, I'm dabbling with premature optimization.

**Comment by jtdaugherty** [comment]
> By the way, is the only way to force a specific width for a widget hLimit width (a horizontally greedy widget)?

I'd say it's certainly the easiest and best way. Why do you ask?

**Comment by amano-kenji** [comment]
> I'd say it's certainly the easiest and best way. Why do you ask?

I was trying to find a faster way than `hLimit w (Greedy Widget)`. But, I think it's a premature optimization.

By the way, I want to give some columns fixed( percentage) widths and hide some of them automatically if the viewport is too narrow to show them. Can brick do it natively? Or, is it something that users have to calculate in their own applications?

**Comment by jtdaugherty** [comment]
> I was trying to find a faster way than hLimit w (Greedy Widget). But, I think it's a premature optimization.

Do you mean faster as in "performance"? Or "ease of use of the API"? But either way, I would say it's not premature, it's just the wrong level of performance to worry about. (Not a first-order term in your performance equation, if you will.)

> I want to give some columns fixed( percentage) widths and hide some of them automatically if the viewport is too narrow to show them. Can brick do it natively?

That's something that could only be done by writing a custom widget and using the rendering context to determine which of your columns could be rendered. But I could imagine it having an API like `percentWidths :: [(Widget n, Int)] -> Widget n` that behaves like `hBox` but is given a list of things to draw and their percentages.

**Comment by amano-kenji** [comment]
Okay, either I come up with a generalized column width calculation algorithm, or users come with their own.

**Comment by amano-kenji** [comment]
MixedTabularList is complete.

The issue is with GridTabularList.

![2023-02-01 14:36:11](https://user-images.githubusercontent.com/106365348/215960593-08c37e5b-5773-4a32-a4a4-2dcbc84c1014.png)
![2023-02-01 14:36:24](https://user-images.githubusercontent.com/106365348/215960597-3c967635-8b73-4d62-90f7-571c47e37a75.png)
![2023-02-01 14:36:33](https://user-images.githubusercontent.com/106365348/215960601-6a910f74-75e9-40d5-b8b3-a7aaf1d2a820.png)
![2023-02-01 14:36:39](https://user-images.githubusercontent.com/106365348/215960606-9d300233-9554-4301-aa33-a84f15b8ea28.png)

Each row is cropped before `translateBy` is applied. Here's the function that draws column headers or row columns after drawing row header.

```haskell
renderColumns ::
  GridTabularList n row cell rowH colH -> VisibleColumns -> (ColumnIndex -> Width -> Widget n) -> Widget n
renderColumns l vCs dC = Widget Greedy Fixed $ do
  c <- getContext
  let curCol = l ^. #currentColumn
      cWs = l ^. #widths % #row
  render $ case vCs of
    NoColumn -> emptyWidget
    CurrentColumn -> dC curCol $ c M.^. availWidthL
    AnchoredLeft right -> hBox $ zipWith dC [0..] $ toList $ S.take (right+1) cWs
    MiddleColumns {..} -> translateBy (Location (offset, 0)) $
      hBox $ zipWith dC [left..] $ toList $ S.take (right-left+1) $ S.drop left cWs
    AnchoredRight {..} -> translateBy (Location (offset, 0)) $
      hBox $ zipWith dC [left..] $ toList $ S.drop left cWs
```

Relevant columns are given to `hBox` which resides in `Widget Greedy Fixed`. How can I prevent cropping before `translateBy`?

**Comment by jtdaugherty** [comment]
> EvKey (KChar 'h') [MCtrl] was ignored.

C-h is equivalent to backspace, so it is not ignored, just reported as Backspace.

I can't answer your question in item (1) because I don't understand what you're talking about. I'd probably need to see a screenshot of what you're doing as well as the code in question.

As for (3), please open a new ticket about that.

**Comment by amano-kenji** [comment]
The code is

```haskell
renderColumns ::
  GridTabularList n row cell rowH colH -> VisibleColumns -> (ColumnIndex -> Width -> Widget n) -> Widget n
renderColumns l vCs dC = Widget Greedy Fixed $ do
  c <- getContext
  let cWs = l ^. #widths % #row
      iH = l ^. #list % #listItemHeight
  render $ case vCs of
    NoColumn -> emptyWidget
    CurrentColumn -> dC (l ^. #currentColumn) $ c M.^. availWidthL
    AnchoredLeft right -> hBox $ zipWith dC [0..] $ toList $ S.take (right+1) cWs
    MiddleColumns {..} -> cropLeftBy offset $ setAvailableSize (totalWidth, iH) $
      hBox $ zipWith dC [left..] $ toList $ S.take (right-left+1) $ S.drop left cWs
    AnchoredRight {..} -> cropLeftBy offset $ setAvailableSize (totalWidth, iH) $
      hBox $ zipWith dC [left..] $ toList $ S.drop left cWs
```

The problematic part is `MiddleColumns` and `AnchoredRight`. If I eliminate `setAvailableSize`, I get this.

![2023-02-02 07:47:23](https://user-images.githubusercontent.com/106365348/216183327-e2e1b9e7-be16-40ef-ba8d-66d63453f6cf.png)
![2023-02-02 07:47:31](https://user-images.githubusercontent.com/106365348/216183339-834e5e1b-e74e-4c8a-8883-c52b4f51e2fb.png)
![2023-02-02 07:47:41](https://user-images.githubusercontent.com/106365348/216183344-5882b94b-30e6-4d49-8034-665061eb127f.png)

With `setAvailableSize`, I get this.

![2023-02-02 07:48:24](https://user-images.githubusercontent.com/106365348/216183346-66789ba5-6a4a-4344-ab83-1555ed18cbca.png)
![2023-02-02 07:48:31](https://user-images.githubusercontent.com/106365348/216183349-158540cb-5d88-4852-9f57-2d1492daedd0.png)

Without `setAvailableSize`, the columns get cropped at the right side before they reach `cropLeftBy`.

**Comment by amano-kenji** [comment]
I think the tabular list problem is solved. It's time to open a new issue.
