### ISSUE TITLE
Requesting discussion group in github or somewhere else.

### ISSUE THREAD

**Issue by amano-kenji** [jtdaugherty/brick#424]
I know there is https://groups.google.com/g/brick-users

However, google has been becoming increasingly totalitarian toward its users. Even logging in google is becoming more difficult. I was once locked out of my own google account temporarily because I used VPN although I didn't do anything wrong.

At this point, I relegate all google activities to google chrome browser where I sometimes watch useless youtube videos. In other web browsers, I don't log into google. Google has a documented history of voluntarily reporting user search queries to police. So, I don't watch videos about social issues on google chrome. I use invidious instances as a youtube proxy for watching videos about social issues.

Compared to google, using github is still okay despite its ownership by microsoft. I'd appreciate a discussion forum in this repository or somewhere else outside github.

I am not comfortable with using google services.

**Comment by jtdaugherty** [comment]
Can you share a bit more about what you're hoping to get out of a discussion forum for brick?

**Comment by amano-kenji** [comment]
Questions that are not really issues. Anything that is not an issue. Basically, anything you would do in the google group.

**Comment by jtdaugherty** [comment]
Okay. I've enabled the Discussions feature on this repository.
