### ISSUE TITLE
I can't zoom without template haskell.

### ISSUE THREAD

**Issue by amano-kenji** [jtdaugherty/brick#430]
I use `optics` because its built-in generic lenses are faster during compilation time than those from `generic-lens`.

I have this

```
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedLabels #-}

import Optics.Extra ((^.), (%), zoom)
import qualified Brick.Widgets.List as L

data MixedTabularList n t row rowKind cell rowH colH = MixedTabularList {
  list :: L.GenericList n t row
, columnWidths :: MixedColumnWidths n row rowKind
, contents :: MixedContents n row cell rowH colH
} deriving Generic

...

handleMixedListEvent :: (Foldable t, L.Splittable t, Ord n) =>
  Event -> EventM n (MixedTabularList n t row rowKind cell rowH colH) ()
handleMixedListEvent e = do
  zoom #list (L.handleListEvent e)
```

The error I see is

```
Diagnostics:
1. • Could not deduce (Optics.Zoom.Zoom
                         (EventM n (L.GenericList n t row))
                         (EventM n (MixedTabularList n t row rowKind cell rowH colH))
                         (L.GenericList n t row)
                         (MixedTabularList n t row rowKind cell rowH colH))
       arising from a use of ‘zoom’
     from the context: (Foldable t, L.Splittable t, Ord n)
       bound by the type signature for:
                  handleMixedListEvent :: forall (t :: * -> *) n row rowKind cell
                                                 rowH colH.
                                          (Foldable t, L.Splittable t, Ord n) =>
                                          Event
                                          -> EventM
                                               n (MixedTabularList n t row rowKind cell rowH colH) ()
       at /data/git/mine/brick-tabular-list/src/Brick/Widgets/TabularList/Mixed.hs:(108,1)-(109,72)
   • In a stmt of a 'do' block: zoom #list (L.handleListEvent e)
     In the expression: do zoom #list (L.handleListEvent e)
     In an equation for ‘handleMixedListEvent’:
         handleMixedListEvent e = do zoom #list (L.handleListEvent e)
```

It seems this error is caused because `EventM` doesn't have Generic instance. I couldn't derive an orphan Generic instance for EventM because EventM data constructor is not exported from brick.

I don't know how to do this without zoom.

**Comment by jtdaugherty** [comment]
Do you get the same result if you use the `zoom` re-exported by `Brick.Types`?

**Comment by jtdaugherty** [comment]
Also, for what it's worth, if for some reason `zoom` isn't working out, you can do things manually with `Brick.Types.nestEventM`.

But I think the type error you are getting is because `EventM` doesn't implement the `Zoom` typeclass that you're using; it implements `Zoom` from `microlens-mtl`, which is the lens API you should use when using `brick` for best compatibility.

**Comment by amano-kenji** [comment]
After adding `generic-lens` to cabal and `import Data.Generics.Labels` to the source file,

```
handleMixedListEvent :: (Foldable t, L.Splittable t, Ord n) =>
  Event -> EventM n (MixedTabularList n t row rowKind cell rowH colH) ()
handleMixedListEvent e = do
  zoom #list (L.handleListEvent e)
```
works fine. I used brick's zoom instead of optics' zoom. `#list` is a generic lens generated by generic-lens through `Data.Generics.Labels`.

**Comment by amano-kenji** [comment]
Optics.Zoom doesn't seem to support Generic.

My research result is that if EventM data constructor is exported from brick, I can derive an orphan Optics.Zoom instance for EventM via StandaloneDeriving and GeneralizedNewtypeDeriving or DerivingVia.

But, generic-lens also works.

**Comment by amano-kenji** [comment]
Between `nestEventM(')` and `generic-lens`, I think the issue can be seen as solved.
