### ISSUE TITLE
I think I discovered a broken link in the docs

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#432]
I think I discovered a broken link in the docs.
1. Go here: https://hackage.haskell.org/package/brick-1.6/docs/Brick-Widgets-Edit.html#v:applyEdit 
2. In the `The Zipper editing transformation to apply` line, click the `Zipper` link -> it goes to the wrong place.

**Comment by jtdaugherty** [comment]
Fixed, thanks!
