### ISSUE TITLE
Optics support

### ISSUE THREAD

**Issue by amano-kenji** [jtdaugherty/brick#438]
optics-core is a small package that implements an alternative interface to lens.

Optics-core's generic optics with overloaded labels are faster during compilation time than generic-lens.

Generic lens and generic optics require Generic instance.

In particular, `Context n` lacks Generic instance. Deriving Generic instance for `Context n` should not be a problem.

Another issue is with zoom. I can use generic-lens to avoid using template haskell for just zoom. However, it would be nice to support Optics.Zoom from optics-extra package for EventM. One issue with supporting Optics.Zoom is the additional dependency on optics-extra.

optics-core is the smallest package. optics-extra adds some things on top of optics-core. optics adds even more things to optics-extra.

You decide whether you want dependency on optics-extra.

**Comment by jtdaugherty** [comment]
> optics-core is a small package that implements an alternative interface to lens.

So is `microlens`, which is what `brick` uses.

> Optics-core's generic optics with overloaded labels are faster during compilation time than generic-lens.

Why are you mentioning `generic-lens` here? Brick doesn't use it, so I don't understand your comparison.

> Another issue is with zoom.

Microlens and Brick already work together to support `zoom` from microlens. Is there some reason why that isn't working for you?

**Comment by amano-kenji** [comment]
I like using generic overloaded labels instead of template haskell. Generic lenses and generic optics make field naming easier for my data structures because they don't clutter top-level namespace. Template haskell has to generate top-level names. My plan is to migrate to `NoFieldSelectors` once I get GHC 9.2.1 and above in order to avoid name clashes in the top-level namespace.

I already use generic-lens in my tabular list widgets to create generic lenses out of my data structures with Generic instance. I already pass generic lenses to zoom exported by brick.

However, I already use optics-core because generic optics compile faster than generic lenses. Generic overloaded label lenses create orphan instances which can clash with overloaded labels created by https://hackage.haskell.org/package/named. Generic optics don't create orphan instances that clas with named and other packages because optics are newtypes.

I ended up using microlens, generic-lens, and optics-core in my widgets. While generic-lens works now, I prefer using either generic-lens and microlens or optics.

**Comment by amano-kenji** [comment]
I can be content with just adding Generic instance on `Context n` although I prefer using either generic-lens or optics, but not both.

**Comment by jtdaugherty** [comment]
Okay. I don't see a response to my question about `zoom` in your comment above, though.

I understand that adding a `Generic` instance to `Context` would help, but `Context` already has lenses that are part of the public API. Deriving more lenses from that using the Generic instance makes Generic part of the public API, and I'm not sure I want to encourage that. The Context type, while exposed out of necessity, is part of the internals of the renderer. I'd like you to expose an API that works for the library as-is, rather than making its API extensible in ways I don't intend. I understand that you prefer another lens package, but I don't find the reasoning compelling enough to add a Generic instance to the data type.

**Comment by amano-kenji** [comment]
After thinking for a while, I also concluded that Generic instance on Context is not going to be very helpful.

I guess I will just get used to using both generic-lens and optics.
