### ISSUE TITLE
renderBox crops the contents to the context width minus one.

### ISSUE THREAD

**Issue by amano-kenji** [jtdaugherty/brick#439]
That's why the last visible column of hBox, vBox, and their variants is blank.

I worked around this issue with

```
Widget Greedy Fixed $ do
  c <- getContext
  let iH = l ^. #list % #listItemHeight
  render $ setAvailableSize (c^.availWidthL+1, iH) $ hBox ...
```

**Comment by amano-kenji** [comment]
It seems that the issue doesn't come from renderBox or cropResultToContext.

Context width itself is one character less than what it should be.

**Comment by amano-kenji** [comment]
This turned out to be a mistake in my codebase.

With
```
padRight Max widget <+> str " "
```
`widget` would have one less character for the context width.

**Comment by jtdaugherty** [comment]
> padRight Max widget <+> str " "
>
> widget would have one less character for the context width.

That's right. The reasons are because:

* `str` is `Fixed` horizontally.
* `padRight Max` is `Greedy` horizontally.
* `<+>` (`hBox`) renders `str` first and then allocates the remaining width to `padRight Max widget`, resulting in that getting one less column than the `hBox` was given.

**Comment by amano-kenji** [comment]
I replaced all references to `hLimit` with `setAvailableWidth`, and the problem was solved.
