### ISSUE TITLE
Constructing an Editor widget from [(String, String)]

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#440]
I need an Editor of `[(String, String)]`. Like this, for example:
```haskell
data TerminatorVM n = TerminatorVM
  { bricksEditor :: Editor [(String, String)] n,
  }
```
When I use the `editor` function to construct it:
```haskell
editor _name Nothing [("", "")]
```
I get the following error:
```haskell
Could not deduce (Data.Text.Zipper.Generic.GenericTextZipper [(String, String)])
```

Can you please help?

**Comment by refaelsh** [comment]
My best guess would be that `GenericTextZipper` can not be instantiated over a list of pairs.
According to here: https://hackage.haskell.org/package/text-zipper-0.9/docs/Data-Text-Zipper-Generic.html, 
it can only be instantiated over:
1. Text
2. [Char]
3. (Vector Char)

Is my guess correct?

**Comment by jtdaugherty** [comment]
That's right. A zipper edits a "string-like" value, i.e., some kind of character sequence type. That's why there are instances already for things that are "string-like." Can you say more about what motivates you to attempt to edit a list of pairs of strings?

**Comment by refaelsh** [comment]
> Can you say more about what motivates you to attempt to edit a list of pairs of strings?

I can, but I really don't want to bother you. I feel kinda bad, I've bothered you a lot :-)
But since you asked, my conscience is clear :-)

I want my editor to be able to display text escaped with Ansi Escape Codes. I wrote something small and primitive (but it works), that can take a text with Ansi Escape Codes and return a list of pairs: the first element of the pair represents the text itself, and the second element represents the color of the text. Furthermore, I already succeeded in doing exactly that with Brick's List.

**Comment by jtdaugherty** [comment]
> But since you asked, my conscience is clear :-)

Okay, great. :)

> I want my editor to be able to display text escaped with Ansi Escape Codes.

Are you saying you essentially want syntax highlighting in your editor?

**Comment by refaelsh** [comment]
> Are you saying you essentially want syntax highlighting in your editor?

No. I am building something that can be used as a terminal: I want for example to type in to it `ls -a` and get back the result of `ls`.
But, since `ls`, and many other command (for example `git status`) can return text with Ansi Escape Codes, I want to be able also to print it to the Editor with colors.

**Comment by jtdaugherty** [comment]
I see. I ought to mention that embedding text with escape sequences in a Brick (Vty) UI is not supported and may very well lead to layout problems. So just be aware in case you run into issues.

**Comment by refaelsh** [comment]
> I see. I ought to mention that embedding text with escape sequences in a Brick (Vty) UI is not supported and may very well lead to layout problems. So just be aware in case you run into issues.

Yes, I am completely aware of it already. I've felt it :-) I also found several issues that people opened about support for Ansi Escape Codes in general in Brick.

**Comment by jtdaugherty** [comment]
Okay. The reason is because Vty is responsible for doing layout calculations and generating the escape sequences, and if the output also contains escape sequences it didn't generate, it will not know about them and then its layout calculations may be wrong.

**Comment by refaelsh** [comment]
I understand. Thank you very much for all your answers.

**Comment by jtdaugherty** [comment]
Also, Vty assumes it can calculate the dimensions of an image by measuring the dimensions of its *printable* contents, and if those contents are non-printable (i.e. escapes) then the dimensions will be incorrect.

**Comment by jtdaugherty** [comment]
You're welcome. Please feel free to ask any and all questions; I do not find them bothersome and would like to help where I can.

**Comment by refaelsh** [comment]
I thought about it some more. Since I want colors in my Editor, need an Editor of `[(String, String)]`: a pair of text and color (a list of them to be more precise).
But, since it is impossible to templatize (is this the right term?) an Editor with `[(String, String)]`, can you please provide a suggestion of what would you do?

**Comment by jtdaugherty** [comment]
Typically the approach I'd recommend is to make this a render-time concern. For small enough bodies of text, that will be fast enough not to be a problem. So you'd have an editor over text values, but then at rendering time you'd have a function
```haskell
tokenize :: Text -> [Token]
```
and a function
```haskell
renderTokens :: [Token] -> Widget n
```
that was responsible for turning your tagged string chunks (i.e. tokens) into widgets with the desired colors.

But that assumes you can tokenize the input text (e.g. when you know a syntax in advance and can use a parser), which is not true in the general case you mentioned above where you want to turn escape-sequence-laden text into colorized output.

**Comment by refaelsh** [comment]
Oh! Yes! I understand your idea! Thank you very much :-)

> which is not true in the general case you mentioned above where you want to turn escape-sequence-laden text into colorized output.

I already have a parser that can tokenize strings with escape codes:
```haskell
tokenize :: String -> [Slice] --`Slice` is like your `Token`.
```

**Comment by refaelsh** [comment]
Your idea does not work, unfortunately. The thing is that the `renderEditor` function, the first parameter of it, is a lambda that receives `[a]`, but this `[a]` was originally a string with Ansi Escape Codes, but after it `passed thru` the TextZipper that is behind a Brick's Editor, the `\x1b` character was stripped from it, and now it is impossible to parse it using the `tokenize` function.

**Comment by jtdaugherty** [comment]
That makes sense. The editor infrastructure forbids non-printable characters which is why they get filtered out. The essential issue here is that you're using a text stream to encode more structured data by embedding escape sequences in it. If that's something you can't avoid, then you'd need to build your own editor, I think. The approach I suggested works when you can tokenize a text string only by looking at the text itself (i.e. the words) without knowing anything else (like escape sequences).

**Comment by refaelsh** [comment]
Ok. Got it. Thanks.
