### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ShrykeWindgrace** [jtdaugherty/brick#445]
Just a status update.

Following my hackings for https://github.com/jtdaugherty/vty/issues/251, I tried compiling `brick` on windows against my patched `vty`.

As expected, the unix-specific part is isolated, it is present only in the `FileBrowser` widget. I managed to build cli apps which do not use that widget with success (e.g. `hledger-ui`).

I do not know whether a functional equivalent of this widget for windows is a complete rewrite or just a couple of carefully chosen CPP selectors.

**Comment by jtdaugherty** [comment]
Okay, thanks for your investigation! I'm going to close this for now, since I want to wait until Vty's windows effort is closer to release before evaluating options for Brick. Thanks!

**Comment by ShrykeWindgrace** [comment]
Bumping an old issue: I took a look at what we need in that widget, and it seems that we can safely replace `unix` dependency by `unix-compat`, which is its cross platform analog. On UNIX machines the switch should be seamless since `unix-compat` simply re-exports functions from `unix`.

**Comment by jtdaugherty** [comment]
Thanks! That's already done in #483.

**Comment by ShrykeWindgrace** [comment]
Ah, that completely flew under my radar, my bad =)

**Comment by jtdaugherty** [comment]
No problem, I had also forgotten about your comment about this before that PR came in!

**Comment by cdupont** [comment]
Hello, is windows supported now? From which version? 
Thanks

**Comment by jtdaugherty** [comment]
Hi @cdupont, Brick 2.0 is the first release to support Windows via its dependency on `vty-crossplatform`. Most `brick` applications won’t need to change, but open a new ticket if you need help!
