### ISSUE TITLE
ld: library not found for -liconv clang-13: error: linker command failed with exit code 1 (use -v to see invocation) `clang' failed in phase `Linker'. (Exit code: 1

### ISSUE THREAD

**Issue by markmark1** [jtdaugherty/brick#452]
Compiling Data.ByteString.Base64.URL.Lazy ( Data/ByteString/Base64/URL/Lazy.hs, dist/build/Data/ByteString/Base64/URL/Lazy.o, dist/build/Data/ByteString/Base64/URL/Lazy.dyn_o )
ld: library not found for -liconv
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
`clang' failed in phase `Linker'. (Exit code: 1)

Failed to build bsb-http-chunked-0.0.0.4.
Build log (
/Users/mark/.cabal/logs/ghc-9.4.4/bsb-http-chnkd-0.0.0.4-e36da04c.log ):
Configuring library for bsb-http-chunked-0.0.0.4..
Preprocessing library for bsb-http-chunked-0.0.0.4..
Building library for bsb-http-chunked-0.0.0.4..
[1 of 1] Compiling Data.ByteString.Builder.HTTP.Chunked ( Data/ByteString/Builder/HTTP/Chunked.hs, dist/build/Data/ByteString/Builder/HTTP/Chunked.o, dist/build/Data/ByteString/Builder/HTTP/Chunked.dyn_o )
ld: library not found for -liconv
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
`clang' failed in phase `Linker'. (Exit code: 1)

Failed to build basement-0.0.15.
Build log ( /Users/mark/.cabal/logs/ghc-9.4.4/bsmnt-0.0.15-4518cd07.log ):
Configuring library for basement-0.0.15..
Preprocessing library for basement-0.0.15..
compiling dist/build/Basement/Terminal/Size_hsc_make.c failed (exit code 1)
rsp file was: "dist/build/Basement/Terminal/hsc2hscall28022-0.rsp"
command was: /opt/homebrew/bin/clang -c dist/build/Basement/Terminal/Size_hsc_make.c -o dist/build/Basement/Terminal/Size_hsc_make.o --target=arm64-apple-darwin --target=arm64-apple-darwin -D__GLASGOW_HASKELL__=904 -Ddarwin_BUILD_OS=1 -Daarch64_BUILD_ARCH=1 -Ddarwin_HOST_OS=1 -Daarch64_HOST_ARCH=1 -Icbits -Idist/build/cbits -DARCH_IS_UNKNOWN_ENDIAN -Idist/build/autogen -Idist/build/global-autogen -include dist/build/autogen/cabal_macros.h -I/opt/homebrew/Cellar/ghc/9.4.4/lib/ghc-9.4.4/lib/../lib/aarch64-osx-ghc-9.4.4/base-4.17.0.0/include -I/opt/homebrew/Cellar/ghc/9.4.4/lib/ghc-9.4.4/lib/../lib/aarch64-osx-ghc-9.4.4/ghc-bignum-1.3/include -I/opt/homebrew/Cellar/ghc/9.4.4/lib/ghc-9.4.4/lib/../lib/aarch64-osx-ghc-9.4.4/rts-1.0.2/include -I/opt/homebrew/Cellar/ghc/9.4.4/include/
error: In file included from Size.hsc:14:
cbits/foundation_system.h:17:14: fatal error: 'TargetConditionals.h' file not found
    #include "TargetConditionals.h"
             ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Failed to build byteorder-1.0.4.
Build log ( /Users/mark/.cabal/logs/ghc-9.4.4/bytrdr-1.0.4-dd9be7f2.log ):
Configuring byteorder-1.0.4...
Preprocessing library for byteorder-1.0.4..
Building library for byteorder-1.0.4..
[1 of 1] Compiling System.ByteOrder ( System/ByteOrder.hs, dist/build/System/ByteOrder.o, dist/build/System/ByteOrder.dyn_o )
ld: library not found for -liconv
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
`clang' failed in phase `Linker'. (Exit code: 1)

Failed to build cabal-doctest-1.0.9.
Build log ( /Users/mark/.cabal/logs/ghc-9.4.4/cbl-dctst-1.0.9-ec6161bc.log ):
Configuring library for cabal-doctest-1.0.9..
Preprocessing library for cabal-doctest-1.0.9..
Building library for cabal-doctest-1.0.9..
[1 of 1] Compiling Distribution.Extra.Doctest ( src/Distribution/Extra/Doctest.hs, dist/build/Distribution/Extra/Doctest.o, dist/build/Distribution/Extra/Doctest.dyn_o )
ld: library not found for -liconv
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
`clang' failed in phase `Linker'. (Exit code: 1)
Error: cabal: Failed to build OneTuple-0.4.1.1 (which is required by
exe:bhoogle from bhoogle-0.1.4.2). See the build log above for details.
Failed to build StateVar-1.2.2 (which is required by exe:bhoogle from
bhoogle-0.1.4.2). See the build log above for details.
Failed to build blaze-builder-0.4.2.2 (which is required by exe:bhoogle from
bhoogle-0.1.4.2). See the build log above for details.
Failed to build bimap-0.5.0 (which is required by exe:bhoogle from
bhoogle-0.1.4.2). See the build log above for details.
Failed to build base-compat-0.12.2 (which is required by exe:bhoogle from
bhoogle-0.1.4.2). See the build log above for details.
Failed to build base-orphans-0.9.0 (which is required by exe:bhoogle from
bhoogle-0.1.4.2). See the build log above for details.
Failed to build base64-bytestring-1.2.1.0 (which is required by exe:bhoogle
from bhoogle-0.1.4.2). See the build log above for details.
Failed to build bsb-http-chunked-0.0.0.4 (which is required by exe:bhoogle
from bhoogle-0.1.4.2). See the build log above for details.
Failed to build basement-0.0.15 (which is required by exe:bhoogle from
bhoogle-0.1.4.2). See the build log above for details.
Failed to build byteorder-1.0.4 (which is required by exe:bhoogle from
bhoogle-0.1.4.2). See the build log above for details.
Failed to build cabal-doctest-1.0.9 (which is required by exe:bhoogle from
bhoogle-0.1.4.2). See the build log above for details.

**Comment by jtdaugherty** [comment]
This doesn't appear to be a `brick` problem. Was this filed here by mistake?
