### ISSUE TITLE
Wrap repeating code in a function

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#456]
I have the following piece of code:
```haskell
myHandleEvent :: Ord n => BrickEvent n Common.CustomEvent -> EventM n (CommitMessageVM n) ()
myHandleEvent e = do
  state <- get
  (newBricksList, ()) <- nestEventM (bricksList state) $ do
    handleListEvent event
  modify $ \s -> s {bricksList = newBricksList}
```
I find that it repeats its self in many places. I wish to package it in one function, e.g., the DRY principle.
But, its not exactly the same, the only difference is the second parameter to the EventM thingy, in the above case its `CommitMessageVM`. So, how do I warp this repeating piece of code in one function if the only different is as stated?

P.S.
This might be a general question for Stackoverflow and not Brick related --> in that case, please ignore it and send me to Stackoverflow.

**Comment by jtdaugherty** [comment]
> I find that it repeats its self in many places.

Can you say a bit more about what is repetitive that you'd like to reduce repetition of?

> This might be a general question for Stackoverflow and not Brick related

This is definitely Brick-related, and I would prefer you ask here instead of Stackoverflow.

**Comment by jtdaugherty** [comment]
Also, for what it's worth, the above code could be simplified to just
```haskell
handleEvent e =
  zoom bricksList $ handleEditorEvent e
```
if you make `bricksList` a lens.

**Comment by refaelsh** [comment]
I've updated the source code block in my original post. I've made a few silly copy/paste mistakes.

**Comment by refaelsh** [comment]
> Can you say a bit more about what is repetitive that you'd like to reduce repetition of?

The entire function exists in 3 different files, and it looks the same, the only difference is the second parameter to the EventM thingy. The entire function should be written once in some common file and every other place should call this function instead of repeating the same code all over again.

**Comment by refaelsh** [comment]
> Also, for what it's worth, the above code could be simplified to just
> 
> ```haskell
> handleEvent e =
>   zoom bricksList $ handleEditorEvent e
> ```
> 
> if you make `bricksList` a lens.

Up until now I've avoided this `lens` thingy due to me being really new to Haskell. But, maybe it's time to bight the bullet and go learn it...

**Comment by jtdaugherty** [comment]
> Up until now I've avoided this lens thingy due to me being really new to Haskell. But, maybe it's time to bight the bullet and go learn it...

A nice thing about lenses is that you can use them as much or as little as you like. You can get a lot of benefit from them without, for example, learning all of Control.Lens or using fancy combinators. In the case of your function above, just having lenses makes it possible to reduce all of that boilerplate down to just one call to `zoom`. If that's all you use lenses for, I think that's a win. But if you have lenses, then you can *also* get some nice benefits using the `microlens-mtl` API to make your `EventM` code much more concise. I'd be happy to give you pointers on what I mean if you go that route.

**Comment by refaelsh** [comment]
> if you go that route

No, thank you. I am afraid of the dark :-)

> reduce all of that boilerplate down to just one call to zoom

I will go that route. I think.



But, I would still like to hear your suggestion, please, on how to solve my original question.

**Comment by jtdaugherty** [comment]
> But, I would still like to hear your suggestion, please, on how to solve my original question.

Okay. On that topic, I am still a little bit unclear about what your original question is. It sounds like you are concerned about duplication. What bit of code are you hoping to make more reusable?

**Comment by refaelsh** [comment]
> It sounds like you are concerned about duplication. 

Correct.

> What bit of code are you hoping to make more reusable?

The entire function.

**Comment by refaelsh** [comment]
> Or, to put it another way, _how_ do you want it to be more reusable?

I would like to put this function in one place, so only one time I write the code for it, and every other place that needs this function just calls it without repeating the code.

**Comment by jtdaugherty** [comment]
> I would like to put this function in one place, so only one time I write the code for it, and every other place that needs this function just calls it without repeating the code.

Okay. But the function currently does a very specific thing, which is to handle events in a particular editor in a particular kind of application state. So in order to make it reusable, it would need to be generalized in some way, such as to work for many *different* editors, or to work on many different kinds of application state. What kind of generalization are you hoping for?

**Comment by jtdaugherty** [comment]
(To be clear, the function you provided already *is* reusable if all you want to do is to handle editor events in numerous spots. To call it you'd just write `myHandleEvent e`. But I'm assuming that you want something more than just to know to call this function that you already wrote.)

**Comment by refaelsh** [comment]
> to work on many different kinds of application state

This one. I find that I always need this function but always with a different state, e.g., the `CommitMessageVM` is every time different. One time it can be `TreeVM` and one time `SomethingOtherVM`.

**Comment by jtdaugherty** [comment]
Is the issue that you have an editor in each kind of application state, and you always want to dispatch an editor event, but want that to work across different kinds of application states?

**Comment by refaelsh** [comment]
I have this function here: https://gitlab.com/refaelsh/giter/-/blob/master/src/ViewModel/TreeVM.hs#L51
Exactly the same one here: https://gitlab.com/refaelsh/giter/-/blob/master/src/ViewModel/StatusListVM.hs#L113
They are the same, except the "EventM".
I want only one time to write this function in some file, in one place, and then call it whenever needed.

**Comment by jtdaugherty** [comment]
But those are *not* exactly the same because they operate on different kinds of underlying state, i.e., the first operates on `TreeVM n` and the second one operates on `StatusListVM n`. The code written for each one looks the same, but the types are not. Does that make sense?

The irony is that the way to rewrite those two as one function that is generic in the kind of state is to use lenses, and even then that's overkill because once you are using lenses, both of those handlers become one line of code anyway. Here's a generic version that uses lenses (where `bindings` and `bricksList` are both lenses):
```haskell
handleEvent (VtyEvent e) =
  handleListEventWithLens (bindings.bricksList) e

handleListEventWithLens :: Lens' s (GenricList n t e) -> Brick n ev -> EventM n s ()
handleListEventWithLens which event =
  zoom which (handleListEventVi event)
```
But I think that's not a win because it makes the code *more* verbose than it would be if you just had handlers that said `zoom someLens (handleListEventVi e)` in both handlers.

I'm going to keep pointing this out, even though I know you are wanting to avoid lenses for now: the pattern you are trying to avoid repeating is *exactly* what the lens API is going to help with, among a great many other things.

**Comment by refaelsh** [comment]
> The code written for each one looks the same, but the types are not. Does that make sense?

Yes.

> I'm going to keep pointing this out, even though I know you are wanting to avoid lenses for now: the pattern you are trying to avoid repeating is exactly what the lens API is going to help with, among a great many other things.

Understood. No choice :-) Need to go learn this `lenses` stuff.

Thank you very much for your answers :-)
