### ISSUE TITLE
handleFormEvent doesn't update form field validation state?

### ISSUE THREAD

**Issue by jtdaugherty** [jtdaugherty/brick#468]
### Discussed in https://github.com/jtdaugherty/brick/discussions/467

<div type='discussions-op-text'>

<sup>Originally posted by **amano-kenji** May 15, 2023</sup>
It seems that after I manually call `setFieldValid False ...` on a field, `handleFormEvent` doesn't set it valid after entering a letter in a text field.</div>

**Comment by jtdaugherty** [comment]
@amano-kenji I've opened this in lieu of the discussion. If you think something isn't working as expected, please open an issue instead of a discussion topic. Thanks!

**Comment by jtdaugherty** [comment]
In thinking about this I want to confirm that we both think it ought to work as follows:

* Under normal circumstances, input events arrive and `handleFormEvent` is called to dispatch them to the right fields.
* At some point, a field is considered valid by its built-in validator, but you have some extra validation you want to do.
* You do that validation, get `False`, and then call `setFieldValid False` on the relevant field.
* At some time later, another input event arrives on that field, but this time the built-in validator considers the field valid and you want that result to take precedence and you do *not* want to do additional validation. At this point you would like the field's validation state to be updated for you by the field's built-in validator.

Is that an accurate summary of what you are wanting to happen?

**Comment by jtdaugherty** [comment]
Also, in the mean time, you can get around this issue by calling `setFieldValid True` right before calling `handleFormEvent` to reset the "external" validation state so that the internal validation status takes precedence.

**Comment by amano-kenji** [comment]
This is how I insert an error message into form state and maintain validation state.
```
newtype TextFieldError = TextFieldError T.Text deriving (Eq, Show, Generic)

data TextFieldValidator s n = TextFieldValidator {
  fieldName :: n
, fieldAccessor :: Lens' s T.Text
, validate :: T.Text -> Maybe TextFieldError
} deriving Generic

-- | If any of validators returns an error, set the error field in form state to the error message, and set the form
-- field invalid.
validateTextFields  :: Eq n
  => [TextFieldValidator s n]
  -> Lens' s  (Maybe T.Text) -- ^ lens for error field in form state.
  -> Form s e n
  -> Form s e n
validateTextFields vs errL f = let
  s = formState f
  validateRecursively (TextFieldValidator { fieldName, fieldAccessor, validate }:vs') f' = let
    field = s ^. fieldAccessor
    in case validate field of
      Nothing -> validateRecursively vs' $ setFieldValid True fieldName f'
      Just (TextFieldError err) -> setValidRecursively vs' $ updateFormState (s & errL ?~ err) $ setFieldValid False fieldName f'
  validateRecursively [] f' = updateFormState (s & errL .~ Nothing) f'
  setValidRecursively (TextFieldValidator { fieldName }:vs') f' = setValidRecursively vs' $ setFieldValid True fieldName f'
  setValidRecursively [] f' = f'
  in validateRecursively vs f
```

**Comment by amano-kenji** [comment]
I want external validators to invalidate fields, but I don't want them to manually validate fields.

I want to add additional checks on top of built-in validators. In some cases, I may want to entirely disable built-in validators.

**Comment by jtdaugherty** [comment]
> I want external validators to call setFieldValid False, but I don't want them to manually call setFieldValid True unless I want to entirely override built-in validators.

It seems to me that if you're going to have any external validation, you're kinda committing to taking ownership for all validation anyway, in which case you should call `setFieldValid` after every event anyway.

> Built-in validators should call both setFieldValid True and setFieldValid False.

This is not true, because `setFieldValid` sets the *external* validation flag for each field. The fields already have their own internal validators (as provided to each of the field constructors). The whole point of `setFieldValid` is to provide a totally separate validation mechanism for cases where the internal validators need to run IO.

**Comment by amano-kenji** [comment]
Is external validation entirely separate from internal validation?

**Comment by amano-kenji** [comment]
> since an upper-limit validation can already be performed in the current validation API

How? I had to use an external validator to enforce upper-limit validation.

**Comment by amano-kenji** [comment]
Let's say there is a form field whose type is `Int`. I entered `-` into the edit box.

I want to run an external validator to enforce an upper limit and attach an error message to the form state.

The internal validator fails, so the external validator doesn't get `-`. The external validator gets the last valid value. This is why I have to use `Text` fields for external validators.

**Comment by jtdaugherty** [comment]
> How? I had to use an external validator to enforce upper-limit validation.

Why? Using a pure function to do this work is straightforward, as long as you write your own field constructor. To do that, you'd use something like `editField` and pass as the fifth argument a function like
```haskell
myUpperLimitValidator :: [Text] -> Maybe Int
myUpperLimitValidator ls = do
     let s = T.head ls
     intVal <- readMaybe $ T.pack s
     if intVal <= upperBound then Just intVal else Nothing
```

**Comment by amano-kenji** [comment]
Okay. In some cases, I want my validator to take the whole form state into account.

For example, a number field should not be smaller than another number field.

**Comment by jtdaugherty** [comment]
In that case, you'll likely need to build your own input/field/validation processing. As the Forms documentation mentions, the form API is designed for a specific common set of use cases, and if your needs call for something more involved (or just plain different) then the form API might not be a good choice.

**Comment by amano-kenji** [comment]
In this case,
```
myUpperLimitValidator :: [Text] -> Maybe Int
```
can be turned into
```
meinValidator :: s -> [Text] -> Maybe Int
```

**Comment by jtdaugherty** [comment]
> I wish external validators had access to raw Text instead of the interpreted types like Int.

That's a design choice that I deliberately made. Not every field even has text as its contents, so there is not a uniform way to provide such access. The point of external validation is that 1) internal validation passes and 2) additional validation is required to tell whether the internal values are valid by some other test. If you don't want to do internal validation, don't! Just let the internal values always be considered valid (i.e. their validators would always just be `Just ...`) and then always apply external validators. This would get you the whole form state because the whole form state would have been updated by the (trivial) validators that already run. Then you can manage the validation state yourself with `setFieldValid`.

Please let me know if you have what you need for us to close this ticket. Thanks!

**Comment by amano-kenji** [comment]
I want to make sure the current form API can do what I want.

If I call `setFieldVali True` on every field before calling `handleFormEvent`, does `handleFormEvent` mark fields invalid according to internal validators?

**Comment by jtdaugherty** [comment]
> If I call setFieldValid True on every field before calling handleFormEvent, does handleFormEvent mark fields invalid according to internal validators?

The use of `setFieldValid` takes precedence over the result of the internal validators.

**Comment by amano-kenji** [comment]
As soon as I use `setFieldValid`, internal validators are gone? Are well-formed numbers in `Int` fields still passed to external validators even if `setFieldValid` is used?

**Comment by jtdaugherty** [comment]
> As soon as I use setFieldValid, internal validators are gone?

No, internal validators still run: internal validators *are transformations of the input values* that produce form state update values. They always run, and the form state only gets updated when the internal validators succeed, i.e., they produce a `Just` value.

> Are well-formed numbers in Int fields still passed to external validators even if setFieldValid is used?

External validators are not "passed" anything, i.e., your external validation code has to obtain a form field value (from the updated form state, *post-internal-validator*, and then determine wether to call `setFieldValid`.

> How do I know whether an Int or Double field contains a proper number that fails external validation or something that is not a number?

I'm not sure I understand the question, and this makes me wonder how well you understand how the form API's validators work. An Int or Double that is a valid Int or Double is put back into the form state (of type `s`, using its field-specific lens) at which point you can access it in `EventM` and then decide for yourself whether it is "valid", i.e., passes whatever application check you want to apply. Does that make sense?

**Comment by amano-kenji** [comment]
Okay, I just read the code. 
* `formFieldExternallyValid` is set by `setFieldValid`. `formFieldExternallyValid` is `True` by default.
* `invalidFields` simply returns names of fields that fail internal validation or have `False` as the value of `formFieldExternallyValid`.
* `allFieldsValid` is simply `null . invalidFields`.
* With `invalidFields`, there is no way I can differentiate between internal validation failure and external validation failure. It seems that I should run external validators in `RenderM` if I want to be able to differentiate between internal validation failure and external validation failure.

**Comment by jtdaugherty** [comment]
> With invalidFields, there is no way I can differentiate between internal validation failure and external validation failure.

That's already true regardless of how you do validation, because a validation "failure" means that the input value (as observed in the form field itself) is just never successfully converted into a valid value and thus stored in the form state. So you will never be able to find out what an "invalid" input is, *unless you don't do any validation* and just provide dummy functions like I said earlier. That way, internal validators always succeed (i.e. they always successfully convert an input value into a "real" one, thus causing it to get stored in the form state).

**Comment by amano-kenji** [comment]
There is a workaround. I don't call `setFieldValid` in `EventM`. I call `setFieldValid False` in `RenderM` while calculating error messages at the same time.

**Comment by amano-kenji** [comment]
I think the issue can be closed by stating

* `setFieldValid` sets `formFieldExternallyValid`.
* `invalidFields` returns names of fields that fail internal validation or have `False` as the value of `formFieldExternallyValid`.
* `invalidFields` relies on `invalidFields`
* external validators can detect internal validation failures if `formFieldExternallyValid` is `True` for all fields.
* Error messages can be stored in the application state in `EventM` or calculated in `RenderM`.
