### ISSUE TITLE
The type class constraint of Brick.Widgets.List.listReplace

### ISSUE THREAD

**Issue by sifmelcara** [jtdaugherty/brick#48]
`listReplace :: Eq e => Vector e -> Maybe Int -> List e -> List e`

Is there any reason that the element of Vector must have Eq instance? (I have no idea)
I removed the `Eq e` constraint and the library still compiles.

**Comment by jtdaugherty** [comment]
I think that's left over from a previous implementation. Feel free to submit a pull request removing it!
