### ISSUE TITLE
Cannot install `brick` via `cabal update && cabal install brick` on NixOS

### ISSUE THREAD

**Issue by colin-heffernan** [jtdaugherty/brick#485]
Distro: NixOS Unstable

I am trying to use pure commandline `cabal` for dependencies to make development easier for non-Nix users. However, running `cabal update && cabal install brick` gives the following error:
```
Resolving dependencies...
Error: cabal: Cannot build the executables in the package brick because none
of the components are available to build: the executable
'brick-visibility-demo', the executable 'brick-viewport-scrollbars-demo', the
executable 'brick-viewport-scroll-demo', the executable 'brick-theme-demo',
the executable 'brick-text-wrap-demo', the executable 'brick-tail-demo', the
executable 'brick-tabular-list-demo', the executable 'brick-table-demo', the
executable 'brick-suspend-resume-demo', the executable 'brick-readme-demo',
the executable 'brick-progressbar-demo', the executable 'brick-padding-demo',
the executable 'brick-mouse-demo', the executable 'brick-list-vi-demo', the
executable 'brick-list-demo', the executable 'brick-layer-demo', the
executable 'brick-hello-world-demo', the executable 'brick-form-demo', the
executable 'brick-fill-demo', the executable 'brick-file-browser-demo', the
executable 'brick-editor-line-numbers-demo', the executable 'brick-edit-demo',
the executable 'brick-dynamic-border-demo', the executable
'brick-dialog-demo', the executable 'brick-custom-keybinding-demo', the
executable 'brick-custom-event-demo', the executable 'brick-cropping-demo',
the executable 'brick-cache-demo', the executable 'brick-border-demo' and the
executable 'brick-attr-demo' are all marked as 'buildable: False'
```

I believe `cabal` is trying to build the demo executables, but I did not specify the flag to do so. I can provide any other information as needed.

**Comment by jtdaugherty** [comment]
As far as the specific thing you are trying to do, there is a [provisional](https://github.com/haskell/cabal/issues/6481) `cabal` flag, `cabal install --lib`, for cases like this. But it sounds like that isn't stable yet, so I don't recommend it.

More importantly, though, what is motivating your desire to install `brick` in this way? I could imagine wanting to do this to support offline work, but even then, prefetching the source would be a good approach instead. (`cabal install` historically has meant install executables, not libraries, which is why this isn't working. Brick doesn't provide any non-demo executables.) How are you hoping to help users by doing this? (And what users are we talking about here? NixOS users?)

**Comment by colin-heffernan** [comment]
> `cabal install` historically has meant install executables, not libraries
Sorry for the issue, then! I'm new to Haskell and used to NPM/PIP library installations. How would I do this in Haskell?

> How are you hoping to help users by doing this?
I'm trying to write a text editor as a project to learn Haskell, and I wanted to use something other than Nix for dependency management in case non-Nix users wanted to contribute to my project.

**Comment by jtdaugherty** [comment]
> I wanted to use something other than Nix for dependency management in case non-Nix users wanted to contribute to my project.

In that case, no special action is needed. `cabal` takes care of resolving dependencies, fetching them, and building them. `cabal build` and/or `cabal run` do all that automatically. Does that provide you with enough information to get what you need?

**Comment by jtdaugherty** [comment]
To be clear, if you want *end-users* who aren't Haskell developers to be able to try your program, that's a different problem. If you are just talking about other Haskell developers, then `cabal` will be the conventional way to build and run your program.

**Comment by colin-heffernan** [comment]
> If you are just talking about other Haskell developers, then `cabal` will be the conventional way to build and run your program.

Got it, thanks.

> In that case, no special action is needed. `cabal` takes care of resolving dependencies, fetching them, and building them. `cabal build` and/or `cabal run` do all that automatically.

Do I just specify dependencies manually in the `project.cabal` file?

**Comment by jtdaugherty** [comment]
Yes, the `.cabal` file is typically where dependencies are specified. Any other way is bolted on; `cabal` files are conventionally *the* way to organize Haskell projects.

**Comment by colin-heffernan** [comment]
Thanks for everything, and sorry again for the issue!

**Comment by jtdaugherty** [comment]
No problem, please let me know if I can help with anything else!

**Comment by colin-heffernan** [comment]
Will do!
