### ISSUE TITLE
Documentation Unavailable on Hackage

### ISSUE THREAD

**Issue by liamzee** [jtdaugherty/brick#490]
This is not such a big deal, since it's not a given that the API has changed (version numbers don't suggest PVP) and the previous version is exposed, but on the current Hackage link all the documentation is hidden.

https://hackage.haskell.org/package/brick

**Comment by jtdaugherty** [comment]
Thanks for reporting this!

**Comment by jtdaugherty** [comment]
> it's not a given that the API has changed

FYI: for 2.1, there was indeed an API change. I change the second version component when there is an API change (or other similarly disruptive change like a change to package constraints or dependencies). I change the third version component (or just introduce it) for bug fixes.

**Comment by jtdaugherty** [comment]
See also https://github.com/haskell/haddock/issues/1582

**Comment by jtdaugherty** [comment]
This is now fixed for 2.1 and 2.1.1. Thanks again!
