### ISSUE TITLE
Segmentation fault when eagerly pressing a keyboard key

### ISSUE THREAD

**Issue by MathiasSven** [jtdaugherty/brick#498]
It seems that when a key is either pressed or given to the Haskell process before the initialization of Brick's event handler, it causes a Segmentation Fault. I am not sure how often it happens since it is timing dependent, I only had it happen a couple of times, and only once I think outside using `cabal run`

#### Steps To Reproduce
Either this `Main.hs`, followed by `ghc -threaded Main.hs && ./Main`, pressing any key in the 1 second window.
```haskell
module Main where

import Brick
import Control.Concurrent (threadDelay)

main :: IO ()
main = do
  threadDelay 1_000_000
  simpleMain $ str @() "Foo"
```
Alternatively:
```haskell
main = simpleMain $ str @() "Foo"
```
Running it via `sleep 1 && ghc -threaded Main.hs && ./Main`, key presses during `sleep 1` carry on to the very start of the haskell `main`, having the same effect as a the previous snippet.

**Comment by jtdaugherty** [comment]
Which version of `brick` and `vty` are in effect when this happens? I fixed a bug along these lines in `vty` 5.39 and that fix was also carried over into the initial release of `vty-unix`.

**Comment by MathiasSven** [comment]
Apologies, It seems that the latest version of `brick` in nixpkgs set is somewhat behind and depends on vty `5.35`. I can confirm that the same code above does not have the same issue in the latest versions.

**Comment by jtdaugherty** [comment]
Okay, I'm glad to hear it!
