### ISSUE TITLE
test compilation failure with brick-2.1.1 in Nixpkgs

### ISSUE THREAD

**Issue by cdepillabout** [jtdaugherty/brick#499]
I'm seeing a compilation failure with `brick-2.1.1` (from Stackage's LTS-22.4) in Nixpkgs:

https://hydra.nixos.org/build/246165149/nixlog/1

I don't have enough experience with brick to take a good guess as to why this would be occurring, but my guess would be either a straight-up problem with the test code when the package was uploaded, or possibly too-loose versions on the test suite.

Also, the tests for `brick` have been disabled in Stackage, which is possibly why we're seeing this in Nixpkgs (since we follow stackage, but try to build tests by default).

**Comment by cdepillabout** [comment]
I've disabled the tests for `brick` in Nixpkgs:

https://github.com/NixOS/nixpkgs/pull/279413/commits/2721b4501461

**Comment by jtdaugherty** [comment]
Thanks for the report. I fixed that in 2.2, in case that helps.

**Comment by jtdaugherty** [comment]
I'm not sure there's much to do here so I'm going to close it. But it looks like you have a stop-gap fix for now if you're needing to stick with 2.1.1.
