### ISSUE TITLE
How can I get SIGTSTP (ctrl-z) to suspend the process?

### ISSUE THREAD

**Issue by danchoi** [jtdaugherty/brick#500]
In Brick, the keyboard event ctrl-z is processed like any other keyboard key, but I would like ctrl-z to suspend the process and return me to the previous command line, as typical for most Unix programs. I tried importing `System.Posix.Signals` and running `liftIO $ raiseSignal keyboardStop` directly in the event handler, but this just froze the program.

I also tried `M.suspendAndResult (raiseSignal keyboardStop >> return st)`. The effect is to clear the screen and return to the original terminal screen but then to hang.

The only way to get normal ctrl-z behavior seems to be to use `M.suspendAndResult ...` and then manually press `ctrl-z` a second time while Brick in the suspend action.

**Comment by jtdaugherty** [comment]
Hi @danchoi - that's interesting. When I tried `suspendAndResume (raiseSignal keyboardStop >> return st)`, I got the desired behavior: the program suspended to the shell, and then resumed once I foregrounded the suspended process. Here is a complete working program I used:

```haskell
module Main where

import qualified Graphics.Vty as V

import qualified Brick.Main as M
import qualified Brick.Types as T
import Brick.Widgets.Core (str)
import qualified Brick.AttrMap as A
import System.Posix.Signals

drawUI :: () -> [T.Widget ()]
drawUI () = [str "Press C-z to suspend or any other key to quit"]

appEvent :: T.BrickEvent () e -> T.EventM () () ()
appEvent (T.VtyEvent (V.EvKey (V.KChar 'z') [V.MCtrl])) = do
    st <- T.get
    M.suspendAndResume $ do
        raiseSignal keyboardStop
        return st
appEvent _ =
    M.halt

theApp :: M.App () e ()
theApp =
    M.App { M.appDraw = drawUI
          , M.appChooseCursor = M.neverShowCursor
          , M.appHandleEvent = appEvent
          , M.appStartEvent = return ()
          , M.appAttrMap = const $ A.attrMap V.defAttr []
          }

main :: IO ()
main = M.defaultMain theApp ()
```

**Comment by danchoi** [comment]
@jtdaugherty Thank you for your response. I compiled your program on MacOS 14.2 and I experience the following strange behavior:

1. `cabal run signaltest` and I see the terminal taken over by the message `Press C-z to suspend or any other key to quit`.
2. I press `ctrl-z`. The terminal restores to previous state but shows that `cabal run signaltest` is still running in the foreground. 
3. I press `ctrl-z` again. Finally I get the prompt and the job number of the stopped process.
4. Pressing `fg<ENTER>` foregrounds the program, but it doesn't repaint the screen. Pressing `ctrl-z` puts the program in the background.
5. Now when I press `fg<ENTER>` the program restarts again and repaints the screen as I would expect. 

The pattern is not always consistent. Sometimes I end up in a hang after the Brick screendraw. I can never get `ctrl-z` to get me from the brick app to the command prompt in one keypress.

**Comment by jtdaugherty** [comment]
I suspect that `cabal run` is getting involved. What if you run the binary directly rather than using `cabal run`?

**Comment by jtdaugherty** [comment]
Basically, `cabal run` appears not to `exec` the program it runs, meaning that once you background the Brick program, you're still dealing with an active `cabal run` process. You have to background *that* to get back to the shell.

**Comment by danchoi** [comment]
Problem solved! Thank you very much

**Comment by jtdaugherty** [comment]
Okay, great!
