### ISSUE TITLE
Pop-up overlay dialog, is it possible?

### ISSUE THREAD

**Issue by tobz619** [jtdaugherty/brick#510]
I would like to activate a pop-up with the Tab key that asks the user how many records they want to show on the page. This is the current [file](https://github.com/tobz619/haskell-snake-learn/blob/2d85a51525f851a45953dee1ca6c4d405d30455e/src/UI/HighscoreScreens.hs)

```haskell
data HSPageName = ScoreTable | ScoreDialogNum Int
  deriving (Show, Eq, Ord)

data MenuState = MenuState { _menuDialog :: Dialog Int HSPageName
                           , _menuChoice :: Int
                           }

data HighScoreState = HighScoreState { _highscores :: ![ScoreField]
                                     , _height :: !Int
                                     , _selectScore :: Maybe MenuState
                                     }
concat <$> mapM makeLenses [''HighScoreState, ''MenuState]
-- ...

ui :: HighScoreState -> [Widget HSPageName]
ui hss = perPage (view selectScore hss) 
        <> [ C.center $ allTable hei (scoresTable scos)]

         where hei = view height hss
               scos = view highscores hss

perPage :: Maybe MenuState -> [Widget HSPageName]
perPage Nothing = []
perPage (Just (MenuState dia _)) = [D.renderDialog dia emptyWidget]

-- ...

selDialog :: Dialog Int HSPageName
selDialog = D.dialog (Just $ txtWrap "How many scores to show per page?")
                   (Just (ScoreDialogNum defHeight, options))
                   125
  where options = [ ("5", ScoreDialogNum 10, 10)
                  , ("10", ScoreDialogNum 20, 20)
                  , ("25", ScoreDialogNum 50, 50)
                  , ("50", ScoreDialogNum 100,100)
                  ]

-- ...
inputHandler :: BrickEvent HSPageName e -> EventM HSPageName HighScoreState ()
--...

inputHandler (T.VtyEvent (V.EvKey V.KBackTab [])) = do
  undefined
-- ...

highScores :: IO ()
highScores = do
  db <- openDatabase "highscores.db"
  scores <- getScores db
  _ <- defaultMain highScoresApp (HighScoreState scores defHeight Nothing)
  return ()
```

My strat was to:

1. Initialise the `_selectScore` field as `Nothing` and prepend an `[]` onto the front of the widget made by `ui` so only the table shows.
2. When tab is pressed, change the `_selectScore` field to a `Just _menuDialog` and run the dialog there, prepend the dialog widget onto ui - initialising with the value of `_height`; this will use `perPage` to create the on top of the current state of the table.
3. When the user has selected a value with Enter:
  i. Change the `_menuChoice` to their selection for later initialisations
  ii. Change the `_selectScore` back to `Nothing` so the dialog disappears. 
  iii. Reload the app with `_menuChoice` setting `_height` and rendering a new table.

Maybe my strategy is entirely wrong and I should do the processing on another page and then feed the choice back into the `HighScoreState` later on.

I appreciate the help in advance!

**Comment by tobz619** [comment]
Soon after I solved one of my issues which was "how could I hide the dialog and put it into a state where I can hide it on initialisation?" with this:

```haskell
ui :: HighScoreState -> [Widget HSPageName]
ui hss = perPage (view selectScore hss) 
        <> [ C.center $ allTable hei (scoresTable scos)]

         where hei = view height hss
               scos = view highscores hss

perPage :: Maybe MenuState -> [Widget HSPageName]
perPage Nothing = []
perPage (Just (MenuState dia _)) = [D.renderDialog dia emptyWidget]
```

Now just to figure out how to do the pop-up on Tab in my inputHandler.

**Comment by jtdaugherty** [comment]
@tobz619 it looks like you might have figured out what you want to do, but I'm not entirely sure if there are any unresolved questions. Let me know if there's still something I can help with.

**Comment by tobz619** [comment]
Partially so:

So activating the dialog doesn't seem to render it correctly and control still goes to the table.

Still working out some teething issues but the mechanism to turn it on works.

**Comment by jtdaugherty** [comment]
> So activating the dialog doesn't seem to render it correctly and control still goes to the table.

Can you say more about "doesn't seem to render it correctly"? What behavior do you want, and how does that differ from what you are seeing?

**Comment by jtdaugherty** [comment]
Maybe post a screenshot of what you are seeing?

**Comment by tobz619** [comment]
![image](https://github.com/jtdaugherty/brick/assets/93312805/a0565ce0-a3d3-4c76-bc8a-fc30c721493b)

This is where I currently get up to. This renders if I press 'h'.

Currently I'm having trouble figuring out how to deal with the `Maybe Menustate` field .

I can "zoom" to selectScore and return a Maybe Menustate but I don't really know how best to manipulate that menustate from the outer structure.

**Comment by tobz619** [comment]
There's a really unfortunate pattern of:
1. I brickwall on a problem for an hour.
2. I post it here
3. I find a solution within 15 minutes because I was slightly off.

I just had to add `_Just` prism to the zoom like so:

```haskell
inputHandler key@(T.VtyEvent (V.EvKey (V.KChar 'h') [])) = do
  put . set selectScore (Just defMenuState) =<< get
  zoom (selectScore . _Just) $ dialogHandler key
```

This pops up the menu but it doesn't make the dialog interactable: I think I am still focused on the table in the background.

**Comment by tobz619** [comment]
Okay,

So I finally have separation and it changes the size of the table as desired:

![image](https://github.com/jtdaugherty/brick/assets/93312805/ff2fc6cb-3ec6-4f9d-824a-2b098427dc07)

But selecting the value is laggy with a little bit of delay on repeated inputs and selecting an option behaves as expected in that I can still control the table but sometimes my terminal comes back in view over the table or in the background.

![image](https://github.com/jtdaugherty/brick/assets/93312805/309c1ca7-d66b-459b-8277-c98d42dbfd58)

I've done this by making two apps with two different names and switching back and forth between them like [so](https://github.com/tobz619/haskell-snake-learn/blob/bdcfd4b62926d02548bf795ab57fe16fb30382f6/src/UI/HighscoreScreens.hs#L157-L171).

Is this a correct approach? I feel I'm cheesing it with liftIO.

**Comment by tobz619** [comment]
Please forgive me: [`suspendAndResume`](https://github.com/tobz619/haskell-snake-learn/blob/4-create-highscores-page/src/UI/HighscoreScreens.hs#L118-L121) has solved my problem entirely.

**Comment by jtdaugherty** [comment]
Hmm, cabal run should not be used to execute brick programs because it interacts badly with the terminal state management in brick. Also, I don't think you should need to suspend and resume either.

**Comment by tobz619** [comment]
I mean, it certain solved the issue I was having - albeit it it does flash the screen very quickly when switching between the menu and Highscore screen but not enough to be problematic at the moment.

`suspendAndResume` entirely cut out all of the lag issues I was having with `liftIO`.

**Comment by jtdaugherty** [comment]
Without seeing your complete program I can't really comment on your approach, but `suspendAndResume` isn't for what you're using it for, based on your description, so while it might have helped, I guess I'm concerned you might not understand its purpose or how best to deal with the situation. If you're experiencing lag, or if you need to use `suspendAndResume` for any reason that doesn't involve stopping your program to do useful work and then resume it, then I suspect there are other factors at play, and that a better approach is appropriate. I mention this because having a good understanding of the problem and the Brick API will be essential if your application gets bigger or gets used in other situations.

**Comment by tobz619** [comment]
I mean I think I'm using it correctly; the whole main menu is contained in [here](https://github.com/tobz619/haskell-snake-learn/blob/4-create-highscores-page/src/UI/HighscoreScreens.hs):

1. I suspend the base highscore app and open another an open another app with the score in the back but the dialog over it and in view.
2. I take the result from the dialog and feed it back into the app by changing the state values.
3. Once I have exited the inner app, I resume and change the dialog to Nothing so it is no longer rendered on top of  my page.

**Comment by jtdaugherty** [comment]
Yes, this is exactly my point; your step (1) is not necessary. While nesting Brick applications that way is possible, it would be better to combine your applications into one so that your application is capable of showing the UI it needs to show, and using a mode flag in your application state to decide what gets drawn and how events get dispatched.

If you want to render things “on top” of other things, that is already built into the framework; that is why the draw function returns a list of layers, with the topmost layer first.

**Comment by tobz619** [comment]
The issue I ran into was how could I separate the control from the background and foreground elements in my layer list? Or more specifically, how would I be able to:

a. Overlay another widget on key press? <= Handled with a `Maybe` in the state
b. Provide exclusive control to that widget <= main pain point
c. Carry forward the result of that widget on closure and change the state <= very much doable 

As far as I'm aware, the handler functions see the same app state and I'm not aware of any ways to pattern match or look into my state before I press a key to do something.

In my solution, I had to make two different Apps with two different Names but the same underlying state.

While I could add more keybindings with modifiers so I could work on both at the same time, it was not what I was aiming for.  How would I go about changing my current implementation so something more pleasant? I was looking for inspiration in the example programs but didn't find anything that matched at a glance unfortunately :( .

**Comment by jtdaugherty** [comment]
> Overlay another widget on key press? <= Handled with a Maybe in the state

A Maybe in the state would be part of it, yes; the other part would be a change to the draw function to return more than one layer when you want to present a dialog on top of the rest of your UI.

> Provide exclusive control to that widget: reuse existing keybinds and don't affect what's underneath <= main pain poinot

This would be done by using a mode flag in your application state (e.g. `data Mode = Main | ShowingDialog`) to decide how to route events. Either they are routed to your main event handler, or to `handleDialogEvent` (if you’re using the built-in dialog).

> the handler functions see the same app state and I'm not aware of any ways to pattern match or look into my state before I press a key to do something.

This would involve doing what I described above, where your state contains a “mode” value that you use to decide how to handle events, and what to draw.

Does that make sense?

**Comment by tobz619** [comment]
Yes, this makes a lot more sense. Thank you.

To be clear for each key, I'd do something like:
```haskell
inputHandler someKeyPress = do
  m <- use mode
  case m of
    Main -> input for no dialog.
    ShowingDialog -> input for showing dialog
```

?

**Comment by jtdaugherty** [comment]
> To be clear for each key, I'd do something like:

Rather than doing it for each key, I would recommend having a separate top-level handler for the collections of events for each mode. Something like this:

```haskell
data Mode = Main | Dialog

Ddata AppState = AppState { … , _appMode :: Mode }

inputHandler ev = do
    mode <- use appMode
    case mode of
        Main -> handleEventMain ev
        Dialog -> handleEventDialog ev
```

That is to say, the `case` on the mode would only happen in exactly one place.

**Comment by jtdaugherty** [comment]
Then, in your draw function, you might do something like:

```haskell
draw :: AppState -> [Widget Name]
draw st =
    case st^.appMode of
        Main -> [drawMain st]
        Dialog -> [drawDialog st, drawMain st]
```

**Comment by tobz619** [comment]
Thank you that's perfect!

**Comment by jtdaugherty** [comment]
Great, I hope this will lend itself to a more natural application design! It has worked well for me in all of my Brick projects.

**Comment by tobz619** [comment]
Worked like a dream and is much cleaner and more understandable! I should be able to rewrite the rest of my app to follow a similar pattern.

Thank you very much! :)

**Comment by jtdaugherty** [comment]
I'm glad to hear it, happy to help!
