### ISSUE TITLE
Crashes when use hCenter, hLimit, and vBox together.

### ISSUE THREAD

**Issue by sifmelcara** [jtdaugherty/brick#52]
The following program crashes when the terminal width is less than `max (min hlim a) (min hlim b)`, and this happens both when the initial terminal size is too small and when I manually resize terminal width after program start.
````Haskell
import Brick
import Brick.Widgets.Center

ui :: Widget
ui = hCenter . hLimit hlim $ vBox [s a 'A', s b 'B']
    where
    s x c = str . take x $ repeat c
    hlim = 100
    a = 60
    b = 40

main :: IO ()
main = simpleMain ui
`````
The error I got is `Main.hs: row 0 now exceeds region width`.

Not sure if this is a duplicate of #47 .

**Comment by jtdaugherty** [comment]
Thanks for the report and for the test program!  I'll take a look in the next few days when I get some time.

**Comment by jtdaugherty** [comment]
I've pushed a fix in https://github.com/jtdaugherty/brick/commit/5ed49551795b06ec856a4084e75ac73329f79df6. This behavior could come up in a few different settings and it should now be avoided in all cases. Care to try this against your own project?  Once you're satisfied, feel free to close this issue (or let me know what else I can do).

Thanks!

**Comment by sifmelcara** [comment]
Yes, the commit fixed the problem. Thank you.
