### ISSUE TITLE
Brick visibility demo - ctrl-arrow up/down

### ISSUE THREAD

**Issue by dylanmc** [jtdaugherty/brick#6]
The top-left and top-right viewports work as advertised. The bottom one does as expected for left-right movements, but ctrl-up/down arrows affect the top-left viewport instead of the bottom one.

brick version 0.1
vty-5.2.10 (as reported in my cabal sandbox's share/x86_64-osx-ghc-7.10.2 directory)

unsure where the output of `cabal freeze` goes.

**Comment by jtdaugherty** [comment]
This might be because your terminal emulator isn't sending the same keycodes that Vty expects. Which emulator are you using? (And are you using screen or tmux?)

**Comment by jtdaugherty** [comment]
(And `cabal freeze` writes `cabal.config`.)

**Comment by jtdaugherty** [comment]
I tried this using `Terminal.app` and I saw the same behavior that you described. I always use iTerm2, though, and it works as expected there.

**Comment by jtdaugherty** [comment]
It is possible to tell Terminal.app which escape sequences to send for certain keys.  You might consider this:

http://unix.stackexchange.com/questions/110022/how-do-i-find-out-the-keycodes-for-ctrlup-and-down-arrow-for-term-screen

**Comment by jtdaugherty** [comment]
I was able to get this to work by setting sequences for Ctrl-up/down as follows:

* Go to terminal preferences
* Click "Keyboard" for active profile
* Click "+"
* Select "Control" and "Cursor Up"
* For the sequence, click the text box, and press `ESC` `[` `1` `;` `5` `A`
(Similarly for Ctrl-Down, just `B` instead of `A`)

**Comment by jtdaugherty** [comment]
(But for future reference, Terminal.app tends to be more impoverished than iTerm2.)

**Comment by jtdaugherty** [comment]
Give this a try and if it works, please close this ticket (or let me know what else I need to do).

**Comment by dylanmc** [comment]
That workaround (/fix to Terminal) works great. Thanks! (/me shuffles off to download iTerm2)
