### ISSUE TITLE
Show instances for widgets would help debugging

### ISSUE THREAD

**Issue by simonmichael** [jtdaugherty/brick#63]
I have been defining dummy Show instances for List, Editor etc. so that I can include them in my application types which need to be Showable for debugging, testing in GHCI etc.
```haskell
instance Show (List a) where show _ = "<List>"
instance Show Editor   where show _ = "<Editor>"
```

**Comment by jtdaugherty** [comment]
I'm happy to add these, or consider pull requests if you'd like to submit what you have.  I should have time to get to this in the next few days.

**Comment by jtdaugherty** [comment]
Just to be clear: you mentioned wanting `Show` instances for widgets, but the types you mentioned (`List` and `Editor`) are state types.  So is this really a request for `Show` instances for some of the library's state types?

**Comment by simonmichael** [comment]
Uh, true I mean those state (widget state) types.

I'm note sure if the minimal instances above are a standard enough format that they don't break pretty-show, or if they need to be improved.
