### ISSUE TITLE
Add brick to stackage

### ISSUE THREAD

**Issue by niteria** [jtdaugherty/brick#67]
Please consider adding `brick` to stackage. The package already builds fine with GHC 8 and the stackage resolver:

```
$ cabal unpack brick
$ cd brick-0.8
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
$ stack init --resolver nightly --force --solver
...
$ stack build
...
Registering brick-0.8...
```

**Comment by jtdaugherty** [comment]
I don't support Stackage. From what I've been told, you can still use non-Stackage packages with stack builds, though.
