### ISSUE TITLE
Docs haven't built on Hackage for brick-0.8

### ISSUE THREAD

**Issue by seagreen** [jtdaugherty/brick#68]
It's not a problem for me because they're building locally fine, but I thought you might want to know.

**Comment by jtdaugherty** [comment]
Thanks! I've triggered a documentation rebuild on Hackage. We'll see if it works. :)

**Comment by jtdaugherty** [comment]
About a day later, no docs have built. I'll look into this a bit more but there isn't much I can do, unfortunately. Thanks for letting me know!

**Comment by seagreen** [comment]
Sure thing, thanks for the awesome library:)
