### ISSUE TITLE
Tree widget support

### ISSUE THREAD

**Issue by maoe** [jtdaugherty/brick#70]
Is there a plan to add a Tree widget?

**Comment by jtdaugherty** [comment]
I don't have any plans to add a tree widget to the library, but if someone were to write one with sufficient generality, it might be suitable for inclusion in the library.  (The trouble is that such widgets tend to have APIs that grow horribly out of control, making them hard to use even for simple tasks.)

**Comment by maoe** [comment]
Okay. I was wondering if this library was a good fit for CUI for a GHC time and allocation profiling reports, which have nested data. I think I'll see what I can do.

**Comment by jtdaugherty** [comment]
I see. Cool! If you end up developing that, I would be happy to take a look at the infrastructure that comes out of it.

**Comment by alok** [comment]
@maoe what did you end up coming up with?

**Comment by maoe** [comment]
@alok I think I ended up not using a tree view in my app.
