### ISSUE TITLE
`Eq` instances for Location and Cursor

### ISSUE THREAD

**Issue by geekingfrog** [jtdaugherty/brick#72]
I'm having to compare location quite often, and I'd like to avoid to define an orphan instance.
I can do the PR if you want (I believe ghc can derive `Eq` correctly anyway).
Any reason it's not there ?
(disclaimer, I'm fairly new to haskell)

**Comment by jtdaugherty** [comment]
I don't think there's any reason those aren't there.  If you want to write up a patch, I'd be happy to consider it.  Thanks!

**Comment by jtdaugherty** [comment]
I'm closing this due to the merged pull request.  Thanks for the patch!
