### ISSUE TITLE
Providing a frp interface

### ISSUE THREAD

**Issue by lspitzner** [jtdaugherty/brick#84]
Looking at the `App` datatype, it seems to me that the interface could be expressed more concisely using some frp library such as `reactive-banana` or `reflex`. (And for users that otherwise already use some frp approach it needs a nasty layer between frp and the current state-passing interface.)

Has this been considered before? Do there exist any forks or other vty-reverse-deps that go in this direction?

**Comment by jtdaugherty** [comment]
I don't know of any existing forks or applications that take this approach, and I haven't considered it before. Although I'm not open to rewriting brick to do this, I would be happy to work with anyone who wants to write an adapter library to expose an FRP interface.
