### ISSUE TITLE
lookupViewPort should default to vty

### ISSUE THREAD

**Issue by kquick** [jtdaugherty/brick#86]
If a widget is not placed into a viewport, but is rendered directly, lookupViewPort returns Nothing, which doesn't allow vpSize access and therefore the EventM processing will not have available size information.

A reasonable default for this scenario would probably be a "vty" viewport that provides the size of the current vty for rendering.

**Comment by jtdaugherty** [comment]
The point of `lookupViewport` is to tell you about how the most recent rendering pass sized a viewport. If the viewport you asked for wasn't rendered, it doesn't make any sense to return anything. If it returned the default you suggested, there would be no way to distinguish it from the case where something was, in fact, rendered.

**Comment by jtdaugherty** [comment]
It would also help me to understand what you're trying to accomplish with this recommendation in case there are alternatives that would work.

**Comment by jtdaugherty** [comment]
(That also goes for the other issue you created.)

**Comment by kquick** [comment]
Much of this is probably attributable to my being a novice with brick and trying to "get started" by experimenting (i.e. apologies for blundering around).  

In my case I had created a very simple Widget, using the List widget as a guide (of the available widgets to use as models, List seemed like a simple candidate that was actually an image generation widget; most of the others seem to be wrappers that modify an existing widget).
My widget did a simple rendering without wrapping itself within a viewport.  My assumption was that the caller would be responsible for the layout interactions and deciding if the widget should be in a scrolling region or not, and in the documentation the word "viewport" is almost always adjacent to the word "scrollable". List clearly used it because it handled partial visibility, but my initial widget implementation was more simplistic.

I can now see that the convention is to have each image generation Widget wrap itself into a viewport.  I initially missed this line in the List widget.  I had successfully gotten my widget to render (without a viewport specification, because I was deferring scrolling issues for later), and then began working on event handling.  While working on the event handling, I needed to know the width/height that the widget had rendered itself with and investigation lead me to the lookupViewport.  I made the (wrong) assumption that passing the Widget name to the lookupViewport would return an internal "viewport" for that Widget; this was exacerbated by having a very simple main (modelled after ListDemo) that only rendered my single widget and therefore also did not yet attempt to address scrolling issues (and therefore viewports).

I can see three possible solutions to help others getting started with brick:

1. Add more documentation for lookupViewport (it is only mentioned en-passant in the guide.rst doc) and clarify that it ONLY looks up explicit viewports.  Also document that widgets generating images must explicitly wrap themselves in a viewport if they want to use lookupViewport (or always if they are not a wrapper?).  Update the viewport documentation (or the create your own widget documentation) to indicate that a viewport is also the only way to get the rendered size of the widget (in addition to providing scrolling).

2. Allow lookupViewport to operate on Widget names as well as viewport names (possibly renamed).

3. Provide a getWidgetRenderedSize :: n -> (Int, Int) that is available to widgets in an `EventM n` context and works even without a viewport.

**Comment by jtdaugherty** [comment]
Thanks for that detailed explanation. I'd like to respond to some of it, but before I do, I'd like to know more about what you're trying to do at a high level. Given your description I'm not sure there isn't a better approach, and it would help me to know what you're trying to do. Even better, I'd love to be able to look at the program you're working on.

**Comment by kquick** [comment]
Offline discussions with Jonathan indicate that the underlying issues here will be handled by a future "Extents" enhancement to brick.  Closing this in anticipation of that future feature.

**Comment by jtdaugherty** [comment]
Extent support is now released in `0.12`.
