### ISSUE TITLE
lookupViewPort initially returns Nothing

### ISSUE THREAD

**Issue by kquick** [jtdaugherty/brick#87]
With appStartEvent set to `return` (as simpleMain suggests), the viewport map starts as M.empty and this does not get modified until the rendering phase *after* the first event is processed.  If the first event attempts to lookupViewPort to get the current size, it will return `Nothing`; subsequent event processing will get the `Just vp` value.  This makes the first event (typically a keypress) act differently than subsequent events.

**Comment by jtdaugherty** [comment]
This behavior of `lookupViewport` is both deliberate and a consequence of the design. However, it should only return `Nothing` in either of the following cases:
* It is called in `appStartEvent`, before any rendering could possibly be done, so no viewports are known
* It is called on a viewport that was not part of the most recent rendering pass, thus the viewport could not be located.

Is it returning `Nothing` in a situation not listed above?

**Comment by jtdaugherty** [comment]
Also, what version of `brick` are you using?

**Comment by kquick** [comment]
I am using brick 0.8.

I have a widget I have created that wraps itself in a viewport.  It also provides an event handler.  I have a main application that creates the widget and has a top-level event handler that calls the widget's event handler for events it does not handle.  The widget is roughly modelled on the implementation of brick's List Widget, and the application is similar to the ListDemo.

On startup, the Widget is initially rendered and appears on the screen.  If I then type a key that is handled by the Widget's event handler, and that event handler calls lookupViewport, I am getting back `Nothing` on that lookupViewport call for that keypress event (this should not match either of the two cases above).  On all *subsequent* keypresses, the lookupViewport returns a `Just` value; it is only the very first keypress (or event?) after the application is started that has this problem.  I am using `defaultMain { ..., appStartEvent = return, ...}`.

**Comment by jtdaugherty** [comment]
Regarding version: I suggest upgrading to at least 0.10, since there was a bugfix related to viewport information in `EventM` that should actually fix this problem.

**Comment by kquick** [comment]
Upgrading to brick 0.11 made the problem go away.  My apologies for not having ensured I was on the latest version before opening this issue.

**Comment by jtdaugherty** [comment]
I'm glad that fixed it!
