### ISSUE TITLE
Possible to turn a module like VisibilityDemo into a library?

### ISSUE THREAD

**Issue by seagreen** [jtdaugherty/brick#89]
I'm working on an application using brick that I'd like to support plugins. The idea is that each plugin would handle editing a different type of data. For instance someone might write a plugin for `iCalendar` data that allows drawing the UI and handling app events for editing calendar entries.

I run into problems when implementing this though. For UI drawing functions that include multiple widgets, the `Widget` type argument needs to be concrete. Using VisibilityDemo as an example:

```
module VisibilityDemo where

data Name = VP1
          | VP2
          | VP3

drawUi :: () -> [Widget Name]
```

I would like to be able to use it like so:
```
module Main where

import qualified VisibilityDemo as VD

data FullName = VisibilityDemoName VD.Name
              | Foo
              | Bar
              | Etc
```

And then have a way of modifying the `[Widget Name]` produced by VisibilityDemo into a `[Widget FullName]`.

This style of writing `drawUI` would have benefits even in simple libraries that aren't trying to do something weird like my custom plugin strategy, because the type system prevent the programmer from accidentally using `Foo`, `Bar`, etc. in the `VisibilityDemo` module when they meant to use `VP1` or `VP2`.

Unfortunately there's no way to modify `Widget`s without access to constructors from the Internal module. Might this be a useful tool for `brick` to provide?

**Comment by seagreen** [comment]
(Additionally, it would be really cool if there was a way to modify `EventM` widget names as well. That way both `drawUI` and `appEvent` could be written agnostic of the eventual master widget name data type. This seems much harder though, and from the little I understand of `EventM` might not even be possible)

**Comment by jtdaugherty** [comment]
Is it the case that you really need concrete name name values in your plugins' drawing routines?  If not, you can do
```
drawCustomValue :: YourConcreteValue -> n -> Widget n
drawCustomValue v n = ... $ viewport n ...
```
This way your drawing routines are totally polymorphic in the name type (which they should be, for exactly this reason: as a library author you don't want to have to worry about users' specific name types). The same approach will work for `EventM` functions.

Or is there more to why they can't be polymorphic in this way?

**Comment by seagreen** [comment]
> Or is there more to why they can't be polymorphic in this way?

Nope, that worked great! Sorry for the basic question -- I got hung up on trying to modify concrete types within `Widget`s, instead of just leaving them explicitly polymorphic.

**Comment by jtdaugherty** [comment]
No problem; I'm glad that suggestion was helpful. Let me know if there's anything further I can help with; otherwise please feel free to close this issue.

**Comment by seagreen** [comment]
Nope, everything else has been nicely intuitive!
